select 
MS_AOPTSIH as Id,
CASE
		WHEN MS_AOPTSIH = 1 THEN 'FOT'
		WHEN MS_AOPTSIH = 11 THEN 'CIF'
		ELSE ActionType
		END AS ActionType,
RANK() OVER (ORDER BY MS_AOPTSIH) AS Sort
from TBLT_PEOLOT_HZMNH_T_MSHLOCH