table dimPNL
	lineageTag: 0d2c5ad2-f0de-4bc5-a517-ef0ad815b88b

	column 'PNL Code'
		dataType: int64
		formatString: 0
		lineageTag: 5444408d-afb0-4b6e-847c-bf68e35f9ea8
		summarizeBy: none
		sourceColumn: PNL Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PNL Description'
		dataType: string
		lineageTag: 06481513-fb14-432c-b4d8-6a24cc57a3f0
		summarizeBy: none
		sourceColumn: PNL Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PNLKey
		dataType: int64
		formatString: 0
		lineageTag: 6c3aaf56-361d-4b2d-9518-d71966a3e6ad
		summarizeBy: none
		sourceColumn: PNLKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PNL Description Purchase'
		dataType: string
		lineageTag: 955e069e-2d4c-4602-82ad-2f77bcc82a98
		summarizeBy: none
		sourceColumn: PNL Description Purchase
		sortByColumn: 'PNL Sort'

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Expense Group'
		dataType: string
		lineageTag: 5e0c4b8a-6d1f-4e7c-b9a3-0f2d6c8e4a15
		summarizeBy: none
		sourceColumn: Expense Group
		sortByColumn: 'PNL Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'PNL Sort'
		dataType: int64
		formatString: 0
		lineageTag: 7a1e3c5f-9b2d-4e6a-8c0f-3d5b7e9a1c4f
		summarizeBy: none
		sourceColumn: PNL Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition dimPNL = m
		mode: import
		queryGroup: Dim
		source =
				let
				    Source = Sql.Database(#"SQL Address", "MT", [Query="-- dimPNL#(lf)SELECT#(lf)    QOD_SHROT          AS PNLKey,#(lf)    PNL                AS [PNL Code],#(lf)    SHM_SHROT          AS [PNL Description],#(lf)    p.PNL_Desc         AS [PNL Description Purchase],#(lf)    CASE#(lf)        WHEN PNL = 2270 THEN 'Discharge cost'#(lf)        WHEN PNL = 1111 THEN 'Shortage'#(lf)        WHEN PNL = 1201 THEN 'Demurrage / Despatch'#(lf)        ELSE 'Other Expenses'#(lf)    END                AS [Expense Group],#(lf)    CASE#(lf)        WHEN PNL = 2270 THEN 2#(lf)        WHEN PNL = 1111 THEN 3#(lf)        WHEN PNL = 1201 THEN 4#(lf)        ELSE 5#(lf)    END                AS [PNL Sort]#(lf)FROM HOTSAOT_SHROTIM_New h#(lf)LEFT JOIN (#(lf)    SELECT *#(lf)    FROM tblPnlList#(lf)    WHERE PNL_Type = 'OUT'#(lf)) p#(lf)  ON h.PNL = p.PNL_ID#(lf)#(lf)UNION ALL#(lf)#(lf)-- the extra ""Purchase of inventory"" row#(lf)SELECT#(lf)    999                AS PNLKey,#(lf)    '1010'             AS [PNL Code],#(lf)    ''                 AS [PNL Description],#(lf)    'Purchase of inventory' AS [PNL Description Purchase],#(lf)    'Purchase of inventory' AS [Expense Group],#(lf)    1                  AS [PNL Sort]"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"PNL Code", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

