table factOrders
	lineageTag: f7ecc82d-6f20-4d90-831e-79279651da87

	measure 'Total Cost' = ```
			SUM('factOrders'[LineTotalCost]) 
			```
		formatString: " #,#.##;(#,#.##)"
		displayFolder: עלות ורווחיות
		lineageTag: 767ea634-6fdb-4416-8f9e-01547991fbb6

		changedProperty = IsHidden

	measure 'Gross Profit' = [Total Sales NIS]-[Total Cost]
		formatString: " #,#.##;(#,#.##)"
		displayFolder: עלות ורווחיות
		lineageTag: 101d0782-d4ad-4029-806f-899bf5c4c015

		changedProperty = IsHidden

	measure 'רווח גולמי' = [Gross Profit]
		formatString: " #,#.##;(#,#.##)"
		displayFolder: עלות ורווחיות
		lineageTag: 24fd88ea-454a-47ca-97f5-5a6a09c56aff

		changedProperty = IsHidden

	measure '% Gross Profit' = DIVIDE([Gross Profit],ABS([Total Sales NIS]))
		formatString: #,0.0%;(#,0.0%);#,0.0%
		displayFolder: עלות ורווחיות
		lineageTag: 5766de76-569c-4489-9995-b1b03a9ae495

		changedProperty = IsHidden

	measure 'אחוז רווח' =
			[% Gross Profit]
			//[% Gross Profit]
		formatString: 0.0%;(0.0%);0.0%
		displayFolder: עלות ורווחיות
		lineageTag: 7c63658e-d2c6-4f00-a959-b0d2efb11b5a

		changedProperty = IsHidden

	measure 'Profit Comparison LY' = ```
			var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY] 
			return  CALCULATE([Gross Profit],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		displayFolder: עלות ורווחיות
		lineageTag: 8139cdfc-70dc-44d7-bc75-9380375c3353

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Profit_Comparison LY' = ```
			var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY] 
			return  CALCULATE([% Gross Profit],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: עלות ורווחיות
		lineageTag: 34e30a70-83ba-4f20-9263-a494e0bedad0

		changedProperty = IsHidden

	measure '% Change Profit LY' = DIVIDE([Gross Profit]-[Profit Comparison LY],[Profit Comparison LY])
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: עלות ורווחיות
		lineageTag: f4a7a529-480f-4563-9efc-7d58e1bdc035

		changedProperty = IsHidden

	measure '% Gross Profit Current Year' =
			
			 IF(HASONEVALUE(dimDates[Year]),[% Gross Profit],
				 CALCULATE(
				TOTALYTD([% Gross Profit],
					dimDates[Date],
					dimDates[IsHistory]=1
				),
				dimDates[IsHistory]=1
				))
		formatString: #,0%;-#,0%;#,0%
		displayFolder: עלות ורווחיות
		lineageTag: 2d31c677-9748-418f-8325-e0ed3ce6f9e7

		changedProperty = IsHidden

	measure 'Change % Gross Profit Comparison LY' =
			
			[% Gross Profit Current Year] - [% Profit_Comparison LY]
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: עלות ורווחיות
		lineageTag: 08cf7b19-8ab8-463e-a793-bed86ef941c4

		changedProperty = IsHidden

	measure 'אחוז רווח השוואה' = CALCULATE([אחוז רווח],ALL(dimDates),USERELATIONSHIP(factOrders[Date],Sub_DimDates[Date]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: עלות ורווחיות
		lineageTag: 5533251a-4d1b-4a5b-8a27-3960c1cec50c

		changedProperty = IsHidden

	measure 'רווח גולמי השוואה' = CALCULATE([רווח גולמי],ALL(dimDates),USERELATIONSHIP(factOrders[Date],Sub_DimDates[Date]))
		formatString: #,0
		displayFolder: עלות ורווחיות
		lineageTag: 2785f014-689b-4569-bc58-0e8f65f8aeb4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Gross Profit Comparison LY' = ```
			var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY] 
			return  CALCULATE([Gross Profit],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		displayFolder: עלות ורווחיות
		lineageTag: ed8e924c-f183-42d3-84a5-6bcbecbd7562

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure מכירות = [Total Sales]
		formatString: #,0
		displayFolder: מכירות כללי
		lineageTag: b5afcf16-50ec-4e53-936b-6f8371f35ffb

		changedProperty = IsHidden

	measure 'כמות לקוחות' = ```
			[Customers Quant] 
			```
		formatString: #,0
		displayFolder: מכירות כללי
		lineageTag: 7258e74a-970b-454c-98a4-8c55bcd4e4a9

		changedProperty = IsHidden

	measure 'ממוצע מכירות ליום' =
			DIVIDE([מכירות],
				[כמות ימים עם מכירה])
		formatString: #,0
		displayFolder: מכירות כללי
		lineageTag: 4e4dec1f-3510-4c12-b717-fd664e5d730d

		changedProperty = IsHidden

	measure 'ממוצע מכירות ליום 3 שבועות קודמים' = CALCULATE([ממוצע מכירות ליום],ALL(dimDates),DATESBETWEEN(dimDates[Date],MIN('factOrders'[Date])-21,MIN('factOrders'[Date])-1))
		formatString: #,0
		displayFolder: מכירות כללי
		lineageTag: f62d3d25-a298-4a23-b5fc-1ac39319ba24

		changedProperty = IsHidden

	measure 'מכירות השוואה' = CALCULATE([מכירות],ALL(dimDates),USERELATIONSHIP(FactOrders[Date],Sub_DimDates[Date]))
		formatString: #,0
		displayFolder: מכירות כללי
		lineageTag: 56eb9d32-ec2f-434b-90f2-a6af1c3d8793

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'ממוצע מכירות ליום שנתי' =
			
			/*
			VAR ThisMonth=CALCULATE(MAX(dimDates[YearMonthSum]),dimDates[IsHistory]=1)
			return
			 CALCULATE([ממוצע מכירות ליום],FILTER(dimDates,dimDates[YearMonthSum]=ThisMonth))*/
			 CALCULATE(CALCULATE([ממוצע מכירות ליום],DATESYTD(dimDates[Date])),dimDates[IsHistory]=1)
		displayFolder: מכירות כללי
		lineageTag: e2173632-a992-436b-96d9-896c969156e1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Quantity' = SUM('factOrders'[Quantity])
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: e4831819-3665-4db0-9b6d-6ed472c449e9

		changedProperty = IsHidden

	measure 'כמות מכירה' = [Total Quantity]
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: 2db214c8-292d-4119-80ef-7af419218772

		changedProperty = IsHidden

	measure 'Quantity Comparison LY' = ```
			
			 var MinDate = [Mindate - LY] 
			 var MaxDate = [Maxdate - LY] 
			return  CALCULATE([Total Quantity],DATEADD(dimDates[Date],-1,YEAR),DATEADD(Sub_DimDates[Date],-1,YEAR))
			
			```
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: 3eca36a3-16ce-4be0-94eb-5174caf6e757

		changedProperty = IsHidden

	measure 'Total Quantity Current Year' =
			
			VAR _YEAR = YEAR(CALCULATE(MAX(dimDates[Date]),ALL(dimDates),dimDates[IsHistory]=1))
			
			RETURN
			CALCULATE([Total Quantity],Sub_DimDates[Year]=_YEAR)
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: ee0d20d1-d6c2-4796-8761-d4f05eef7704

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '% Change Quantity Comparison LY' =
			
			DIVIDE([Total Quantity]-[Quantity Comparison LY],[Quantity Comparison LY])
		formatString: 0.00%;(0.00%);0.00%
		displayFolder: כמויות
		lineageTag: a82aa52f-2213-42a5-bb54-9db7d159f0ab

		changedProperty = IsHidden

	measure 'אחוז שינוי כמות מכירה אשתקד' = [% Change Quantity Comparison LY]
		formatString: 0.00%;(0.00%);0.00%
		displayFolder: כמויות
		lineageTag: 3a06e593-0858-4346-97ac-3c6c31097a5e

		changedProperty = IsHidden

	measure 'כמות מכירה השוואה' = CALCULATE([כמות מכירה],ALL(dimDates),USERELATIONSHIP(factOrders[Date],Sub_DimDates[date]))
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: 9013447e-5b65-4341-ace2-6ae6d3c60791

		changedProperty = IsHidden

	measure '% Change Transaction Quantity Comparison LY' =
			
			DIVIDE([Transactions Quantity Current Year]-[Transactions Quantity Comparison LY],[Transactions Quantity Comparison LY])
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: כמויות
		lineageTag: ec8ecfe0-b656-4439-a028-6a825c071d7e

		changedProperty = IsHidden

	measure 'Quantity YTD' = CALCULATE(CALCULATE([Total Quantity],DATESYTD(dimDates[Date]),DATESYTD(Sub_DimDates[Date])),dimDates[IsHistory]=1,Sub_DimDates[IsHistory]=1)
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: db6b6019-1aef-47ee-81d8-6012d088f481

		changedProperty = IsHidden

	measure 'Quantity LY YTD' = CALCULATE(CALCULATE([Quantity Comparison LY],DATESYTD(dimDates[Date]),DATESYTD(Sub_DimDates[Date])),dimDates[IsHistory]=1,Sub_DimDates[IsHistory]=1)
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: fc35c581-195e-4679-b4bc-0c52ad7c0389

		changedProperty = IsHidden

	measure 'Quantity Comparison LY YTD Full' = ```
			var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY_Full] 
			return CALCULATE([Quantity YTD],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: 18580b62-815b-4c64-bb48-7f16ba81fec7

		changedProperty = IsHidden

	measure 'Quantity MTD' =
			
			VAR ThisMonth=CALCULATE(MAX(dimDates[YearMonthSum]),dimDates[IsHistory]=1)
			VAR SubThisMonth=CALCULATE(MAX(Sub_DimDates[YearMonthSum]),Sub_DimDates[IsHistory]=1)
			VAR _Month = IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),SubThisMonth,ThisMonth)
			return
			CALCULATE([Total Quantity],dimDates[YearMonthSum]=_Month)
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: b73e73a0-345a-44a8-ab85-28aadb36eeab

		changedProperty = IsHidden

	measure 'Quantity Comparison LY MTD' = ```
			
			VAR ThisMonth=CALCULATE(MAX(dimDates[YearMonthSum]),dimDates[IsHistory]=1)
			VAR SubThisMonth=CALCULATE(MAX(Sub_DimDates[YearMonthSum]),Sub_DimDates[IsHistory]=1)
			VAR _Month = IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),SubThisMonth,ThisMonth)
			
			return 
			CALCULATE(CALCULATE([Quantity MTD],DATEADD(dimDates[Date],-1,YEAR),DATEADD(Sub_DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1)
			```
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: c5b0125c-4dd8-4eae-939c-6e6b23a5cda9

		changedProperty = IsHidden

	measure 'Quantity Comparison LY MTD Full' = ```
			var MinDate = [Mindate - LY] var MaxDate = [Maxdate MTD - LY_Full] 
			return  CALCULATE([Quantity MTD],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: 5bea66bb-d4ae-4ee6-bc54-27ad0beaf233

		changedProperty = IsHidden

	measure 'Quantity Comparison LM' = ```
			var MinDate = [Mindate - LM] var MaxDate = [Maxdate - Lm] 
			return  CALCULATE([Quantity MTD],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: ba3569e0-38b9-4364-a019-5127454d5a6a

		changedProperty = IsHidden

	measure 'Quantity Comparison LM Full' = ```
			var MinDate = [Mindate - LM] var MaxDate = [Maxdate - LM_Full] 
			return  CALCULATE([Quantity MTD],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: 2b926160-609b-4bbd-9c6e-1799ccf269a8

		changedProperty = IsHidden

	measure '% change YTD Quantity LY Comparsion' = DIVIDE([Quantity YTD]-[Quantity LY YTD],[Quantity LY YTD],1)
		formatString: #,0.0%;(#,0.0%);#,0.0%
		displayFolder: כמויות
		lineageTag: f961b76d-3dda-44c5-bf23-cae02a80bba3

		changedProperty = IsHidden

	measure '% Change Quantity Comparison LY YTD - Full' = DIVIDE([Quantity YTD]-[Quantity Comparison LY YTD Full],[Quantity Comparison LY YTD Full])
		formatString: #,0.0%;(#,0.0%);#,0.0%
		displayFolder: כמויות
		lineageTag: e25fea28-abb2-4f58-9700-1ca831984a2f

		changedProperty = IsHidden

	measure '% Change Quantity LY MTD Comparison' = DIVIDE([Quantity MTD]-[Quantity Comparison LY MTD],([Quantity Comparison LY MTD]))
		formatString: #,0%;(#,0%);#,0%
		displayFolder: כמויות
		lineageTag: 2fce5a7e-3499-4321-9246-9d14b95461f1

		changedProperty = IsHidden

	measure '% Change Quantity Comparison LY MTD - Full' = DIVIDE([Quantity MTD]-[Quantity Comparison LY MTD Full],[Quantity Comparison LY MTD Full])
		formatString: #,0.0%;(#,0.0%);#,0.0%
		displayFolder: כמויות
		lineageTag: c45bbc7e-d1a0-4f41-80cb-ac1affb5d234

		changedProperty = IsHidden

	measure '% Change Quantity LM Comparison' = DIVIDE([Quantity MTD]-[Quantity Comparison LM],ABS([Quantity Comparison LM]))
		formatString: 0.0%;(0.0%);0.0%
		displayFolder: כמויות
		lineageTag: 7627044d-6ef4-4a9d-9031-620736af9773

		changedProperty = IsHidden

	measure '% Change Quantity Comparison LM - Full' = DIVIDE([Quantity MTD]-[Quantity Comparison LM Full],[Quantity Comparison LM Full])
		formatString: #,0.0%;(#,0.0%);#,0.0%
		displayFolder: כמויות
		lineageTag: 50c8df90-6b14-482b-b38c-89340792fef3

		changedProperty = IsHidden

	measure 'Quantity Comparison LY Full' = ```
			var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY_Full] 
			return  CALCULATE([Total Quantity],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		formatString: " #,#.##;(#,#.##)"
		displayFolder: כמויות
		lineageTag: 1b1f426b-2e45-4067-8b07-d8794a005525

		changedProperty = IsHidden

	measure 'Sales Comparison LY' = ```
			var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY] 
			return  CALCULATE([Total Sales],DATEADD(dimDates[Date],-1,YEAR),DATEADD(Sub_DimDates[Date],-1,YEAR))
			```
		displayFolder: מכירות אשתקד
		lineageTag: 658dddb0-490a-4441-bbd9-45aaca181f5c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'מכירות אשתקד' = ```
			
			 [Sales Comparison LY]
			```
		formatString: #,0
		displayFolder: מכירות אשתקד
		lineageTag: b1d76cf2-84f5-456f-9bd4-5d9895a39a64

		changedProperty = IsHidden

	measure 'מכירות מצטברות אשתקד' = [Sales LY YTD]
		formatString: #,0
		displayFolder: מכירות אשתקד
		lineageTag: 12953910-98b5-4443-896d-19afaa11fcd2

		changedProperty = IsHidden

	measure '% Change Sales Comparison LY - Full' = DIVIDE([Total Sales]-[Sales Comparison LY Full],[Sales Comparison LY Full])
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: מכירות אשתקד
		lineageTag: 6b5a388f-a78a-4047-9fab-31c050088ed9

		changedProperty = IsHidden

	measure 'Sales Comparison LY Full' = ```
			var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY_Full] 
			return  CALCULATE([Total Sales],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		displayFolder: מכירות אשתקד
		lineageTag: 2ad97a9b-50e6-4fbd-a4b3-1d7f96386d6a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Change Sales Comparison LY YTD - Full' = DIVIDE([Sales YTD]-[Sales Comparison LY YTD Full],[Sales Comparison LY YTD Full])
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: מכירות אשתקד
		lineageTag: 72ca4bcc-17c9-4eb5-9ef4-87981a5f232d

		changedProperty = IsHidden

	measure 'מכירות אשתקד - עד סוף חודש' =
			
			CALCULATE([Sales Comparison LY Full],dimDates[UntilNextMonth]=1)
		formatString: #,0
		displayFolder: מכירות אשתקד
		lineageTag: 89280b2a-7120-452c-845b-9f0754547377

		changedProperty = IsHidden

	measure 'מגוון מוצרים' = [Items Variety]
		formatString: #,0
		displayFolder: מגוון
		lineageTag: 2ed36ee6-4597-4a02-8db2-603989cf867a

		changedProperty = IsHidden

	measure 'Variety Per Client' = AVERAGEX(VALUES(dimCustomers[שם לקוח]),[Items Variety])
		formatString: 0
		displayFolder: מגוון
		lineageTag: 82112153-a68e-4f02-a07f-dde5bbe7f1b9

		changedProperty = IsHidden

	measure 'Variety Per Client Comparison LY' = ```
			
			 var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY] 
			return  CALCULATE([Variety Per Client],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			
			```
		displayFolder: מגוון
		lineageTag: a7fcb352-78db-4ded-b1fb-110569262f00

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Variety YTD' = CALCULATE([Items Variety],DATESYTD(dimDates[Date]))
		formatString: 0
		displayFolder: מגוון
		lineageTag: 248712f5-b9b2-4c3c-a4ca-2ac395ac6cc8

		changedProperty = IsHidden

	measure 'Variety LY YTD' = CALCULATE([Variety Per Client Comparison LY],DATESYTD(dimDates[Date]))
		displayFolder: מגוון
		lineageTag: f2d46070-6888-4423-88b0-6596131c167b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'אחוז שינוי מצטבר' = [% change YTD sales LY Comparsion]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: אחר
		lineageTag: b65d663a-974b-4933-a602-c84df2862ef9

		changedProperty = IsHidden

	measure 'מכר ליום זהה -ממוצע 3 שבועות אחרונים' =
			
			DIVIDE(CALCULATE([Total Sales],DATEADD(dimDates[Date],-21,DAY))+
			CALCULATE([Total Sales],DATEADD(dimDates[Date],-14,DAY))+CALCULATE( [Total Sales],DATEADD(dimDates[Date],-7,DAY)),3)
		formatString: #,0
		displayFolder: אחר
		lineageTag: 018be052-5817-46ed-8d92-ee362623e458

		changedProperty = IsHidden

	measure 'סהכ ימים בבחירה' = CALCULATE(COUNTROWS(dimDates),dimDates[IsHistory]=1)
		formatString: 0
		displayFolder: אחר
		lineageTag: 799dfe34-5f72-4512-a86f-35e5dd260222

		changedProperty = IsHidden

	measure 'ממוצע ימים בין מכירה' =
			DIVIDE([סהכ ימים בבחירה],
			    [כמות ימים עם מכירה])
		formatString: #,0
		displayFolder: אחר
		lineageTag: 9e68f375-c034-4d81-b8d3-e538c70b2f1b

		changedProperty = IsHidden

	measure 'Sales Comparison LM' = ```
			var MinDate = [Mindate - LM] var MaxDate = [Maxdate - Lm] 
			return  CALCULATE([Sales MTD],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		displayFolder: מכירות חודשי
		lineageTag: 8601b550-0b58-4afd-b1b9-8dd6506e6d85

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Comparison LM Full' = ```
			var MinDate = [Mindate - LM] var MaxDate = [Maxdate - LM_Full] 
			return  CALCULATE([Sales MTD],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		displayFolder: מכירות חודשי
		lineageTag: 8ed7469f-79d7-4ad8-91b8-ca50f69736a6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Change Sales LM Comparison' = DIVIDE([Sales MTD]-[Sales Comparison LM],ABS([Sales Comparison LM]))
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: מכירות חודשי
		lineageTag: a1503abf-97a9-4fb8-8305-687f3b37add3

		changedProperty = IsHidden

	measure '% Change Sales Comparison LM - Full' = DIVIDE([Sales MTD]-[Sales Comparison LM Full],[Sales Comparison LM Full])
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: מכירות חודשי
		lineageTag: debf794b-8766-472d-a1e8-f48b3f336c20

		changedProperty = IsHidden

	measure 'Sales MTD' =
			
			VAR ThisMonth=CALCULATE(MAX(dimDates[YearMonthSum]),dimDates[IsHistory]=1)
			VAR SubThisMonth=CALCULATE(MAX(Sub_DimDates[YearMonthSum]),Sub_DimDates[IsHistory]=1)
			VAR _Month = IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),SubThisMonth,ThisMonth)
			return
			CALCULATE([Total Sales],FILTER(dimDates,dimDates[YearMonthSum]=_Month))
		formatString: #,0.0
		displayFolder: מכירות חודשי
		lineageTag: 2cac63f4-1f91-479c-91a4-ab5f4b3e5916

		changedProperty = IsHidden

	measure 'Sales Comparison LY MTD' = ```
			
			var MinDate = [Mindate - LY] 
			var MaxDate = [Maxdate - LY] 
			return  CALCULATE(CALCULATE([Sales MTD],DATEADD(dimDates[Date],-1,YEAR),DATEADD(Sub_DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1)
			```
		formatString: #,0.0
		displayFolder: מכירות חודשי
		lineageTag: ac1eecfc-fdde-4af0-b8e2-e4a229e446a7

		changedProperty = IsHidden

	measure '% Change Sales LY MTD Comparison' = DIVIDE([Sales MTD]-[Sales Comparison LY MTD],([Sales Comparison LY MTD]))
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: מכירות חודשי
		lineageTag: d8bdce10-97f5-4a99-a8d5-4d9387a6e0e0

		changedProperty = IsHidden

	measure 'מכירות חודשי' = [Sales MTD]
		formatString: #,0
		displayFolder: מכירות חודשי
		lineageTag: 6011c20f-ab25-44bf-9a19-6a98474cf858

		changedProperty = IsHidden

	measure 'Sales Comparison LY MTD Full' = ```
			var MinDate = [Mindate - LY] var MaxDate = [Maxdate MTD - LY_Full] 
			return  CALCULATE([Sales MTD],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		formatString: #,0.0
		displayFolder: מכירות חודשי
		lineageTag: dd1d9768-959e-47f0-9553-a34e7ceb278b

		changedProperty = IsHidden

	measure '% Change Sales Comparison LY MTD - Full' = DIVIDE([Sales MTD]-[Sales Comparison LY MTD Full],[Sales Comparison LY MTD Full])
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: מכירות חודשי
		lineageTag: 6eee2edd-19cc-415c-a8b8-143a9c857af8

		changedProperty = IsHidden

	measure 'ממוצע מכירות ליום חודשי' = ```
			
			VAR ThisMonth=CALCULATE(MAX(dimDates[YearMonthSum]),dimDates[IsHistory]=1)
			return
			 CALCULATE([ממוצע מכירות ליום],FILTER(dimDates,dimDates[YearMonthSum]=ThisMonth))
			
			```
		formatString: #,0
		displayFolder: מכירות חודשי
		lineageTag: 0e5d56cc-3965-40a6-bc1c-f21ffe0b3814

		changedProperty = IsHidden

	measure 'לקוחות חדשים' = ```
			
			
			SUMX(
			    VALUES(dimDates[MonthInCalendarName]),
			CALCULATE(COUNTROWS (
			
			    FILTER (
			        ADDCOLUMNS (
			            //CROSSJOIN(VALUES(factSales[AccountKey]),VALUES(factSales[AgentKey])),
			            VALUES ('factOrders'[AccountKey]), 
			            "PreviousSales", 
			                CALCULATE (
			                  
			                    COUNTROWS ( 'factOrders'), //Original Calc
			                    ALL(dimCustomers),
			                    FILTER (
			                        ALL ( dimDates ),
			                        dimDates[Date] < min(dimDates[Date])
			                    )
			                )
			                ,"ThisSales"
			              ,[Total Sales]
			        ),
			      
			          [PreviousSales]=0
			          && [ThisSales]>0
			         
			    )
			)))
			```
		formatString: #,0
		displayFolder: לקוחות
		lineageTag: c1b7467f-b1a2-4f5d-b51e-e6407c37224d

		changedProperty = IsHidden

	measure 'Transactions Quantity' = ```
			DISTINCTCOUNT('factOrders'[OrderID]) 
			```
		formatString: #,0
		displayFolder: עסקאות
		lineageTag: d682a4f5-02ee-4305-a0d4-7ddbb9a38465

		changedProperty = IsHidden

	measure 'Transactions Quantity Current Year' =
			
			 IF(HASONEVALUE(dimDates[Year]),[Transactions Quantity],
				 CALCULATE(
				TOTALYTD([Transactions Quantity],
					dimDates[Date],
					dimDates[IsHistory]=1
				),
				dimDates[IsHistory]=1
				))
		formatString: #,0
		displayFolder: עסקאות
		lineageTag: 5b809784-951d-47c3-87e3-c712718486be

		changedProperty = IsHidden

	measure 'ממוצע מכירה לעסקה' = ```
			DIVIDE(
				[Total Sales],
				[Transactions Quantity]) 
			```
		formatString: #,0
		displayFolder: עסקאות
		lineageTag: e341e169-ea75-4634-b65c-5239900fa034

		changedProperty = IsHidden

	measure 'כמות עסקאות' = [Transactions Quantity]
		formatString: #,0
		displayFolder: עסקאות
		lineageTag: 63e094a6-22fb-479a-a1e7-eea0485d9ec3

		changedProperty = IsHidden

	measure 'Transactions Quantity Comparison LY' = ```
			
			 var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY] 
			return  CALCULATE([Transactions Quantity],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		formatString: #,0
		displayFolder: עסקאות
		lineageTag: 0446ac0c-c482-41c9-9920-0ab4f072ccac

		changedProperty = IsHidden

	measure 'עסקאות השוואה' = CALCULATE([כמות עסקאות],ALL(dimDates),USERELATIONSHIP(factOrders[Date],Sub_DimDates[Date]))
		formatString: #,0
		displayFolder: עסקאות
		lineageTag: b95b4187-a140-44b5-ad3f-9deeea379850

		changedProperty = IsHidden

	measure 'ממוצע לעסקה השוואה' = CALCULATE([ממוצע מכירה לעסקה],ALL(dimDates),USERELATIONSHIP(factOrders[Date],Sub_DimDates[Date]))
		formatString: #,0
		displayFolder: עסקאות
		lineageTag: b495a714-b4b8-40f5-bdf7-e89ceaa7dd1b

		changedProperty = IsHidden

	measure 'ממוצע מכירה לעסקה אשתקד' = ```
			var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY] 
			return  CALCULATE([ממוצע מכירה לעסקה],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		formatString: #,0
		displayFolder: עסקאות
		lineageTag: 23d4d4d9-50ea-4bf3-b9cd-d0504d573d10

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'חידושים/ צירופים חודשי' =
			
			VAR ThisMonth=CALCULATE(MAX(dimDates[YearMonthSum]),dimDates[IsHistory]=1)
			return
			 CALCULATE([כמות צירופים/חידושים],FILTER(dimDates,dimDates[YearMonthSum]=ThisMonth))
		formatString: #,0
		displayFolder: מועדון לקוחות
		lineageTag: ee503883-27bb-4952-ae15-7f0c877ab87f

		changedProperty = IsHidden

	measure 'מכירות למצטרפים' =
			
			SUMX(CROSSJOIN(dimCustomers,VALUES(dimDates[MonthInCalendarName])),CALCULATE(
			    if([כמות צירופים/חידושים]
			    >0,
			   [מכירות]
			    ,BLANK())))
		displayFolder: מועדון לקוחות
		lineageTag: e86cdc04-4b82-432f-aab3-3a9c5d9a42a8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ממוצע לעסקה למצטרפים' = ```
			
			AVERAGEX(CROSSJOIN(dimCustomers,VALUES(dimDates[MonthInCalendarName])),CALCULATE(
			    if([כמות צירופים/חידושים]
			    >0,
			   [ממוצע מכירה לעסקה] 
			    ,BLANK())))
			```
		formatString: 0
		displayFolder: מועדון לקוחות
		lineageTag: 70b06891-5990-4b32-bc07-4edd4f105ea4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'סהכ הנחות' = SUM('factOrders'[LineTotalDiscount])
		formatString: #,0
		displayFolder: הנחות
		lineageTag: 22af5f72-c9f0-48f2-aa2a-a77130fe8f1b

		changedProperty = IsHidden

	measure 'Total Sales' =
			//SUM(factSales[LineTotalNet])
				SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
					1,[Total Sales NIS],
					2,[Total Sales USD],
			   [Total Sales USD])
		lineageTag: 24487d62-1074-4b25-8691-3b51b4e56257

		formatStringDefinition =
				SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
				1,"₪ ,#,0.00",
				2,"$ ,#,0.00",
				"$ ,#,0.00")

		changedProperty = IsHidden

	measure '% Change Sales LY Comparison' = DIVIDE([Total Sales Current Year]-[Sales Comparison LY],([Sales Comparison LY]))
		formatString: 0.0%;(0.0%);0.0%
		lineageTag: 624bd916-452a-46c2-a6b0-15eb1f7e01b5

		changedProperty = IsHidden

	measure 'Forecast This Month' = CALCULATE([Sales Per Day This Month]*[Working Days in Selected Period])
		formatString: " #,#.##;(#,#.##)"
		lineageTag: f9d8fde4-0821-4450-bed7-e61f41ba9da4

		changedProperty = IsHidden

	measure 'Customers Quant' = DISTINCTCOUNT('factOrders'[AccountKey])
		formatString: " #,#.##;(#,#.##)"
		lineageTag: 9db08f18-4c9f-4196-92f0-8da2c4332325

		changedProperty = IsHidden

	measure 'Items Variety' = DISTINCTCOUNT('factOrders'[ItemKey])
		formatString: #,0
		lineageTag: 1434685c-d9a1-4b25-97ca-a2cb86235d48

		changedProperty = IsHidden

	measure '% From Sales' = DIVIDE([Total Sales],CALCULATE([Total Sales],ALLSELECTED('factOrders')))
		formatString: 0.00%;(0.00%);0.00%
		lineageTag: 326b1bda-7a37-4fd3-92f5-b9a807ae22a4

		changedProperty = IsHidden

	measure 'Sales LY YTD' = CALCULATE(CALCULATE([Sales YTD],DATEADD(dimDates[Date],-1,YEAR),DATEADD(Sub_DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1,Sub_DimDates[IsHistory])
		lineageTag: 5a3d9335-9a13-4022-af19-74ab9f54f56f

		formatStringDefinition =
				SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
				1,"₪ ,#,0.00",
				2,"$ ,#,0.00",
				"$ ,#,0.00")

		changedProperty = IsHidden

	measure 'Sales YTD' = CALCULATE(CALCULATE([Total Sales],DATESYTD(dimDates[Date]),DATESYTD(Sub_DimDates[Date])),dimDates[IsHistory]=1,Sub_DimDates[IsHistory]=1)
		lineageTag: 58c3d8da-ea55-4ef0-97b7-1232cdf0e821

		formatStringDefinition =
				SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
				1,"₪ ,#,0.00",
				2,"$ ,#,0.00",
				"$ ,#,0.00")

		changedProperty = IsHidden

	measure 'AVG Client Sales' = DIVIDE([Total Sales],[Customers Quant])
		formatString: #,0
		lineageTag: 058dc9af-b8b1-4021-976d-55db8cba6d06

		changedProperty = IsHidden

	measure 'AVG Client Sales_Comparison LY' = ```
			
			
			 var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY] 
			return  CALCULATE([AVG Client Sales],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			
			```
		lineageTag: cb65b4d3-8ae7-48c5-b6d5-0c876c8fc1f0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Category with Sales' = CALCULATE(SUMX(VALUES(dimItems[קטגוריה]),[Total Sales]),ALL(dimItems[שם מוצר]))
		lineageTag: 2e689a8f-e2f3-48be-84c3-67a507bed10e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Items With No Sales Per Client' = ```
			IF( CALCULATE([Total Sales],ALL(dimItems))>0 && ISBLANK([Total Sales]) && NOT(ISBLANK([Category with Sales])) && NOT(ISBLANK([Customer Category with Sales]))
			
			,1,BLANK())
			
			```
		lineageTag: d97cac75-4691-4f63-b4fa-e2a88d0746a7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Change Periods Comparison - Variety' = DIVIDE([Variety Per Client]-[Variety Per Client Comparison LY],[Variety Per Client Comparison LY])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: aa97f9b5-49b3-446a-95bf-b0bbf831f593

		changedProperty = IsHidden

	measure 'AVG Sales all customers' = ```
			IF(HASONEVALUE(dimItems[ItemKey]),CALCULATE([AVG Client Sales],ALL(dimCustomers[שם לקוח])),CALCULATE(SUMX(ADDCOLUMNS(VALUES(dimItems[ItemKey]),"SumParts",CALCULATE([AVG Client Sales],ALL(dimCustomers))),[SumParts])))
			
			```
		formatString: #,0
		lineageTag: 834a5b62-ae35-4664-9311-f1161eaab457

		changedProperty = IsHidden

	measure 'Client With No Sales Per Item' =
			IF( ISBLANK([Total Sales]) ,0,[Total Sales])
			
			//NOT(ISBLANK([Category with Sales])) && NOT(ISBLANK([Customer Category with Sales])
			//IF( ISBLANK([Total Sales]) ,0,[Total Sales])
			/*IF( CALCULATE([Total Sales],ALL(dimItems))>0 && ISBLANK([Total Sales]) && NOT(ISBLANK([Category with Sales])) && NOT(ISBLANK([Customer Category with Sales]))
			,1,BLANK())*/
		lineageTag: 98879b3f-d5e0-40bb-adfc-bb9ec4bfd376

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales All periods' = IF([Client With No Sales Per Item]=0 && NOT(ISBLANK([Client With No Sales Per Item])), CALCULATE([Total Sales],ALL(dimDates)),BLANK())
		lineageTag: 2ec436b8-7948-4f73-82e5-e9a0f8a004c3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Comparison LY YTD Full' = ```
			var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY_Full] 
			return CALCULATE([Sales YTD],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			
			```
		formatString: #,0.00
		lineageTag: 9b402fc1-7751-49a8-b415-d8b3468a6aee

		changedProperty = IsHidden

	measure 'Avg Unit Price Comparison LY' = ```
			var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY] 
			return  CALCULATE([Avg Unit Price],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5c43e46a-1fcf-4b9b-8f8c-fb89a3bdec5c

		changedProperty = IsHidden

	measure 'Sales YTD Last Month' = CALCULATE([Sales YTD],dimDates[Show Months]="חודש שעבר")
		formatString: #,0
		lineageTag: d4a5587b-4be0-4838-b9a8-433e6fd083eb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '% change YTD sales LY Comparsion' = DIVIDE([Sales YTD]-[Sales LY YTD],[Sales LY YTD])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 7e35962f-2b7b-4d12-a84c-234da2b9334f

		changedProperty = IsHidden

	measure '% change YTD sales until LY Comparsion to LY' = CALCULATE([% change YTD sales LY Comparsion],dimDates[Show Months]="חודש שעבר")
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 19eb9743-0386-4eb4-ad71-795dedf37dfe

		changedProperty = IsHidden

	measure 'Sales Per Day This Month' = CALCULATE([Total Sales],dimDates[Show Months]="החודש")
		lineageTag: dca16c95-3191-4518-9dcd-05a2e6d3d2e1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'כמות ימים עם מכירה' =
			DISTINCTCOUNT('factOrders'[Date])
			// Sum(dimDates[Is Working Day]) // use if you want by working days
			//DISTINCTCOUNT(factSales[Date]) // use by invoice dates
			//COUNTROWS(dimDates) // use for all Days
		formatString: 0
		lineageTag: 6887aad5-a3f2-4b92-bcb9-09ad7c16f610

		changedProperty = IsHidden

	measure 'Total Sales NIS' =
			
			SUM('factOrders'[LineTotalNetNIS])
		formatString: "₪"\ #,0.00;"₪"-#,0.00;"₪"\ #,0.00
		lineageTag: 82c5d662-c6d4-4187-abe3-7340d92e4834

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"he-IL"}

	measure 'Total Sales USD' =
			
			SUM('factOrders'[LineTotalNetUSD])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3d9829ef-b476-4e53-8ce5-a694b997a995

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Sales Current Year' =
			
			 IF(HASONEVALUE(dimDates[Year]),[מכירות],
				 CALCULATE(
				TOTALYTD([מכירות],
					dimDates[Date],
					dimDates[IsHistory]=1
				),
				dimDates[IsHistory]=1
				))
		lineageTag: 9cbcd805-d7b9-4d0d-8b51-734028af6421

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Sale per Transaction Current Year' =
			
			 IF(HASONEVALUE(dimDates[Year]),[ממוצע מכירה לעסקה],
				 CALCULATE(
				TOTALYTD([ממוצע מכירה לעסקה],
					dimDates[Date],
					dimDates[IsHistory]=1
				),
				dimDates[IsHistory]=1
				))
		lineageTag: 7904fb7d-a270-404b-9170-bf77924e797b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Sale per Transaction Comparison LY' = ```
			var MinDate = [Mindate - LY] var MaxDate = [Maxdate - LY] 
			return  CALCULATE([ממוצע מכירה לעסקה],FILTER(ALL(dimDates),dimDates[Date]>= minDate &&dimDates[Date]<=MaxDate))
			```
		formatString: #,0
		lineageTag: f2dbb12b-ed60-4c64-a002-29749bbecf96

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Days From Last Buy' =
			DATEDIFF([Last Buy_Calc],TODAY(),DAY)
			//IF(HASONEVALUE(dimCustomers[AccountKey]), DATEDIFF([Last Buy_Calc],TODAY(),DAY),BLANK())
		formatString: #,0
		lineageTag: 635b018b-7af0-4793-81e5-96c7cff4bae3

		changedProperty = IsHidden

	measure 'Last Buy_Calc' = CALCULATE(MAX('factOrders'[Date]),ALL(dimDates))
		formatString: dd/mm/yyyy
		lineageTag: 39aa00ff-f2e9-4ec6-9d92-b9331561c748

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Last Buy' = IF(HASONEVALUE(dimCustomers[שם לקוח]), CALCULATE(MAX('factOrders'[Date])),"")//FORMAT(CALCULATE(MAX(factSales[Date]),ALL(dimDates)),"dd/mm/yyyy")
		lineageTag: 31cf9ae1-9fd7-4e89-b9f5-1af2aaf517fd

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Unit Price' =
			
			DIVIDE([Total Sales Flat + FlatValue Switch],[Total Quantity])
			--DIVIDE([Total Sales Flat + FlatValue Switch],[Total Quantity])
			--DIVIDE([Total Sales],[Total Quantity])
		lineageTag: 696e7fcc-b5bc-4408-9efc-bac455f743b1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Top Catgory From Sales' =
			
			CALCULATE([Total Sales],TREATAS(VALUES(dimCustomers[קטגוריה מועדפת]),
			dimItems[קטגוריה]))
			
			//CALCULATE([Total Sales],dimCustomers[Top Category])
		formatString: 0
		lineageTag: 862ff712-5bb7-4d1a-807b-d73e1d344812

		changedProperty = IsHidden

	measure '% Top Catgory From Sales' = DIVIDE([Top Catgory From Sales],[Total Sales])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: dac8e2d2-b420-4a68-8eb8-7c8add3c248f

		changedProperty = IsHidden

	measure 'Last Date Sale From Top Catgory' =
			
			CALCULATE(MAX('factOrders'[Date]),TREATAS(VALUES(dimCustomers[קטגוריה מועדפת]),
			dimItems[קטגוריה]))
			
			//CALCULATE([Total Sales],dimCustomers[Top Category])
		formatString: Short Date
		lineageTag: aee9fd07-260a-4458-a2a6-052b1e8b6767

		changedProperty = IsHidden

	measure '% Avg Change All agents' = CALCULATE([% Change Sales LY Comparison],ALL(dimCustomers))
		formatString: 0%;-0%;0%
		lineageTag: a6e6812d-f279-4643-87f0-08500f3bda53

		changedProperty = IsHidden

	measure 'Customer Category with Sales' = ```
			
			 SUMX(VALUES(dimCustomers[AccountKey]),CALCULATE(IF(HASONEVALUE(dimCustomers[AccountKey]),CALCULATE([Total Sales],FILTER(ALL(dimCustomers),dimCustomers[קטגוריית לקוח]=VALUES(dimCustomers[קטגוריית לקוח]))),BLANK())))
			
			 /* Version without sumx
			IF(HASONEVALUE(dimCustomers[AccountKey]),CALCULATE([Total Sales],FILTER(ALL(dimCustomers),dimCustomers[קטגוריית לקוח]=VALUES(dimCustomers[קטגוריית לקוח]))),BLANK())
			*/
			
			
			```
		lineageTag: 96ecfc77-46b4-44ca-b4a8-2f15e25af6ed

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Client Quantity Sales' = DIVIDE([Total Quantity],[Customers Quant])
		formatString: #,0.0
		lineageTag: f8d6bc31-96c3-4636-92ee-aa6842fff860

		changedProperty = IsHidden

	measure 'ממוצע כמות מכירה ליום' =
			DIVIDE([כמות מכירה],
				[כמות ימים עם מכירה])
		lineageTag: d2d8446b-9758-4a3b-a932-cf66ed20ee87

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ממוצע כמות מכירה ליום שנתי' =
			
			/*
			VAR ThisMonth=CALCULATE(MAX(dimDates[YearMonthSum]),dimDates[IsHistory]=1)
			return
			 CALCULATE([ממוצע מכירות ליום],FILTER(dimDates,dimDates[YearMonthSum]=ThisMonth))*/
			 CALCULATE(CALCULATE([ממוצע כמות מכירה ליום],DATESYTD(dimDates[Date])),dimDates[IsHistory]=1)
		lineageTag: 341eeca2-e9e0-44af-9c7a-6125459bf4c0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Unit Price By Supply Date _ DailyPrice' =
			
			VAR DailyDate = CALCULATE(MAX(Sub_DimDates[Date]),Sub_DimDates[IsHistory]=1)--CALCULATE(LASTDATE(factDailyPrices[AsOfDate]),ALL(factDailyPrices))
			Var _MaxDate = MAX(dimDates[Date])
			
			
			RETURN
			Switch(TRUE(),
			    _MaxDate<>BLANK(),
			                CALCULATE([Avg Unit Price]
			                  ,FILTER(ALLSELECTED(factOrders[תאריך אספקה],factOrders[Date])
			                           ,factOrders[תאריך אספקה]>=DailyDate && factOrders[Date]=DailyDate
			                         )
			                  ,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			                  ),
			BLANK())
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e4c1049f-e4bc-4e78-9ac4-33f13229e1c4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Unit Price By Supply Date' =
			
			CALCULATE([Avg Unit Price],USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה]))
			--CALCULATE(DIVIDE([Total Sales],[Total Quantity]),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])))
		lineageTag: 6bf79886-f191-415e-a748-61579935b8dd

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cumulative Open Orders' = CALCULATE([Open Orders Quantity By Supply Date],FILTER(All(DimDates),DimDates[Date]<=MAX(DimDates[Date]) && dimDates[IsHistory]=0))
		lineageTag: 30ef7d90-e27a-4a1b-bcdd-0ece3ad10d46

		changedProperty = IsHidden

	measure 'Open Orders Quantity By Supply Date' =
			
			
			CALCULATE([Open Orders Quantity]
			,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			)
		lineageTag: 8bba415c-6b2c-4b98-af34-2366171df597

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Open Orders Quantity' = ```
			CALCULATE([Total Quantity],factOrders[סטטוס]=1) +  [Total Quantity Left]--סטטוס 1 = הזמנה פתחוחה ---- Total Quantity Left = הזמנות שסופקו חלקית 
			```
		lineageTag: d9234b08-091e-4695-895c-91731f0fa3c7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'הזמנות פתוחות לפי תאריך אספקה' = [Open Orders Quantity By Supply Date]
		lineageTag: f908c7e8-5354-4cd0-9b0e-381f61bb964b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Orders Count' = DISTINCTCOUNT(factOrders[OrderID])
		formatString: 0
		lineageTag: 2250cc32-59f9-4ce8-a9dd-af4f042e20a1

		changedProperty = IsHidden

	measure 'All Open Orders Quantity By Supply Date' =
			
			--VAR _MaxDate = MAX(dimDates[תאריך])
			VAR _MaxDate = CALCULATE(MAX(factOrders[תאריך אספקה]),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה]))
			RETURN
			CALCULATE(
			    [Open Orders Quantity By Supply Date]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			)
		lineageTag: e93dc4e5-88ba-4e86-b4af-e10c11c6d905

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Stock calculated' = ```
			
			VAR LastUpdated=CALCULATE(MAX(factInventory[Date]),ALL(factInventory))
			var StockCurrentMonth = CALCULATE(CALCULATE(SUM(factInventory[Quantity]),factInventory[Date]=LastUpdated),ALL(dimDates))
			var AllOpenPrevMonth = CALCULATE([All Open Orders By Supply Date - Risk Plan],DATEADD(dimDates[Date],-1,MONTH))
			VAR AllOpenPurchasePrevMonth = CALCULATE([All Open Purchase By Supply Date - Risk Plan],DATEADD(dimDates[Date],-1,MONTH))
			
			return 
			StockCurrentMonth+AllOpenPurchasePrevMonth-AllOpenPrevMonth
			```
		formatString: " #,#.##;(#,#.##)"
		displayFolder: Risk Plan
		lineageTag: edcdfdc5-20dc-41bf-a40a-4242ca013d49

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Remain - Risk Plan' = ```
			
			VAR LastUpdated=CALCULATE(MAX(factInventory[Date]),ALL(factInventory))
			var StockCurrentMonth = CALCULATE(CALCULATE(SUM(factInventory[Quantity]),factInventory[Date]=LastUpdated),ALL(dimDates))
			
			return 
			StockCurrentMonth + [All Open Purchase By Supply Date - Risk Plan] - [All Open Orders By Supply Date - Risk Plan]
			
			```
		formatString: " #,#.##;(#,#.##)"
		displayFolder: Risk Plan
		lineageTag: 5de6f3ff-67e9-4461-bb10-7712c6f2b2a4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Stock - Risk Plan' = IF(MAX(dimDates[Show Months])="This Month",[Inventory Balance - Quantity],[Stock calculated])
		formatString: " #,#.##;(#,#.##)"
		displayFolder: Risk Plan
		lineageTag: 4e12d039-ae49-4df0-bc50-708f7c6bffa1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Sales - Risk Plan' = ```
			
			VAR _MaxDate = CALCULATE(MAX(factOrders[תאריך אספקה]),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה]))
			VAR MinDate = MIN(dimDates[Date])
			VAR _ALLMinDate = CALCULATE(MIN(dimDates[Date]),ALL(dimDates))
			var allOpenChosenMonth = 
			CALCULATE(
			    [Open Orders Quantity By Supply Date]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate && dimDates[Date]>=MinDate)
			)
			VAR _OLDOpenOrders = 
			CALCULATE(
			    [Open Orders Quantity By Supply Date]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate && dimDates[Date]>=_ALLMinDate)
			)
			return 
			IF(MAX(dimDates[Show Months])="This Month",_OLDOpenOrders,allOpenChosenMonth)
			
			```
		formatString: #,0
		displayFolder: Risk Plan
		lineageTag: 60c578f5-b59d-4f4a-aa64-7678bb0a7e5e

		changedProperty = IsHidden

	measure 'Switch Measures Show' =
			
			IF(HASONEVALUE(dimItemsSimple[Article_Description]),
			    SWITCH(MAX(SwitchMeasure[ID]),
			    1,[Stock - Risk Plan],
			    2,[Purchase - Risk Plan],
			    3,[Sales - Risk Plan],
			    4,[Remain - Risk Plan],
			    BLANK())
			,
			    SWITCH(MAX(SwitchMeasure[ID]),
			    1,CALCULATE([Stock - Risk Plan],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    2,CALCULATE([Purchase - Risk Plan],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    3,CALCULATE([Sales - Risk Plan],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    4,CALCULATE([Remain - Risk Plan],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    BLANK()))
		formatString: " #,#.##;(#,#.##)"
		lineageTag: 4137cf2f-1515-4d13-8c90-39720c9509b5

		changedProperty = IsHidden

	measure 'All Open Orders By Supply Date - Risk Plan' = ```
			
			VAR _MaxDate = MAX(dimDates[Date])
			VAR MinDate = MIN(dimDates[Date])
			VAR _ALLMinDate = CALCULATE(MIN(dimDates[Date]),ALL(dimDates))
			return
			CALCULATE(
			    [Open Orders Quantity By Supply Date]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			)
			
			```
		displayFolder: Risk Plan
		lineageTag: 285e4fef-c82b-41c2-a946-95aa92d3dff8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Sales USD NIS Switch' = ```
			
			 SWITCH(MAX(OrderVSExecutionVSSupply[ID]),
			    1,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, [Total Sales NIS],
			        2, [Total Sales USD],
			        3, [Total Quantity])
			    ,2,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, [Total Sales NIS Supply TO DATE],
			        2, [Total Sales USD Supply TO DATE],
			        3, [Total Quantity Supply TO DATE])
			    ,3,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, [Total Sales NIS (Sales)],
			        2, [Total Sales USD (Sales)],
			        3, [Total Quantity (Sales)])
			 )+0
			```
		displayFolder: Dynamic Switch Graph Measures
		lineageTag: 2efbc142-7319-4d07-b77f-688b37ab20a2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Sales USD NIS LY Switch' = ```
			
			 SWITCH(MAX(OrderVSExecutionVSSupply[ID]),
			    1,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE([Total Sales NIS],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),
			        2, CALCULATE([Total Sales USD],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),
			        3, CALCULATE([Total Quantity],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)))
			    ,2,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE(CALCULATE([Total Sales NIS Supply TO DATE],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1),
			        2, CALCULATE(CALCULATE([Total Sales USD Supply TO DATE],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1), 
			        3, [Quantity Dynamic Switch LY FYvsYTD])
			    ,3,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE([Total Sales NIS (Sales)],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),
			        2, CALCULATE([Total Sales USD (Sales)],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),
			        3, CALCULATE([Total Quantity (Sales)],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)))
			 )+0
			```
		displayFolder: Dynamic Switch Graph Measures
		lineageTag: 9f2398c9-73aa-4413-b8d3-ed4b4c908b5a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Diff Quantity From LY' = [Quantity YTD] - [Quantity LY YTD]
		formatString: #,0.00
		lineageTag: 4b59e8aa-4f10-47ec-b173-ef3334d4c21c

		changedProperty = IsHidden

	measure 'Total Quantity Supply Date_DailyPrice' =
			
			VAR DailyDate = CALCULATE(MAX(Sub_DimDates[Date]),Sub_DimDates[IsHistory]=1)--CALCULATE(LASTDATE(factDailyPrices[AsOfDate]),ALL(factDailyPrices))
			Var _MaxDate = MAX(dimDates[Date])
			
			
			RETURN
			Switch(TRUE(),
			    _MaxDate<>BLANK(),
			                CALCULATE([Total Quantity]
			                  ,FILTER(ALLSELECTED(factOrders[תאריך אספקה],factOrders[Date])
			                           ,factOrders[תאריך אספקה]>=DailyDate && factOrders[Date]=DailyDate
			                         )
			                  ,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			                  ),
			BLANK())
		lineageTag: b0f85fac-baf4-4a0c-9608-cd77fc42c43f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Supply Date DynamicTable' = ```
			
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[Date])),dimDates[IsHistory]=1)
			VAR _todate = CALCULATE(MAX(dimDates[Date]),FILTER(ALL(dimDates),dimDates[IsHistory]=1))
			VAR _Maxdate = MAX(dimDates[Date])
			VAR _SubMaxdate = MAX(Sub_DimDates[Date])
			VAR _date = IF(_Maxdate<=_SubMaxdate,_Maxdate,_SubMaxdate)
			
			
			RETURN
			CALCULATE(CALCULATE([Total Quantity]
			                  ,FILTER(dimDates,dimDates[Date]<=_date)
			                  ,Sub_DimDates[Year]=_YEAR
			                  ,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			                  )
			        ,dimDates[IsHistory]=1)
			--CALCULATE([Total Quantity],USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]),USERELATIONSHIP(DimDates[Date],factOrders[תאריך אספקה]))--,Sub_DimDates[Year]=_Year)
			
			```
		formatString: #,0.00
		displayFolder: Dynamic Table
		lineageTag: 24c9cd35-58d2-4913-b0d1-93c1a3fb25c7

		changedProperty = IsHidden

	measure 'Quantity Orders DynamicTable' =
			
			// VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[Date])),dimDates[IsHistory]=1)
			VAR _YEAR = CALCULATE(YEAR(MAX(Sub_DimDates[Date])),Sub_DimDates[IsHistory]=1)
			RETURN
			CALCULATE([Total Quantity],Sub_DimDates[Year]=_Year)
		displayFolder: Dynamic Table
		lineageTag: 778ad16d-bc5e-431c-bae4-b518eff6937d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Execution DynamicTable' =
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[Date])),dimDates[IsHistory]=1)
			
			
			RETURN
			CALCULATE([Total Quantity (Sales) By Delivery Date],Sub_DimDates[Year]=_Year)
			--CALCULATE([Total Quantity (Sales)],Sub_DimDates[Year]=_Year)
		formatString: #,0.00
		displayFolder: Dynamic Table
		lineageTag: b38dc056-84f2-40d2-af38-0654fb13c287

		changedProperty = IsHidden

	measure 'Quantity Months Table Switch' = ```
			
			VAR _MinDate= MIN(Sub_DimDates[Date])
			VAR _CheckBlank = CALCULATE([Total Quantity Supply TO DATE],ALL(dimItemsSimple),Filter(ALL(Sub_DimDates),Sub_DimDates[Date]>=_MinDate))
			VAR _todate = CALCULATE(MAX(dimDates[Date]),FILTER(ALL(dimDates),dimDates[IsHistory]=1))
			VAR _Maxdate = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			VAR _SubMaxdate = MAX(Sub_DimDates[Date])
			VAR _date = IF(_Maxdate<=_SubMaxdate,_Maxdate,_SubMaxdate)
			VAR _Orders = CALCULATE([Quantity Orders DynamicTable],FILTER(dimDates,dimDates[Date]<=_date))
			
			
			Var _Supply =
			CALCULATE(CALCULATE([Total Quantity]
			                  ,FILTER(dimDates,dimDates[Date]<=_date)
			                  ,Sub_DimDates[MonthToShow]=1
			                  ,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			                  )
			        ,dimDates[IsHistory]=1)
			VAR _Execute = CALCULATE([Quantity Execution DynamicTable],FILTER(dimDates,dimDates[Date]<=_date)) --[Quantity Execution DynamicTable]
			VAR _Measure = 
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,IF(ISBLANK(_Orders),"-",_Orders),
			2,IF(ISBLANK(_Supply),"-",_Supply),
			3,IF(ISBLANK(_Execute),"-",_Execute),
			IF(ISBLANK(_Orders),"-",_Orders)
			)
			
			
			Return
			IF(ISBLANK(_CheckBlank),BLANK(),_Measure)
			
			```
		formatString: #,0.00
		displayFolder: Dynamic Table
		lineageTag: 361d001c-1baf-47c0-ae88-1d1a7921d083

		changedProperty = IsHidden

	measure DynamicFilter =
			
			IF([Quantity Dynamic Table Switch Filter]=0 && [Quantity Dynamic Table Switch LY Filter]=0 && (ISBLANK([DynamicTable Potential]) || [DynamicTable Potential] = 0),0,1)
		displayFolder: Dynamic Table
		lineageTag: 27c86e67-e1b9-4265-838b-d549526d1c78

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch LY' =
			
			VAR _Blank = IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),"-",0)
			
			VAR _Calc =
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,IF(ISBLANK([Quantity Orders DynamicTable LY]),0,[Quantity Orders DynamicTable LY]),
			2,IF(ISBLANK([Quantity Supply DynamicTable LY]),0,[Quantity Supply DynamicTable LY]),
			3,IF(ISBLANK([Quantity Execution DynamicTable LY]),0,[Quantity Execution DynamicTable LY]),
			IF(ISBLANK([Quantity Orders DynamicTable LY]),0,[Quantity Orders DynamicTable LY]))
			
			RETURN
			--SWITCH(TRUE(),
			--ISBLANK([Quantity Dynamic Table Switch]) && MAX(Sub_DimDates[IsHistory])=0,BLANK(),
			_Calc
			--)
		displayFolder: Dynamic Table
		lineageTag: e631eb58-1623-47ff-8cc3-3ec55649e5c2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Orders DynamicTable LY' =
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-1
			RETURN
			--CALCULATE([Total Quantity],Sub_DimDates[Year]=_YEAR)--,DATEADD(dimDates[Date],-1,YEAR),DATEADD(Sub_DimDates[Date],-1,YEAR))
			CALCULATE([Total Quantity],
			            Sub_DimDates[Year]=_YEAR,
			            DATEADD(Sub_DimDates[Date],-1,YEAR)
			            ,DATEADD(DimDates[Date],-1,YEAR)
			            )
			/*
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[LastYear])),dimDates[IsHistory]=1)
			VAR _Month = Month(MAX(Sub_DimDates[Date]))
			
			RETURN
			SWITCH(TRUE(),
			HASONEVALUE(Sub_DimDates[MonthInCalendarName]) || HASONEVALUE(Sub_DimDates[ShortMonthName]),
			CALCULATE([Total Quantity],REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factOrders[Date]),Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR && Sub_DimDates[MonthNumberOfYear] =_Month)),
			CALCULATE([Total Quantity],REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factOrders[Date]),Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR))
			--,DATEADD(Sub_DimDates[Date],-1,YEAR),Sub_DimDates[Year]=_YEAR,Sub_DimDates[IsHistory]=1)
			)*/
		formatString: 0
		displayFolder: Dynamic Table
		lineageTag: 82e5645f-c4eb-4222-b323-66eed99845b0

		changedProperty = IsHidden

	measure 'Quantity Execution DynamicTable LY' =
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-1
			RETURN
			CALCULATE([Total Quantity (Sales) By Delivery Date],Sub_DimDates[Year]=_YEAR)--,DATEADD(dimDates[Date],-1,YEAR),DATEADD(Sub_DimDates[Date],-1,YEAR))
			--CALCULATE([Total Quantity (Sales)],Sub_DimDates[Year]=_YEAR)--,DATEADD(dimDates[Date],-1,YEAR),DATEADD(Sub_DimDates[Date],-1,YEAR))
			/*
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[LastYear])),dimDates[IsHistory]=1)
			VAR _Month = Month(MAX(Sub_DimDates[Date]))
			
			RETURN
			SWITCH(TRUE(),
			HASONEVALUE(Sub_DimDates[MonthInCalendarName]) || HASONEVALUE(Sub_DimDates[ShortMonthName]),
			CALCULATE([Total Quantity (Sales)],REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factSales[DeliveryDate]),Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR && Sub_DimDates[MonthNumberOfYear]=_Month)),
			CALCULATE([Total Quantity (Sales)],REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factSales[DeliveryDate]),Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR))
			)*/
		displayFolder: Dynamic Table
		lineageTag: cf925d7a-e70b-4707-a233-76d4869750d4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Supply DynamicTable LY' =
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-1
			RETURN
			CALCULATE([Total Quantity Supply Date],
			            Sub_DimDates[Year]=_YEAR,
			            DATEADD(Sub_DimDates[Date],-1,YEAR)
			            ,DATEADD(DimDates[Date],-1,YEAR)
			            )
			/*
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[LastYear])),dimDates[IsHistory]=1)
			VAR _Month = Month(MAX(Sub_DimDates[Date]))
			
			RETURN
			SWITCH(TRUE(),
			HASONEVALUE(Sub_DimDates[MonthInCalendarName]) || HASONEVALUE(Sub_DimDates[ShortMonthName]),
			CALCULATE([Total Quantity],USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]),REMOVEFILTERS(dimDates)
			,Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR && Sub_DimDates[MonthNumberOfYear]=_Month)),
			CALCULATE([Total Quantity],USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]),REMOVEFILTERS(dimDates)
			--,DATEADD(Sub_DimDates[Date],-1,YEAR),Sub_DimDates[Year]=_YEAR,Sub_DimDates[IsHistory]=1)
			,Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR))
			)
			*/
		displayFolder: Dynamic Table
		lineageTag: 6d776be4-fa38-4a53-94c5-c4b576654348

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Quantity Supply Date' =
			CALCULATE([Total Quantity]
			                  ,ALLSELECTED(factOrders[תאריך אספקה],factOrders[Date])
			                  ,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			                  ,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			                )
		lineageTag: eb5d6ec8-6656-476f-8940-2cd4a61cc446

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales USD Supply Date' =
			CALCULATE([Total Sales USD]
			                  ,ALLSELECTED(factOrders[תאריך אספקה],factOrders[Date])
			                  ,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			                  ,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			                )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 189291d3-975b-438a-be02-a0218907c996

		changedProperty = IsHidden

	measure 'Total Sales NIS Supply Date' =
			CALCULATE([Total Sales NIS]
			                  ,ALLSELECTED(factOrders[תאריך אספקה],factOrders[Date])
			                  ,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			                  ,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			                )
		lineageTag: d223b0dc-50cd-455a-b54f-c6b3d0ed3f75

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DynamicTable Potential' = ```
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[Date])),dimDates[IsHistory]=1)
			
			
			RETURN
			
			CALCULATE([Potential],REMOVEFILTERS(dimDates),Sub_DimDates[Year]=_YEAR)
			
			```
		lineageTag: 8c88ac34-550a-40a3-93f1-dcb6023b2cbd

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Price - Risk Plan' =
			
			ROUND(
			    SWITCH(TRUE(),
			    ISBLANK([Sales - Risk Plan]) && [Purchase - Risk Plan] <> BLANK(),
			        [Avg Cost Price Supply Date],
			    ISBLANK([Sales - Risk Plan]) && ISBLANK([Purchase - Risk Plan]),
			        BLANK(),
			        [Avg Unit Price By Supply Date]
			    )
			,0)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Risk Plan
		lineageTag: 7efccd97-dc78-4ca5-82ed-349d612a6db2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure _blank = BLANK()
		formatString: 0
		lineageTag: eb23ce31-565b-483d-ba19-c757d5204373

		changedProperty = IsHidden

	measure 'Price Diff - Risk Plan' =
			
			Switch(TRUE(),
			[Balance - Risk Plan]>0,
			    [Market Price] - [AVG Price - Risk Plan],
			[Balance - Risk Plan]<0,
			    [AVG Price - Risk Plan] - [Market Price],
			BLANK()
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Risk Plan
		lineageTag: c0e6bbde-6133-4a77-a096-487a22c90f37

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Risk Plan' =
			
			SWITCH(TRUE(),
			ISBLANK([AVG Price - Risk Plan]),
			    BLANK(),
			SUMX(CROSSJOIN(SUMMARIZE(dimItemsSimple,dimItemsSimple[MainItemName]),SUMMARIZE(dimDates,dimDates[MonthInCalendarName])),
			ABS([Balance - Risk Plan])
			*
			[Price Diff - Risk Plan])
			)
		displayFolder: Risk Plan
		lineageTag: dbf09f3c-bd1b-4362-aa9a-a5f36c660b4a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Price Diff - Risk Plan No Total' =
			
			SWITCH(TRUE(),
			ISBLANK([AVG Price - Risk Plan No Total]),
			    BLANK(),
			HASONEVALUE(dimDates[MonthInCalendarName]),
			    [Price Diff - Risk Plan],
			BLANK()
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Risk Plan
		lineageTag: 46c94285-84d6-4206-a0a2-635bdc21873a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'AVG Price - Risk Plan No Total' =
			
			SWITCH(TRUE(),
			HASONEVALUE(dimDates[MonthInCalendarName]),
			    [AVG Price - Risk Plan],
			BLANK()
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Risk Plan
		lineageTag: f12f3723-d037-4684-b8aa-33cf47f8232a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Balance - Risk Plan' =
			
			VAR _maxDate = MAX(Sub_DimDates[Date])
			Var _maxMonth = CALCULATE(MAX(Sub_DimDates[MonthInCalendarName]),Sub_DimDates[Date]=_maxDate)
			
			RETURN
			SWITCH(TRUE(),
			MAX(dimDates[MonthInCalendarName])=_maxMonth, [Remain - Risk Plan],
			[Purchase - Risk Plan] - [Sales - Risk Plan]
			)
		displayFolder: Risk Plan
		lineageTag: 2f52b6ae-1576-4b7a-84a5-8baaf3409b67

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Quantity Left' = ```
			CALCULATE(SUM('factOrders'[QuantityLeft]),factOrders[סטטוס]=2) 
			```
		lineageTag: 02cc1a4d-a560-4519-9b93-ae07607479a9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QQuantity Sales USD NIS 2Y Switch' = ```
			
			 SWITCH(MAX(OrderVSExecutionVSSupply[ID]),
			    1,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE([Total Sales NIS],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),
			        2, CALCULATE([Total Sales USD],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),
			        3, CALCULATE([Total Quantity],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)))
			    ,2,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE(CALCULATE([Total Sales NIS Supply TO DATE],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),dimDates[IsHistory]=1),
			        2, CALCULATE(CALCULATE([Total Sales USD Supply TO DATE],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),dimDates[IsHistory]=1),
			        3, [Quantity Dynamic Table Switch 2LY FYvsYTD])
			    ,3,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE([Total Sales NIS (Sales)],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),
			        2, CALCULATE([Total Sales USD (Sales)],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),
			        3, CALCULATE([Total Quantity (Sales)],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)))
			 )+0
			```
		displayFolder: Dynamic Switch Graph Measures
		lineageTag: 5bbe7ed7-bacd-413d-90a4-9df8c667bca3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lazy Customer - Supply Date Last Year' =
			
			VAR MonthParameter = SELECTEDVALUE(LazyCustomerSupplyLastYearMonths[LazyCustomerSupplyLastYearMonths])
			VAR _year = Year(CALCULATE(MAX(dimDates[Date]),ALL(dimDates),dimDates[IsHistory]=1))
			VAR _Ly = _year - 1
			VAR _LastMonth = EOMONTH(CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1),-2)
			VAR _OpenOrders = CALCULATE([Total Quantity Supply Date],Filter(ALL(dimDates),dimDates[Date]>_LastMonth))
			VAR _QtyCheck = IF(ISBLANK(CALCULATE([Total Quantity Supply Date],FILTER(ALL(dimDates),YEAR(dimDates[Date])=_Ly))),0,1)
			VAR _LYCheckTable = CALCULATETABLE(SUMMARIZE(factOrders,dimCustomers[שם לקוח אב],dimDates[MonthInCalendarName],"QtyCheck",_QtyCheck),FILTER(dimDates,YEAR(dimDates[Date])=_Ly))
			VAR _LYSumTable=SELECTCOLUMNS(
			                FILTER(
			                    SUMMARIZE(_LYCheckTable,dimCustomers[שם לקוח אב],"Sum",SUMX(_LYCheckTable,[QtyCheck]))
			                    ,[Sum]>=MonthParameter)
			                ,dimCustomers[שם לקוח אב])
			VAR __CurrentSumTable=SELECTCOLUMNS(
			                                    FILTER(
			                                        SUMMARIZE(factOrders,dimCustomers[שם לקוח אב],"Sum",_OpenOrders)
			                                    ,_OpenOrders = BLANK())
			                                ,dimCustomers[שם לקוח אב])
			
			VAR _Count = COUNTROWS(INTERSECT(_LYSumTable,__CurrentSumTable))
			
			RETURN
			_Count
		formatString: 0
		lineageTag: 961c26b8-791f-4052-8c4b-f50391c8541a

		changedProperty = IsHidden

	measure 'Lazy Customer Check' =
			
			[Lazy Customer - Supply Date] + [Lazy Customer - Execution]
		formatString: 0
		lineageTag: f910dfe8-53cc-4c7f-ad0a-502d3367c7ff

		changedProperty = IsHidden

	measure 'Lazy Customer - Supply Date Last X Month' =
			
			VAR _MonthXParameter = SELECTEDVALUE(LazyCustomerXMonths[LazyCustomerXMonths])
			VAR _MonthYParameter = SELECTEDVALUE(LazyCustomerYMonths[LazyCustomerYMonths])
			VAR _Date = CALCULATE(MAX(dimDates[Date]),ALL(dimDates),dimDates[IsHistory]=1)
			VAR _Ly = DATE(Year(_Date),MONTH(_Date)-_MonthYParameter,DAY(_Date))
			VAR _LastMonth = DATE(Year(_Date),MONTH(_Date),DAY(_Date)-60)
			VAR _OpenOrders = CALCULATE([Total Quantity Supply Date],Filter(ALL(dimDates),dimDates[Date]>_LastMonth))
			VAR _QtyCheck = IF(ISBLANK(CALCULATE([Total Quantity Supply Date],FILTER(ALL(dimDates),dimDates[Date]>_Ly &&dimDates[Date]<=_LastMonth))),0,1)
			VAR _LYCheckTable = CALCULATETABLE(SUMMARIZE(factOrders,dimCustomers[שם לקוח אב],dimDates[MonthInCalendarName],"QtyCheck",_QtyCheck),FILTER(dimDates,dimDates[Date]>_Ly &&dimDates[Date]<=_LastMonth))
			VAR _LYSumTable=SELECTCOLUMNS(
			                FILTER(
			                    SUMMARIZE(_LYCheckTable,dimCustomers[שם לקוח אב],"Sum",SUMX(_LYCheckTable,[QtyCheck]))
			                    ,[Sum]>=_MonthXParameter)
			                ,dimCustomers[שם לקוח אב])
			VAR __CurrentSumTable=SELECTCOLUMNS(
			                                    FILTER(
			                                        SUMMARIZE(factOrders,dimCustomers[שם לקוח אב],"Sum",_OpenOrders)
			                                    ,_OpenOrders = BLANK())
			                                ,dimCustomers[שם לקוח אב])
			
			VAR _Count = COUNTROWS(INTERSECT(_LYSumTable,__CurrentSumTable))
			
			RETURN
			_Count
		formatString: 0
		lineageTag: b2ce2916-755e-43b9-ae64-6f8f2009a230

		changedProperty = IsHidden

	measure 'Total Quantity Supply TO DATE' =
			
			VAR _Maxdate = MAX(dimDates[Date])
			VAR _SubMaxdate = MAX(Sub_DimDates[Date])
			VAR _date = IF(_Maxdate<=_SubMaxdate,_Maxdate,_SubMaxdate)
			
			
			RETURN
			
			CALCULATE([Total Quantity]
			                  ,FILTER(dimDates,dimDates[Date]<=_date)
			                  ,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]) ,dimDates[IsHistory]=1
			)
		lineageTag: 346d06f1-ee91-46f9-ad35-d91009750373

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales NIS Supply TO DATE' = ```
			
			VAR _todate = CALCULATE(MAX(dimDates[Date]),FILTER(ALL(dimDates),dimDates[IsHistory]=1))
			VAR _Maxdate = MAX(dimDates[Date])
			VAR _SubMaxdate = MAX(Sub_DimDates[Date])
			VAR _date = IF(_Maxdate<=_SubMaxdate,_Maxdate,_SubMaxdate)
			
			
			RETURN
			CALCULATE(CALCULATE([Total Sales NIS]
			                  ,FILTER(dimDates,dimDates[Date]<=_date)
			                  ,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			                  )
			        ,dimDates[IsHistory]=1)
			
			
			```
		lineageTag: c961cb00-81ca-4dec-bbe0-388f62b5dff3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales USD Supply TO DATE' =
			
			VAR _todate = CALCULATE(MAX(dimDates[Date]),FILTER(ALL(dimDates),dimDates[IsHistory]=1))
			VAR _Maxdate = MAX(dimDates[Date])
			VAR _SubMaxdate = MAX(Sub_DimDates[Date])
			VAR _date = IF(_Maxdate<=_SubMaxdate,_Maxdate,_SubMaxdate)
			
			
			RETURN
			CALCULATE(CALCULATE([Total Sales USD]
			                  ,FILTER(dimDates,dimDates[Date]<=_date)
			                  ,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			                  )
			        ,dimDates[IsHistory]=1)
		lineageTag: 258e0688-5946-4f64-b569-30ca70c5edd1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Sales USD NIS Switch CurrentYear' =
			
			VAR _year = YEAR(CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1))
			
			RETURN
			 SWITCH(MAX(OrderVSExecutionVSSupply[ID]),
			    1,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE([Total Sales NIS],Filter(dimDates,YEAR(dimDates[Date])=_year)),
			        2, CALCULATE([Total Sales USD],Filter(dimDates,YEAR(dimDates[Date])=_year)),
			        3, CALCULATE([Total Quantity],Filter(dimDates,YEAR(dimDates[Date])=_year)))
			    ,2,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE([Total Sales NIS Supply Date],Filter(dimDates,YEAR(dimDates[Date])=_year)),
			        2, CALCULATE([Total Sales USD Supply Date],Filter(dimDates,YEAR(dimDates[Date])=_year)),
			        3, CALCULATE([Total Quantity Supply Date],Filter(dimDates,YEAR(dimDates[Date])=_year)))
			    ,3,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE([Total Sales NIS (Sales)],Filter(dimDates,YEAR(dimDates[Date])=_year)),
			        2, CALCULATE([Total Sales USD (Sales)],Filter(dimDates,YEAR(dimDates[Date])=_year)),
			        3, CALCULATE([Total Quantity (Sales)],Filter(dimDates,YEAR(dimDates[Date])=_year)))
			 )
		lineageTag: fa2230bc-2246-49de-a53b-285bd006f532

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Price Date Switch' = ```
			
			Var _today = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			Var _thisMonth = EOMONTH(_today,0)
			VAR _ThisWeek = CALCULATE(MAX(dimDates[WeekEnding]),dimDates[IsHistory]=1)
			Var _Daily = EOMONTH(_today,-2)
			VAR _Weekly = EOMONTH(_today,-7)
			VAR _Monthly = EOMONTH(_today,-9)
			VAR _WeeklyFull = CALCULATE(MAX(dimDates[WeekStart]),FILTER(dimDates,dimDates[Date]=_Weekly))
			RETURN
			
			SWITCH(SELECTEDVALUE('Time Selection'[Time Selection Order]),
			0,SWITCH(SELECTEDVALUE(OrderVSExecutionVSSupply[ID]),
			    1,CALCULATE([Avg Unit Price],FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Daily)),
			     2,CALCULATE([Avg Unit Price By Supply Date],USERELATIONSHIP(Sub_dimDates[Date],factOrders[תאריך אספקה]),FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Daily))
			    ),
			1,SWITCH(SELECTEDVALUE(OrderVSExecutionVSSupply[ID]),
			    1,CALCULATE([Avg Unit Price],FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>=_WeeklyFull)),
			     2,CALCULATE([Avg Unit Price By Supply Date],USERELATIONSHIP(Sub_dimDates[Date],factOrders[תאריך אספקה]),FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>=_WeeklyFull))
			    ),
			2,SWITCH(SELECTEDVALUE(OrderVSExecutionVSSupply[ID]),
			    1,CALCULATE([Avg Unit Price],FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Monthly)),
			    2,CALCULATE([Avg Unit Price By Supply Date],USERELATIONSHIP(Sub_dimDates[Date],factOrders[תאריך אספקה]),FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Monthly))
			    )
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f7857521-36ba-4ab8-8f1f-a92fd1a235d6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Date Switch' = ```
			
			Var _today = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			Var _thisMonth = EOMONTH(_today,0)
			VAR _ThisWeek = CALCULATE(MAX(dimDates[WeekEnding]),dimDates[IsHistory]=1)
			Var _Daily = EOMONTH(_today,-2)
			VAR _Weekly = EOMONTH(_today,-7)
			VAR _Monthly = EOMONTH(_today,-9)
			VAR _WeeklyFull = CALCULATE(MAX(dimDates[WeekStart]),FILTER(dimDates,dimDates[Date]=_Weekly))
			RETURN
			
			SWITCH(SELECTEDVALUE('Time Selection'[Time Selection Order]),
			0,IF(MAX(Sub_dimDates[Date])<=_today && MIN(Sub_dimDates[Date])>_Daily,
			    SWITCH(SELECTEDVALUE(OrderVSExecutionVSSupply[ID]),
			        1,CALCULATE([Total Quantity]+0,FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Daily)),
			        2,CALCULATE([Total Quantity Supply Date]+0,USERELATIONSHIP(Sub_dimDates[Date],factOrders[תאריך אספקה]),FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Daily)),BLANK()
			        )
			    ),
			1,IF(MAX(Sub_dimDates[Date])<=_thisMonth && MIN(Sub_dimDates[Date])>_WeeklyFull,
			    SWITCH(SELECTEDVALUE(OrderVSExecutionVSSupply[ID]),
			        1,CALCULATE([Total Quantity]+0,FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_WeeklyFull)),
			        2,CALCULATE([Total Quantity Supply Date]+0,USERELATIONSHIP(Sub_dimDates[Date],factOrders[תאריך אספקה]),FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_WeeklyFull)),BLANK()
			        )
			    ),
			2,IF(MAX(Sub_dimDates[Date])<=_thisMonth && MIN(Sub_dimDates[Date])>_Monthly,
			    SWITCH(SELECTEDVALUE(OrderVSExecutionVSSupply[ID]),
			        1,CALCULATE([Total Quantity]+0,FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Monthly)),
			        2,CALCULATE([Total Quantity Supply Date]+0,USERELATIONSHIP(Sub_dimDates[Date],factOrders[תאריך אספקה]),FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Monthly)),BLANK()
			        )
			    )
			)
			
			```
		lineageTag: d771bb03-846e-462d-9e9c-faee5aa30960

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD OR MTD %' = IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch % MTD],[Switch % YTD])
		formatString: 0.00%;(0.00)%;0.00%
		lineageTag: 1124141e-49c4-4b32-9eee-3a8e9255aad6

		changedProperty = IsHidden

	measure 'YTD OR MTD LY' =
			
			IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch LY MTD],[Switch LY YTD])
		lineageTag: 9ed84cf8-3b4e-4ff2-ba2b-1f7dbec5fec6

		formatStringDefinition =
				SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
				3,SWITCH(TRUE(),
				        ABS(IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch LY MTD],[Switch LY YTD]))<1000,",#,0",
				        ABS(IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch LY MTD],[Switch LY YTD]))<1000000,",#,0.0",
				        ",#,0.00"),
				2,SWITCH(TRUE(),
				        ABS(IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch LY MTD],[Switch LY YTD]))<1000,"$  ,#,0",
				        ABS(IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch LY MTD],[Switch LY YTD]))<1000000,"$  ,#,0.0",
				        "$ ,#,0.00"),
				1,SWITCH(TRUE(),
				        ABS(IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch LY MTD],[Switch LY YTD]))<1000,"₪ ,#,0",
				        ABS(IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch LY MTD],[Switch LY YTD]))<1000000,"₪ ,#,0.0",
				        "₪ ,#,0.00")
				)

		changedProperty = IsHidden

	measure 'Switch % YTD' =
			
			SWITCH(SELECTEDVALUE(VAT_MeasureSelctionTable[ID ANALYSIS]),
			1, [% change YTD Sales LY Comparsion],
			2, [% change YTD Sales LY Comparsion],
			3, [% change YTD Quantity LY Comparsion]
			)
		formatString: 0.00%;(0.00)%;0.00%
		lineageTag: 73fad28d-8c51-42cc-84b4-41464b0368cc

		changedProperty = IsHidden

	measure 'Switch % MTD' =
			
			SWITCH(SELECTEDVALUE(VAT_MeasureSelctionTable[ID ANALYSIS]),
			1, [% Change Sales LY MTD Comparison],
			2, [% Change Sales LY MTD Comparison],
			3, [% Change Quantity LY MTD Comparison]
			)
		formatString: 0.00%;(0.00)%;0.00%
		lineageTag: aae88bab-ce4e-4cfa-86d0-0e39b43af435

		changedProperty = IsHidden

	measure 'Switch LY MTD' =
			
			SWITCH(SELECTEDVALUE(VAT_MeasureSelctionTable[ID ANALYSIS]),
			1, [Sales Comparison LY MTD],
			2, [Sales Comparison LY MTD],
			3, [Quantity Comparison LY MTD]
			)
		lineageTag: 32d51540-8d33-4b6a-9983-aa4e1a7938a3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch LY YTD' =
			
			SWITCH(SELECTEDVALUE(VAT_MeasureSelctionTable[ID ANALYSIS]),
			1, [Sales LY YTD],
			2, [Sales LY YTD],
			3, [Quantity LY YTD]
			)
		lineageTag: 90ab196a-98a4-4b6b-98e7-92e37c978806

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch MTD' =
			
			SWITCH(SELECTEDVALUE(VAT_MeasureSelctionTable[ID ANALYSIS]),
			1, [Sales MTD],
			2, [Sales MTD],
			3, [Quantity MTD]
			)
		lineageTag: d85d5951-dd83-40d0-a69c-8deb65719219

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch YTD' =
			
			SWITCH(SELECTEDVALUE(VAT_MeasureSelctionTable[ID ANALYSIS]),
			1, [Sales YTD],
			2, [Sales YTD],
			3, [Quantity YTD]
			)
		lineageTag: c47b2078-8e96-4607-b0c5-fc274948cfd7

		changedProperty = IsHidden

	measure 'YTD OR MTD' = IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch MTD],[Switch YTD])
		lineageTag: 0233ddc7-7025-43b4-a9af-4eca21bae367

		formatStringDefinition =
				SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
				3,SWITCH(TRUE(),
				        ABS(IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch MTD],[Switch YTD]))<1000,",#,0",
				        ABS(IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch MTD],[Switch YTD]))<1000000,",#,0.0",
				        ",#,0.00"),
				2,SWITCH(TRUE(),
				        ABS(IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch MTD],[Switch YTD]))<1000,"$  ,#,0",
				        ABS(IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch MTD],[Switch YTD]))<1000000,"$  ,#,0.0",
				        "$ ,#,0.00"),
				1,SWITCH(TRUE(),
				        ABS(IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch MTD],[Switch YTD]))<1000,"₪ ,#,0",
				        ABS(IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),[Switch MTD],[Switch YTD]))<1000000,"₪ ,#,0.0",
				        "₪ ,#,0.00")
				)

		changedProperty = IsHidden

	measure 'Lazy Customer - Supply Date' =
			
			[Lazy Customer - Supply Date Last X Month] + [Lazy Customer - Supply Date Last Year]
		formatString: 0
		lineageTag: 0e5a12e8-efea-4023-829a-6df83596995c

		changedProperty = IsHidden

	measure 'Lazy Customer - Execution Last X Month' =
			
			VAR _MonthXParameter = SELECTEDVALUE(LazyCustomerExecutionXMonths[LazyCustomerExecutionXMonths])
			VAR _MonthYParameter = SELECTEDVALUE(LazyCustomerExecutionYMonths[LazyCustomerExecutionYMonths])
			VAR _Date = CALCULATE(MAX(dimDates[Date]),ALL(dimDates),dimDates[IsHistory]=1)
			VAR _Ly = DATE(Year(_Date),MONTH(_Date)-_MonthYParameter,DAY(_Date))
			VAR _LastMonth = DATE(Year(_Date),MONTH(_Date),DAY(_Date)-60)
			VAR _OpenOrdersExecution = CALCULATE([Total Quantity (Sales)],Filter(ALL(dimDates),dimDates[Date]>_LastMonth))
			VAR _QtyExecution = CALCULATE([Total Quantity (Sales)],FILTER(ALL(dimDates),dimDates[Date]>_Ly &&dimDates[Date]<=_LastMonth))
			VAR _OpenOrders = CALCULATE([Total Quantity],Filter(ALL(dimDates),dimDates[Date]>_LastMonth))
			VAR _QtyOrders = CALCULATE([Total Quantity],FILTER(ALL(dimDates),dimDates[Date]>_Ly &&dimDates[Date]<=_LastMonth))
			VAR _QtyCheck = IF(ISBLANK(_QtyExecution) && ISBLANK(_QtyOrders),0,1)
			VAR _LYCheckTable = CALCULATETABLE(SUMMARIZE(CROSSJOIN(dimCustomers,dimDates),dimCustomers[שם לקוח אב],dimDates[MonthInCalendarName],"QtyCheck",_QtyCheck),FILTER(dimDates,dimDates[Date]>_Ly &&dimDates[Date]<=_LastMonth))
			VAR _LYSumTable=SELECTCOLUMNS(
			                FILTER(
			                    SUMMARIZE(_LYCheckTable,dimCustomers[שם לקוח אב],"Sum",SUMX(_LYCheckTable,[QtyCheck]))
			                    ,[Sum]>=_MonthXParameter)
			                ,dimCustomers[שם לקוח אב])
			VAR __CurrentSumTable=SELECTCOLUMNS(
			                                    FILTER(
			                                        SUMMARIZE(dimCustomers,dimCustomers[שם לקוח אב],"SumOpenOrder",_OpenOrders+_OpenOrdersExecution)
			                                    ,[SumOpenOrder] = BLANK())
			                                ,dimCustomers[שם לקוח אב])
			
			VAR _Count = COUNTROWS(INTERSECT(_LYSumTable,__CurrentSumTable))
			
			RETURN
			_Count
		formatString: 0
		lineageTag: fbe9e845-fe42-4197-a11a-aa782b62fd8b

		changedProperty = IsHidden

	measure 'Lazy Customer - Execution' =
			
			[Lazy Customer - Execution Last X Month]
		formatString: 0
		lineageTag: 055553e0-7130-4e33-bc30-dd9043e40161

		changedProperty = IsHidden

	measure 'Lazy Customer - Decline Last Year' = ```
			
			VAR PrecentageParameter = SELECTEDVALUE(LazyCustomerInDeclinePercentage[LazyCustomerInDeclinePercentage])
			
			RETURN
			
			IF([% change YTD Quantity LY Comparsion]<=-1*(PrecentageParameter/100),1,BLANK())
			
			```
		formatString: 0
		lineageTag: 57e3ae25-567c-49ee-a523-52c6e6e9363f

		changedProperty = IsHidden

	measure 'Switch Measures Price' =
			
			//SWITCH(TRUE(),
			//ISINSCOPE(dimDates[MonthInCalendarName]),
			//,
			IF(HASONEVALUE(dimItemsSimple[Article_Description]),
			    SWITCH(MAX(SwitchMeasure[ID]),
			    1,[Stock Price - Risk Plan],
			    2,[Avg Cost Price Supply Date - Risk Plan],
			    3,[AVG Sales Balance Price Flat+FlatValue],--[Avg Unit Price By Supply Date],--[Avg Price Supply Date Switch],
			    4,[Remain Price - Risk Plan],
			    BLANK()
			    )
			,
			    SWITCH(MAX(SwitchMeasure[ID]),
			    1,CALCULATE([Stock Price - Risk Plan],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    2,CALCULATE([Avg Cost Price Supply Date - Risk Plan],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    3,CALCULATE([AVG Sales Balance Price Flat+FlatValue],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    4,CALCULATE([Remain Price - Risk Plan],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    BLANK()))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 2a46cb0f-a67a-4770-b27f-ecae66bda713

		changedProperty = IsHidden

	measure 'Switch Measure' =
			
			SWITCH(MIN('QtyPrice Table'[ID]),
			1,[Switch Measures Show],
			2,[Switch Measures Price],
			BLANK())
		lineageTag: b461e317-9fb7-4e50-b6c8-ee2103fa53d3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Open Orders DynamicTable' = ```
			
			
			VAR _LastDay = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			VAR _OpenOrder= 
			CALCULATE([Open Orders Quantity],REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factOrders[Date]),FILTER(ALL(dimDates),dimDates[Date]<=_LastDay))
			
			RETURN
			
			CALCULATE( [Open Orders Quantity],REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factOrders[Date]),FILTER(ALL(dimDates),dimDates[Date]<=_LastDay))
			
			```
		formatString: #,0
		displayFolder: Dynamic Table
		lineageTag: a61c351e-86f3-4d19-a96f-c44cec4b1594

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Quantity Open Orders Supply Date DynamicTable' = ```
			
			[Open Orders Quantity By Supply Date]
			
			```
		displayFolder: Dynamic Table
		lineageTag: 780fdc99-aa9a-49de-96f8-7efe410c686a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Open Quantity Dynamic Table Switch' =
			
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,[Quantity Open Orders DynamicTable],
			2,[Quantity Open Orders Supply Date DynamicTable],
			3,[Quantity Open Orders Supply Date DynamicTable],
			[Quantity Open Orders DynamicTable])
		displayFolder: Dynamic Table
		lineageTag: 6775c388-aa75-493a-9abd-459846c85efb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Remain Price - Risk Plan' =
			
			VAR LastUpdated=CALCULATE(MAX(factInventory[Date]),ALL(factInventory))
			var StockCostCurrentMonth = CALCULATE(CALCULATE([Inventory Value Switch],factInventory[Date]=LastUpdated),ALL(dimDates))
			var StockQtyCurrentMonth = CALCULATE(CALCULATE([Inventory Balance - Quantity],factInventory[Date]=LastUpdated),ALL(dimDates))
			VAR _MaxDate = MAX(dimDates[Date])
			var _Quantity = CALCULATE(
			    --CALCULATE(SUM(factPurchaseOrder[Quantity]),factPurchaseOrder[IsOpen]="1",USERELATIONSHIP(dimDates[Date],factPurchaseOrder[Supply Date]))
			    CALCULATE(SUM(factPurchaseOrder[Balance]),factPurchaseOrder[IsOpen]="1",USERELATIONSHIP(dimDates[Date],factPurchaseOrder[Supply Date]))
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate),USERELATIONSHIP(dimDates[Date],factPurchaseOrder[Supply Date]))
			VAR _Positive = DIVIDE( StockCostCurrentMonth+[All Open Purchase Cost By Supply Date - Risk Plan],StockQtyCurrentMonth+_Quantity,BLANK())
			
			return
			IF([Remain - Risk Plan] >=0 ,_Positive,[AVG Sales Balance Price Flat+FlatValue]--[AVG Sales Price Flat+FlatValue By Supply Date]--[AVG Price Supply Date Switch] --[Avg Unit Price By Supply Date]--
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Risk Plan
		lineageTag: 03afc911-41b8-496b-8876-5796f4575afa

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Stock Price - Risk Plan' =
			
			IF(MAX(dimDates[Show Months])="This Month",
			    [Inventory Avg Value Switch],
			    --[Stock Price calculated Flat]
			    CALCULATE([Remain Price - Risk Plan],DATEADD(dimDates[Date],-1,MONTH))
			)
			
			--IF(MAX(dimDates[Show Months])="This Month",[Inventory Avg Value Switch],[Stock Price calculated])--[Stock Price calculated Flat+FlatValue])--
		displayFolder: Risk Plan
		lineageTag: 810980d2-c0e4-4676-be8e-5e3928ded651

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Price Dynamic Table Details Switch' =
			
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,[Avg Unit Price],
			2,[Avg Unit Price By Supply Date],
			3,[Avg Unit Price (Sales)],
			[Avg Unit Price])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Dynamic Table
		lineageTag: d9274d4e-fe47-4c9f-a3aa-5f542c48554b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Quantity Dynamic Table Switch Filter' =
			
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,[Quantity Orders DynamicTable]+0,
			2,[Quantity Supply Date DynamicTable]+0,
			3,[Quantity Execution DynamicTable]+0,
			[Quantity Orders DynamicTable]+0)
		displayFolder: Dynamic Table
		lineageTag: 58b533e2-4cc3-4133-9597-28d4f1063e4f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch LY Filter' =
			
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,[Quantity Orders DynamicTable LY]+0,
			2,[Quantity Supply DynamicTable LY]+0,
			3,[Quantity Execution DynamicTable LY]+0,
			[Quantity Orders DynamicTable LY]+0)
		displayFolder: Dynamic Table
		lineageTag: 0efd2b46-3a8c-4819-a380-209437c46fd9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Orders DynamicTable LY YTD' = ```
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-1
			RETURN
			--CALCULATE(CALCULATE([Total Quantity],FILTER(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR),dimDates[Is History to Today]=1,Sub_DimDates[Is History To Today]=1))
			CALCULATE(
			    CALCULATE(
			        [Total Quantity],
			        Sub_DimDates[Year]=_YEAR,
			        DATEADD(Sub_DimDates[Date],-1,YEAR),
			        DATEADD(DimDates[Date],-1,YEAR)
			        
			    )
			,dimDates[IsHistory]=1
			)
			```
		displayFolder: Dynamic Table
		lineageTag: 2e0997b5-1629-41bc-ab8f-d596c565db2b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Execution DynamicTable LY YTD' = ```
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-1
			RETURN
			CALCULATE(
			    CALCULATE(
			        [Total Quantity (Sales) By Delivery Date TO DATE],
			        Sub_DimDates[Year]=_YEAR,
			        DATEADD(Sub_DimDates[Date],-1,YEAR),
			        DATEADD(DimDates[Date],-1,YEAR)
			        
			    )
			,dimDates[IsHistory]=1
			)
			--CALCULATE(CALCULATE([Total Quantity (Sales)],FILTER(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR),dimDates[Is History to Today]=1,Sub_DimDates[Is History To Today]=1))--,DATEADD(dimDates[Date],-1,YEAR),DATEADD(Sub_DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1,Sub_DimDates[IsHistory]=1)
			/*
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[LastYear])),dimDates[IsHistory]=1)
			VAR _Month = Month(MAX(Sub_DimDates[Date]))
			
			RETURN
			SWITCH(TRUE(),
			HASONEVALUE(Sub_DimDates[MonthInCalendarName]) || HASONEVALUE(Sub_DimDates[ShortMonthName]),
			CALCULATE([Total Quantity (Sales)],REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factSales[DeliveryDate]),Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR && Sub_DimDates[MonthNumberOfYear]=_Month&& Sub_DimDates[Is History to Today] = 1)),
			CALCULATE([Total Quantity (Sales)],REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factSales[DeliveryDate]),Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR && Sub_DimDates[Is History to Today] = 1))
			)
			*/
			```
		displayFolder: Dynamic Table
		lineageTag: 0c727b18-732d-4957-b688-f9cb6046ca03

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Supply DynamicTable LY YTD_backup' = ```
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[LastYear])),dimDates[IsHistory]=1)
			VAR _todate = CALCULATE(MAX(dimDates[Date]),FILTER(ALL(dimDates),dimDates[IsHistory]=1))
			VAR _Maxdate = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			VAR _SubMaxdate = MAX(Sub_DimDates[Date])
			VAR _date = IF(_Maxdate<=_SubMaxdate,_Maxdate,_SubMaxdate)
			--min(_Maxdate,_SubMaxdate)
			
			
			RETURN
			CALCULATE(CALCULATE(CALCULATE([Total Quantity]
			                  ,FILTER(dimDates,dimDates[Date]<=_date) --13/02/2025
			                  ,Sub_DimDates[Year]=_YEAR --2024
			                  ,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			                  )
			        ,dimDates[IsHistory]=1
			        )
			,DATEADD(dimDates[Date],-1,YEAR),DATEADD(Sub_DimDates[Date],-1,YEAR)
			--,dimDates[Is History to Today]=1,Sub_DimDates[Is History To Today]=1
			)
			
			```
		displayFolder: Dynamic Table
		lineageTag: 4cc49309-e59d-417f-a49c-ec819468d220

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch' =
			
			VAR _Blank = IF(HASONEVALUE(Sub_DimDates[MonthInCalendarName]),"-",0)
			Return
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,[Quantity Orders DynamicTable],
			2,[Quantity Supply Date DynamicTable],
			3,[Quantity Execution DynamicTable],
			[Quantity Orders DynamicTable]
			)
		formatString: #,0
		displayFolder: Dynamic Table
		lineageTag: aca5439e-62bc-473e-8c9e-9814b06f8316

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Open Quantity Switch' =
			
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			0,[Open Orders Quantity],
			1,[Open Orders Quantity By Supply Date],
			2,Blank(),
			[Open Orders Quantity])
		lineageTag: 052d08bd-af71-4ddf-a714-2f1ee4023e0f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch LY No -' = ```
			
			
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,[Quantity Orders DynamicTable LY],
			2,[Quantity Supply DynamicTable LY],
			3,[Quantity Execution DynamicTable LY],
			[Quantity Orders DynamicTable LY])
			
			```
		displayFolder: Dynamic Table
		lineageTag: 41fa2b1a-6e1f-484f-a3d5-08a4c8d92347

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch LY YTD Visual' =
			
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,[Quantity Orders DynamicTable LY YTD],
			2,[Quantity Supply DynamicTable LY YTD],
			3,[Quantity Execution DynamicTable LY YTD],
			[Quantity Orders DynamicTable LY YTD])
		displayFolder: Dynamic Table
		lineageTag: 2553da79-91a7-4512-b92f-de41e341408a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Sales USD NIS LY Switch YTD' = ```
			
			 SWITCH(MAX(OrderVSExecutionVSSupply[ID]),
			    1,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE(CALCULATE([Total Sales NIS],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1),
			        2, CALCULATE(CALCULATE([Total Sales USD],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1),
			        3, CALCULATE(CALCULATE([Total Quantity],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1))
			    ,2,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE(CALCULATE([Total Sales NIS Supply TO DATE],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1),
			        2, CALCULATE(CALCULATE([Total Sales USD Supply TO DATE],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1),
			        3, CALCULATE(CALCULATE([Total Quantity Supply TO DATE],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1))
			    ,3,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE(CALCULATE([Total Sales NIS (Sales)],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1),
			        2, CALCULATE(CALCULATE([Total Sales USD (Sales)],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1),
			        3, CALCULATE(CALCULATE([Total Quantity (Sales)],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1))
			 )+0
			```
		displayFolder: Dynamic Switch Graph Measures
		lineageTag: 35c157a0-3bb3-4e5d-9f89-05b66d7243b2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Sales USD NIS 2Y Switch YTD' = ```
			
			 SWITCH(MAX(OrderVSExecutionVSSupply[ID]),
			    1,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE(CALCULATE([Total Sales NIS],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),dimDates[IsHistory]=1),
			        2, CALCULATE(CALCULATE([Total Sales USD],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),dimDates[IsHistory]=1),
			        3, CALCULATE(CALCULATE([Total Quantity],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),dimDates[IsHistory]=1))
			    ,2,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE(CALCULATE([Total Sales NIS Supply Date],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),dimDates[IsHistory]=1),
			        2, CALCULATE(CALCULATE([Total Sales USD Supply Date],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),dimDates[IsHistory]=1),
			        3, CALCULATE(CALCULATE([Total Quantity Supply TO DATE],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),dimDates[IsHistory]=1))
			    ,3,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE(CALCULATE([Total Sales NIS (Sales)],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),dimDates[IsHistory]=1),
			        2, CALCULATE(CALCULATE([Total Sales USD (Sales)],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),dimDates[IsHistory]=1),
			        3, CALCULATE(CALCULATE([Total Quantity (Sales)],DATEADD(Sub_DimDates[Date],-2,YEAR),DATEADD(DimDates[Date],-2,YEAR)),dimDates[IsHistory]=1))
			 )+0
			```
		displayFolder: Dynamic Switch Graph Measures
		lineageTag: 83ac0eb3-074e-4382-87f6-de68d0421ddb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Orders DynamicTable 2Y' =
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-2
			RETURN
			CALCULATE([Total Quantity],Sub_DimDates[Year]=_YEAR,DATEADD(dimDates[Date],-2,YEAR),DATEADD(Sub_DimDates[Date],-2,YEAR))
			/*
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[LastYear])),dimDates[IsHistory]=1)-1
			VAR _Month = Month(MAX(Sub_DimDates[Date]))
			
			RETURN
			SWITCH(TRUE(),
			HASONEVALUE(Sub_DimDates[MonthInCalendarName]),
			CALCULATE([Total Quantity],REMOVEFILTERS(dimDates),REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factOrders[Date]),Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR && Sub_DimDates[MonthNumberOfYear] =_Month)),
			CALCULATE([Total Quantity],REMOVEFILTERS(dimDates),REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factOrders[Date]),Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR))
			--,DATEADD(Sub_DimDates[Date],-1,YEAR),Sub_DimDates[Year]=_YEAR,Sub_DimDates[IsHistory]=1)
			)*/
		formatString: 0
		displayFolder: Dynamic Table
		lineageTag: 85c318be-f9d5-465b-bba1-759b337bf0d8

		changedProperty = IsHidden

	measure 'Quantity Execution DynamicTable 2Y' =
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-2
			RETURN
			CALCULATE([Total Quantity (Sales)],Sub_DimDates[Year]=_YEAR)--,DATEADD(dimDates[Date],-2,YEAR),DATEADD(Sub_DimDates[Date],-2,YEAR),Sub_DimDates[Year]=_YEAR)
			/*
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-2
			VAR _Month = Month(MAX(Sub_DimDates[Date]))
			
			RETURN
			SWITCH(TRUE(),
			HASONEVALUE(Sub_DimDates[MonthInCalendarName]),
			CALCULATE([Total Quantity (Sales)],REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factSales[DeliveryDate]),Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR && Sub_DimDates[MonthNumberOfYear]=_Month)),
			CALCULATE([Total Quantity (Sales)],REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factSales[DeliveryDate]),Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR))
			)*/
		displayFolder: Dynamic Table
		lineageTag: 622269fc-a46e-4d73-873c-e7d8a81091fc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Supply DynamicTable 2Y' =
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-2
			RETURN
			CALCULATE([Total Quantity Supply Date],
			            Sub_DimDates[Year]=_YEAR,
			            DATEADD(Sub_DimDates[Date],-2,YEAR),
			            DATEADD(DimDates[Date],-2,YEAR)
			        )
			
			/*CALCULATE([Total Quantity],
			            Sub_DimDates[Year]=_YEAR,
			            DATEADD(Sub_DimDates[Date],-2,YEAR),
			            DATEADD(DimDates[Date],-2,YEAR)
			        )
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[LastYear])),dimDates[IsHistory]=1)-1
			VAR _Month = Month(MAX(Sub_DimDates[Date]))
			
			RETURN
			SWITCH(TRUE(),
			HASONEVALUE(Sub_DimDates[MonthInCalendarName]),
			CALCULATE([Total Quantity],USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]),REMOVEFILTERS(dimDates)
			,Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR && Sub_DimDates[MonthNumberOfYear]=_Month)),
			CALCULATE([Total Quantity],USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]),REMOVEFILTERS(dimDates)
			--,DATEADD(Sub_DimDates[Date],-1,YEAR),Sub_DimDates[Year]=_YEAR,Sub_DimDates[IsHistory]=1)
			,Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR))
			)
			*/
		displayFolder: Dynamic Table
		lineageTag: 8893302f-fd0d-4d3f-91dd-7dbc6698a363

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Orders DynamicTable 2Y YTD' =
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-2
			RETURN
			--CALCULATE(CALCULATE([Total Quantity],Sub_DimDates[Year]=_YEAR,dimDates[Is History to Today]=1,Sub_DimDates[Is History To Today]=1))--,DATEADD(dimDates[Date],-2,YEAR),DATEADD(Sub_DimDates[Date],-2,YEAR)),dimDates[IsHistory]=1,Sub_DimDates[IsHistory]=1)
			CALCULATE(
			    CALCULATE(
			        [Total Quantity],
			        Sub_DimDates[Year]=_YEAR,
			        DATEADD(Sub_DimDates[Date],-2,YEAR),
			        DATEADD(DimDates[Date],-2,YEAR)
			    )
			,dimDates[IsHistory]=1
			)
			/*
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[LastYear])),dimDates[IsHistory]=1)-1
			VAR _Month = Month(MAX(Sub_DimDates[Date]))
			
			RETURN
			SWITCH(TRUE(),
			HASONEVALUE(Sub_DimDates[MonthInCalendarName]),
			CALCULATE([Total Quantity],REMOVEFILTERS(dimDates),REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factOrders[Date]),Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR && Sub_DimDates[MonthNumberOfYear] =_Month)),
			CALCULATE([Total Quantity],REMOVEFILTERS(dimDates),REMOVEFILTERS(dimDates),USERELATIONSHIP(Sub_DimDates[Date],factOrders[Date]),Filter(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR && Sub_DimDates[Is History to Today] = 1))
			--,DATEADD(Sub_DimDates[Date],-1,YEAR),Sub_DimDates[Year]=_YEAR,Sub_DimDates[IsHistory]=1)
			)
			*/
		displayFolder: Dynamic Table
		lineageTag: 706678b8-8e6c-45b9-8984-d5b1189895f5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Execution DynamicTable 2Y YTD' = ```
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-2
			RETURN
			CALCULATE(
			    CALCULATE(
			        [Total Quantity (Sales) By Delivery Date TO DATE],
			        Sub_DimDates[Year]=_YEAR,
			        DATEADD(Sub_DimDates[Date],-2,YEAR),
			        DATEADD(DimDates[Date],-2,YEAR)
			        
			    )
			,dimDates[IsHistory]=1
			)
			--CALCULATE(CALCULATE([Total Quantity (Sales)],Sub_DimDates[Year]=_YEAR,dimDates[Is History to Today]=1,Sub_DimDates[Is History To Today]=1))
			```
		displayFolder: Dynamic Table
		lineageTag: d9b83536-e301-410e-8dcb-c13d2b5a6b4a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch 2Y' = ```
			
			
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,[Quantity Orders DynamicTable 2Y],
			2,[Quantity Supply DynamicTable 2Y],
			3,[Quantity Execution DynamicTable 2Y],
			[Quantity Orders DynamicTable 2Y])
			
			```
		displayFolder: Dynamic Table
		lineageTag: a495c841-e20f-4d64-aa06-1700362eaada

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch 2Y YTD' =
			
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,[Quantity Orders DynamicTable 2Y YTD],
			2,[Quantity Supply DynamicTable 2Y YTD],
			3,[Quantity Execution DynamicTable 2Y YTD],
			[Quantity Orders DynamicTable 2Y YTD])
		displayFolder: Dynamic Table
		lineageTag: 039a91db-e3d2-417c-b73f-5d9fa70d20b8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Diff Indicator' =
			
			IF(ISBLANK([Quantity Dynamic Table Switch]) && ISBLANK([Quantity Dynamic Table Switch LY YTD Visual]),BLANK(),
			IF([Quantity Dynamic Table Switch] - [Quantity Dynamic Table Switch LY YTD Visual] > 2000,
			 1,
			    IF(DIVIDE([Quantity Dynamic Table Switch] - [Quantity Dynamic Table Switch LY YTD Visual],[Quantity Dynamic Table Switch LY YTD Visual])>=0.5, 1,
			  IF([Quantity Dynamic Table Switch] - [Quantity Dynamic Table Switch LY YTD Visual] < -2000,
			    -1,
			    IF(DIVIDE([Quantity Dynamic Table Switch] - [Quantity Dynamic Table Switch LY YTD Visual],[Quantity Dynamic Table Switch LY YTD Visual])<-0.4,-1,
			 IF([Quantity Dynamic Table Switch] - [Quantity Dynamic Table Switch LY YTD Visual] < -200,
			    0,
			    IF(DIVIDE([Quantity Dynamic Table Switch] - [Quantity Dynamic Table Switch LY YTD Visual],[Quantity Dynamic Table Switch LY YTD Visual])<-0.2,0,
			    BLANK()
			    )
			 )
			 )
			))))
		formatString: 0
		displayFolder: Dynamic Table
		lineageTag: 18726b16-0cb8-4dbd-a2fd-4b79de8beef9

		changedProperty = IsHidden

	measure 'Dynamic Table Target' =
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[Date])),dimDates[IsHistory]=1)
			
			
			RETURN
			--SWITCH(TRUE(),
			--HASONEVALUE(Sub_DimDates[MonthInCalendarName]),BLANK(),
			CALCULATE([Total Target],REMOVEFILTERS(dimDates),Sub_DimDates[Year]=_YEAR,Sub_DimDates[IsHistory]=1)
			--)
		displayFolder: Dynamic Table\Column
		lineageTag: 10e5975e-eea2-4d93-a766-5919638bc028

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch Open Orders' =
			
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,[Quantity Open Orders DynamicTable],
			2,[Quantity Open Orders Supply Date DynamicTable],
			3,[Quantity Open Orders Supply Date DynamicTable],
			[Quantity Open Orders DynamicTable])
		displayFolder: Dynamic Table\Column
		lineageTag: 52b67ff2-13dd-4a02-9f5a-5d0bcd4a7944

		formatStringDefinition = ```
				VAR V = [Quantity Dynamic Table Switch Open Orders] 
				RETURN
				IF(
				    NOT ISNUMBER(V),
				    "-",
				    SWITCH(
				        TRUE(),
				        ABS(V) >= 1000000, "#,0,,.0#M",
				        ABS(V) >= 1000, "#,0,.0#K",
				        "#,0"
				    )
				)
				
				```

		changedProperty = IsHidden

	measure 'Quantity Dynamic Table Switch LY YTD' = ```
			
			
			VAR _Calc =
			    SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			    1,IF(ISBLANK([Quantity Orders DynamicTable LY YTD]),"-",[Quantity Orders DynamicTable LY YTD]),
			    2,IF(ISBLANK([Quantity Supply DynamicTable LY YTD_backup]),"-",[Quantity Supply DynamicTable LY YTD_backup]),
			    3,IF(ISBLANK([Quantity Execution DynamicTable LY YTD]),"-",[Quantity Execution DynamicTable LY YTD]),
			    IF(ISBLANK([Quantity Orders DynamicTable LY YTD]),"-",[Quantity Orders DynamicTable LY YTD])
			    )
			RETURN
			
			_Calc
			
			```
		displayFolder: Dynamic Table\Column
		lineageTag: 91d428a9-f1bb-42ca-9f19-32a763ed1580

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch Diff %' = ```
			
			Divide(
			    ([Quantity Dynamic Table Switch] - [Quantity Dynamic Table Switch LY FYvsYTD]), 
			    [Quantity Dynamic Table Switch LY FYvsYTD])
			```
		formatString: 0.0%;(0.0%);0.0%
		displayFolder: Dynamic Table\Column
		lineageTag: 08420f84-e229-4b7a-a6fb-466884eab62e

		changedProperty = IsHidden

	measure 'Lazy Customer Check or Decline' = ```
			
			    IF(
			        [Lazy Customer - Supply Date] + [Lazy Customer - Execution]>0,
			        UNICHAR(128276),
			            BLANK()
			        )
			  
			```
		displayFolder: Dynamic Table\Column
		lineageTag: b34b05fd-26ad-4c47-a60d-0471e2c692b0

		changedProperty = IsHidden

	measure 'Qty Last 3 Month' = ```
			VAR _today = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			VAR _3MonthAgo = Date(YEAR(_today),Month(_today),Day(_today)-91)
			
			RETURN
			CALCULATE([Quantity Dynamic Table Switch]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_today && dimDates[Date] > _3MonthAgo)) +0
			    
			```
		lineageTag: 13153ba1-1b39-4bb2-a94f-779bab999c9c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qty Last 3 Month Previous Period' = ```
			VAR _today = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			VAR _3MonthAgo = Date(YEAR(_today),Month(_today),Day(_today)-91)
			VAR _6MonthAgo = Date(YEAR(_today),Month(_today),Day(_today)-181)
			
			RETURN
			CALCULATE([Quantity Dynamic Table Switch]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_3MonthAgo && dimDates[Date] > _6MonthAgo))
			    
			```
		lineageTag: 604a07e9-43b3-4461-8168-6e06f81c6740

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qty Last 3 Month Parallel Period' = ```
			VAR _today = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			VAR _3MonthAgo = Date(YEAR(_today),Month(_today),Day(_today)-91)
			VAR _todayLY = CALCULATE(MAX(dimDates[LastYear]),dimDates[IsHistory]=1)
			VAR _3MonthAgoLY = Date(YEAR(_todayLY),Month(_todayLY),Day(_todayLY)-91)
			
			RETURN
			CALCULATE([Quantity Dynamic Table Switch]--[Transactions Quantity])
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_todayLY && dimDates[Date] > _3MonthAgoLY))
			    
			```
		lineageTag: e31dbc88-0308-4ed7-877a-669701b3c974

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qty Last 3 Month Parallel Period MAX' =
			VAR _today = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			VAR _3MonthAgo = Date(YEAR(_today),Month(_today),Day(_today)-91)
			VAR _todayLY = CALCULATE(MAX(dimDates[LastYear]),dimDates[IsHistory]=1)
			VAR _3MonthAgoLY = Date(YEAR(_todayLY),Month(_todayLY),Day(_todayLY)-91)
			
			
			RETURN
			CALCULATE([Quantity Dynamic Table Switch]--[Transactions Quantity])
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_todayLY && dimDates[Date] > _3MonthAgoLY))*2+0
		lineageTag: 93c3ec39-1b81-4af6-91db-6bdbc98bdb7d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qty Last 3 Month Previous Period MAX' = ```
			VAR _today = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			VAR _3MonthAgo = Date(YEAR(_today),Month(_today),Day(_today)-91)
			VAR _6MonthAgo = Date(YEAR(_today),Month(_today),Day(_today)-181)
			
			RETURN
			CALCULATE([Quantity Dynamic Table Switch]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_3MonthAgo && dimDates[Date] > _6MonthAgo))*2
			    
			```
		lineageTag: 08964645-14e9-4ee6-97b3-98fd6142011e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qty Last 3 Month Parallel Period MIN' =
			VAR _today = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			VAR _3MonthAgo = Date(YEAR(_today),Month(_today),Day(_today)-91)
			VAR _todayLY = CALCULATE(MAX(dimDates[LastYear]),dimDates[IsHistory]=1)
			VAR _3MonthAgoLY = Date(YEAR(_todayLY),Month(_todayLY),Day(_todayLY)-91)
			
			
			RETURN
			CALCULATE([Quantity Dynamic Table Switch]--[Transactions Quantity])
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_todayLY && dimDates[Date] > _3MonthAgoLY))*0.5+0
		lineageTag: 435055e2-ac04-4782-988e-9d102991aeb1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qty Last 3 Month Previous Period MIN' = ```
			VAR _today = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			VAR _3MonthAgo = Date(YEAR(_today),Month(_today),Day(_today)-91)
			VAR _6MonthAgo = Date(YEAR(_today),Month(_today),Day(_today)-181)
			
			RETURN
			CALCULATE([Quantity Dynamic Table Switch]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_3MonthAgo && dimDates[Date] > _6MonthAgo))*0.5
			    
			```
		lineageTag: 6928479f-7fcf-448f-bc2a-de196db67a8d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qty Last 3 Month Parallel Period Diff' = [Qty Last 3 Month] - [Qty Last 3 Month Parallel Period]
		lineageTag: 66510efe-2e35-4779-9467-15b392999648

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qty Last 3 Month Previous Period Diff' = ```
			[Qty Last 3 Month] - [Qty Last 3 Month Previous Period]
			    
			```
		lineageTag: e2434bf3-6be3-429f-91de-dab3e161492d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales CF' =
			//SUM(factSales[LineTotalNet])
			    SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1,[Total Sales NIS CF],
			        2,[Total Sales USD CF],
			   [Total Sales USD CF])
		displayFolder: CF
		lineageTag: 2eba1dc0-5d76-4788-81b3-8239d541ebe9

		formatStringDefinition =
				SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
				1,"₪ ,#,0.00",
				2,"$ ,#,0.00",
				"$ ,#,0.00")

		changedProperty = IsHidden

	measure 'Total Sales NIS CF' =
			
			SUM('factOrders'[LineTotalCF_NIS])
		formatString: "₪"\ #,0.00;"₪"-#,0.00;"₪"\ #,0.00
		displayFolder: CF
		lineageTag: c0ef2e14-d9cf-46ad-bc49-0f4b5dbb311a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"he-IL"}

	measure 'Total Sales USD CF' =
			
			SUM('factOrders'[LineTotalCF_USD])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: CF
		lineageTag: 634a0002-5cb7-49a3-8601-3e75777a1d2f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sales YTD CF' = CALCULATE(CALCULATE([Total Sales CF],DATESYTD(dimDates[Date]),DATESYTD(Sub_DimDates[Date])),dimDates[IsHistory]=1,Sub_DimDates[IsHistory]=1)
		displayFolder: CF
		lineageTag: 4090c48e-2b54-4c4f-8682-72ae3eb2d34e

		formatStringDefinition =
				SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
				1,"₪ ,#,0.00",
				2,"$ ,#,0.00",
				"$ ,#,0.00")

		changedProperty = IsHidden

	measure 'Avg CF Price By Supply Date' =
			
			
			CALCULATE(DIVIDE([Total Sales CF],[Total Quantity]),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה]))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CF
		lineageTag: b8896172-1f70-436d-a4b0-b3603f76d5f4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg CF Price' = DIVIDE([Total Sales CF],[Total Quantity])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CF
		lineageTag: b1b38072-6cbf-4740-a94a-1552447cfb01

		changedProperty = IsHidden

	measure 'Avg FOT Price' = DIVIDE([Total Sales FOT],[Total Quantity])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: FOT
		lineageTag: 27f81534-3210-41a0-b27b-c0f2f71dbfc4

		changedProperty = IsHidden

	measure 'Total Sales FOT' =
			//SUM(factSales[LineTotalNet])
			    SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1,[Total Sales NIS FOT],
			        2,[Total Sales USD FOT],
			   [Total Sales USD FOT])
		displayFolder: FOT
		lineageTag: fbd91d18-0048-4262-93dd-5a67b7d11ba6

		formatStringDefinition =
				SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
				1,"₪ ,#,0.00",
				2,"$ ,#,0.00",
				"$ ,#,0.00")

		changedProperty = IsHidden

	measure 'Total Sales NIS FOT' =
			
			SUM('factOrders'[LineTotalFOT_NIS])
		formatString: "₪"\ #,0.00;"₪"-#,0.00;"₪"\ #,0.00
		displayFolder: FOT
		lineageTag: f803865b-e2a7-4621-a078-464e5efdb6f2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"he-IL"}

	measure 'Total Sales USD FOT' =
			
			SUM('factOrders'[LineTotalFOT_USD])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: FOT
		lineageTag: ac821984-b447-41bf-8e5a-a42016e276f7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sales YTD FOT' = CALCULATE(CALCULATE([Total Sales FOT],DATESYTD(dimDates[Date]),DATESYTD(Sub_DimDates[Date])),dimDates[IsHistory]=1,Sub_DimDates[IsHistory]=1)
		displayFolder: FOT
		lineageTag: 36049314-4833-4f14-b8f8-dd1ed6dce990

		formatStringDefinition =
				SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
				1,"₪ ,#,0.00",
				2,"$ ,#,0.00",
				"$ ,#,0.00")

		changedProperty = IsHidden

	measure 'Avg FOT Price By Supply Date' =
			
			
			CALCULATE(DIVIDE([Total Sales FOT],[Total Quantity]),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה]))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: FOT
		lineageTag: 7ad7d8e6-9092-439d-a83e-acc16e476642

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Price Date Switch CF' = ```
			
			Var _today = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			Var _thisMonth = EOMONTH(_today,0)
			VAR _ThisWeek = CALCULATE(MAX(dimDates[WeekEnding]),dimDates[IsHistory]=1)
			Var _Daily = EOMONTH(_today,-2)
			VAR _Weekly = EOMONTH(_today,-7)
			VAR _Monthly = EOMONTH(_today,-9)
			VAR _WeeklyFull = CALCULATE(MAX(dimDates[WeekStart]),FILTER(dimDates,dimDates[Date]=_Weekly))
			RETURN
			
			SWITCH(SELECTEDVALUE('Time Selection'[Time Selection Order]),
			0,SWITCH(SELECTEDVALUE(OrderVSExecutionVSSupply[ID]),
			    1,CALCULATE([Avg CF Price],FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Daily)),
			     2,CALCULATE([Avg CF Price By Supply Date],USERELATIONSHIP(Sub_dimDates[Date],factOrders[תאריך אספקה]),FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Daily))
			    ),
			1,SWITCH(SELECTEDVALUE(OrderVSExecutionVSSupply[ID]),
			    1,CALCULATE([Avg CF Price],FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>=_WeeklyFull)),
			     2,CALCULATE([Avg CF Price By Supply Date],USERELATIONSHIP(Sub_dimDates[Date],factOrders[תאריך אספקה]),FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>=_WeeklyFull))
			    ),
			2,SWITCH(SELECTEDVALUE(OrderVSExecutionVSSupply[ID]),
			    1,CALCULATE([Avg CF Price],FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Monthly)),
			    2,CALCULATE([Avg CF Price By Supply Date],USERELATIONSHIP(Sub_dimDates[Date],factOrders[תאריך אספקה]),FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Monthly))
			    )
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CF
		lineageTag: fee1096f-b52e-4a04-ae33-b2eff44791fd

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Price Date Switch FOT' = ```
			
			Var _today = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			Var _thisMonth = EOMONTH(_today,0)
			VAR _ThisWeek = CALCULATE(MAX(dimDates[WeekEnding]),dimDates[IsHistory]=1)
			Var _Daily = EOMONTH(_today,-2)
			VAR _Weekly = EOMONTH(_today,-7)
			VAR _Monthly = EOMONTH(_today,-9)
			VAR _WeeklyFull = CALCULATE(MAX(dimDates[WeekStart]),FILTER(dimDates,dimDates[Date]=_Weekly))
			RETURN
			
			SWITCH(SELECTEDVALUE('Time Selection'[Time Selection Order]),
			0,SWITCH(SELECTEDVALUE(OrderVSExecutionVSSupply[ID]),
			    1,CALCULATE([Avg FOT Price],FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Daily)),
			     2,CALCULATE([Avg FOT Price By Supply Date],USERELATIONSHIP(Sub_dimDates[Date],factOrders[תאריך אספקה]),FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Daily))
			    ),
			1,SWITCH(SELECTEDVALUE(OrderVSExecutionVSSupply[ID]),
			    1,CALCULATE([Avg FOT Price],FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>=_WeeklyFull)),
			     2,CALCULATE([Avg FOT Price By Supply Date],USERELATIONSHIP(Sub_dimDates[Date],factOrders[תאריך אספקה]),FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>=_WeeklyFull))
			    ),
			2,SWITCH(SELECTEDVALUE(OrderVSExecutionVSSupply[ID]),
			    1,CALCULATE([Avg FOT Price],FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Monthly)),
			    2,CALCULATE([Avg FOT Price By Supply Date],USERELATIONSHIP(Sub_dimDates[Date],factOrders[תאריך אספקה]),FILTER(Sub_dimDates,Sub_dimDates[Date]<=_today &&Sub_dimDates[Date]>_Monthly))
			    )
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: FOT
		lineageTag: 0275bdc3-5f91-4d9a-b6da-a1341e9b7158

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Price Date PriceType Switch' =
			
			SWITCH(MIN(PriceType[ID]),
			1,[Avg Price Date Switch],
			2,[Avg Price Date Switch CF],
			3,[Avg Price Date Switch FOT],
			[Avg Price Date Switch]
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 66eb04fe-1189-47dd-9529-eb9ae0e7a5e6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Price Switch' =
			
			
			SWITCH(MIN(PriceType[ID]),
			1,[Avg Unit Price],
			2,[Avg CF Price],
			3,[Avg FOT Price],
			[Avg Unit Price]
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 571ad79a-49ab-4c61-9c89-cc4ad724ef6b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Price Supply Date Switch' =
			
			SWITCH(MIN(PriceType[ID]),
			1,[Avg Unit Price By Supply Date],
			2,[Avg CF Price By Supply Date],
			3,[Avg FOT Price By Supply Date],
			[Avg Unit Price By Supply Date]
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 989ee743-6bd1-4275-8c4d-87e7287fef85

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Price Supply Date Margin' = ```
			
			VAR _AvgPrice= [AVG Price Supply Date Switch]
			VAR _AvgPriceALL = CALCULATE([AVG Price Supply Date Switch],FILTER(ALL(dimDates),dimDates[This Year Selection]="This Year"),ALL(dimCustomers))
			Var _Quantity = [Total Quantity Supply Date]
			VAR _QuantityALL = CALCULATE([Total Quantity Supply Date],FILTER(ALL(dimDates),dimDates[This Year Selection]="This Year"),ALL(dimCustomers))
			
			RETURN 
			(_AvgPrice - _AvgPriceALL)*(DIVIDE(_Quantity,_QuantityALL,0))
			```
		formatString: 0.00
		lineageTag: 55fea92e-aad5-4844-b88f-e2d64ded8164

		changedProperty = IsHidden

	measure 'Good Customer - Supply Date - 4 Out 9' =
			
			VAR _MonthXParameter = 4
			VAR _MonthYParameter = 9
			VAR _Date = CALCULATE(MAX(dimDates[Date]),ALL(dimDates),dimDates[IsHistory]=1)
			VAR _EOdate = EOMONTH(_Date,0)
			VAR _Ly = DATE(Year(_Date),MONTH(_Date)-9,DAY(_Date))
			VAR _OpenOrders = CALCULATE([Total Quantity Supply Date],Filter(ALL(dimDates),dimDates[Date]>_Date))
			VAR _QtyCheck = IF(ISBLANK(CALCULATE([Total Quantity Supply Date],FILTER(ALL(dimDates),dimDates[Date]>_Ly &&dimDates[Date]<=_EOdate))),0,1)
			VAR _LYCheckTable = CALCULATETABLE(SUMMARIZE(factOrders,dimCustomers[שם לקוח אב],dimDates[MonthInCalendarName],"QtyCheck",_QtyCheck),FILTER(dimDates,dimDates[Date]>_Ly &&dimDates[Date]<=_EOdate))
			VAR _LYSumTable=FILTER(
			                    SUMMARIZE(_LYCheckTable,dimCustomers[שם לקוח אב],"Sum",SUMX(_LYCheckTable,[QtyCheck]))
			                    ,[Sum]>=4)
			
			VAR _Count = COUNTROWS(_LYSumTable)
			
			RETURN
			_Count
		formatString: 0
		lineageTag: ad61f0ad-b2a2-4a62-b1e1-02a32f908925

		changedProperty = IsHidden

	measure 'Good Customer - Supply Date - 3 Out 6' = ```
			
			VAR _Date = CALCULATE(MAX(dimDates[Date]),ALL(dimDates),dimDates[IsHistory]=1)
			VAR _EOdate = EOMONTH(_Date,0)
			VAR _L6M = CALCULATE(
			            CALCULATE(MAX(dimDates[FirstDayOfMonth])  
			                        ,DATEADD(dimDates[Date],-6,MONTH)
			                     )
			                    ,dimDates[IsHistory]=1
			                    )
			--EDATE(_EOdate, -6)
			VAR _Months =
			    CALCULATETABLE(
			        VALUES(dimDates[FirstDayOfMonth]),
			        dimDates[FirstDayOfMonth] >= _L6M,
			        dimDates[FirstDayOfMonth] <= _EOdate,
			        dimDates[IsHistory] = 1
			    )
			VAR _ActiveMonthCount =
			    SUMX(
			        _Months,
			        // For each month from the _Months table, use the column name [FirstDayOfMonth] as the current month.
			        VAR CurrentMonth = [FirstDayOfMonth]
			        VAR _StartOfMonth = CurrentMonth
			        VAR _EndOfMonth = EOMONTH(CurrentMonth, 0)
			        VAR Qty =
			            CALCULATE(
			                [Total Quantity Supply Date_v1],
			                ALL(dimDates),
			                dimDates[Date] >= _StartOfMonth,
			                dimDates[Date] <= _EndOfMonth
			            )
			        RETURN IF(NOT(ISBLANK(Qty)) && Qty <> 0, 1, 0)
			    )
			RETURN
			        IF(_ActiveMonthCount >=3, 1, 0)
			
			/*VAR _L6M = CALCULATE(
			            CALCULATE(MAX(dimDates[FirstDayOfMonth])  
			                        ,DATEADD(dimDates[Date],-6,MONTH)
			                     )
			                    ,dimDates[IsHistory]=1
			                    )
			    --DATE(Year(_Date),MONTH(_Date)-6,DAY(_Date))
			VAR _QtyCheck = IF(ISBLANK(
			                        CALCULATE([Total Quantity Supply Date_v1],FILTER(ALL(dimDates),dimDates[Date]>=_L6M &&dimDates[Date]<=_EOdate))
			                        ),0,1)
			
			RETURN
			_QtyCheck */
			
			/* original measure
			VAR _MonthXParameter = 3
			VAR _MonthYParameter = 6
			VAR _Date = CALCULATE(MAX(dimDates[Date]),ALL(dimDates),dimDates[IsHistory]=1)
			VAR _EOdate = EOMONTH(_Date,0)
			VAR _Ly = DATE(Year(_Date),MONTH(_Date)-6,DAY(_Date))
			VAR _OpenOrders = CALCULATE([Total Quantity Supply Date],Filter(ALL(dimDates),dimDates[Date]>=_Date))
			VAR _QtyCheck = IF(ISBLANK(CALCULATE([Total Quantity Supply Date],FILTER(ALL(dimDates),dimDates[Date]>_Ly &&dimDates[Date]<=_EOdate))),0,1)
			VAR _LYCheckTable = CALCULATETABLE(SUMMARIZE(factOrders,dimCustomers[שם לקוח אב],dimDates[MonthInCalendarName],"QtyCheck",_QtyCheck),FILTER(dimDates,dimDates[Date]>_Ly &&dimDates[Date]<=_EOdate))
			VAR _LYSumTable=FILTER(
			                    SUMMARIZE(_LYCheckTable,dimCustomers[שם לקוח אב],"Sum",SUMX(_LYCheckTable,[QtyCheck]))
			                    ,[Sum]>=3)
			
			VAR _Count = COUNTROWS(_LYSumTable)
			
			RETURN
			_Count*/
			```
		formatString: 0
		lineageTag: 9124a75a-e861-45a9-9cd4-d4d0069b5d49

		changedProperty = IsHidden

	measure 'Good Customer - Supply Date_backup' =
			
			Var _4out9 = [Good Customer - Supply Date - 4 Out 9]
			Var _3Out6 = [Good Customer - Supply Date - 3 Out 6]
			Var _date = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			Var _OpenOrder = [Open Orders Quantity By Supply Date]
			Var _totalOrderThisYear = CALCULATE([Total Quantity Supply Date],Filter(dimDates,Year(dimDates[Date])=YEAR(_date)))
			Var _totalTransactionThisYear = CALCULATE([Transactions Quantity],USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה]),USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]),Filter(dimDates,Year(dimDates[Date])=YEAR(_date)))
			Var _MonthlyAVG = DIVIDE(_totalOrderThisYear,_totalTransactionThisYear,BLANK())
			
			RETURN
			SWITCH(TRUE(),
			ISBLANK(_OpenOrder),
			    _3Out6+_4out9,
			_OpenOrder<=_MonthlyAVG*1.2,
			        _3Out6 + _4out9,
			BLANK()
			)
		formatString: 0
		lineageTag: ef2ddb2b-3d3f-4d9b-b730-e7412afb575b

		changedProperty = IsHidden

	measure 'Good Customer Star' =
			
			IF(ISBLANK([Good Customer - Supply Date])|| [Good Customer - Supply Date] = 0,BLANK(),UNICHAR(128222))
		lineageTag: b2a3138a-ca6b-4ca6-a5e9-6d5920fbf9d6

		changedProperty = IsHidden

	measure 'Good Customer - Supply Date - Monthly AVG' =
			
			Var _4out9 = [Good Customer - Supply Date - 4 Out 9]
			Var _3Out6 = [Good Customer - Supply Date - 3 Out 6]
			Var _date = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			Var _OpenOrder = [Open Orders Quantity By Supply Date]
			Var _totalOrderThisYear = CALCULATE([Total Quantity Supply Date],Filter(dimDates,Year(dimDates[Date])=YEAR(_date)))
			Var _totalTransactionThisYear = CALCULATE([Transactions Quantity],USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה]),USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]),Filter(dimDates,Year(dimDates[Date])=YEAR(_date)))
			Var _MonthlyAVG = DIVIDE(_totalOrderThisYear,_totalTransactionThisYear,BLANK())
			
			RETURN
			_MonthlyAVG
		lineageTag: 2919bcfd-07ff-45fa-96c1-02bd75b10bab

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Full Monthly Quantity' =
			
			VAR _date = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			VAR _EoMONTH = EOMONTH(_date,0)
			var _SoMonth = EOMONTH(_date,-1)
			
			RETURN
			CALCULATE([Quantity Dynamic Table Switch],FILTER(ALL(dimDates[Date]),dimDates[Date]>_SoMonth && dimDates[Date]<=_EoMONTH),FILTER(ALL(Sub_DimDates[Date]),Sub_DimDates[Date]>_SoMonth && Sub_DimDates[Date]<=_EoMONTH))
		lineageTag: 9f53086d-9b32-41c2-b866-b42ebc0ffee5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Callout Customer Filter' =
			
			VAR _Lazy =[Lazy Customer Check or Decline]
			Var _Good = [Good Customer - Supply Date_backup]
			
			RETURN
			IF(ISBLANK(_Lazy) && ISBLANK(_Good),BLANK(),1)
		lineageTag: 1227c9a4-8349-44db-a078-48b360901c2f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch Diff' =
			
			[Quantity Dynamic Table Switch] - [Quantity Dynamic Table Switch LY FYvsYTD]
			
			--[Quantity Dynamic Table Switch LY YTD Visual]
		formatString: " #,#.##;(#,#.##)"
		displayFolder: Dynamic Table
		lineageTag: 9372945f-7584-472f-80b3-e87e7591bb23

		changedProperty = IsHidden

	measure 'Monthly Avg' =
			
			Var _date = CALCULATE(MAX(Sub_DimDates[Date]),FILTER(ALL(Sub_DimDates),Sub_DimDates[IsHistory]=1))
			Var _days = CALCULATE(SUM(Sub_DimDates[IsHistory]),FILTER(ALL(Sub_DimDates),YEAR(Sub_DimDates[Date])=YEAR(_date)))
			Var _qty = CALCULATE([Quantity Dynamic Table Switch],FILTER(ALL(Sub_DimDates),YEAR(Sub_DimDates[Date])=YEAR(_date)))
			
			RETURN
			DIVIDE(_qty,_days)*30
		lineageTag: 1adfe86f-cd0a-492a-a814-d22f10f64912

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Avg Last 3Month' =
			
			Var _date = CALCULATE(MAX(Sub_dimDates[Date]),Sub_dimDates[IsHistory]=1)
			VAR _date3months = DATE(YEAR(_date),MONTH(_date),DAY(_date)-90)
			Var _days = CALCULATE(SUM(Sub_dimDates[IsHistory]),FILTER(ALL(Sub_dimDates),Sub_dimDates[Date]<=_date && Sub_dimDates[Date]>=_date3months))
			Var _qty = CALCULATE([Quantity Dynamic Table Switch],FILTER(ALL(Sub_dimDates),Sub_dimDates[Date]<=_date && Sub_dimDates[Date]>=_date3months),REMOVEFILTERS(DimDates))
			
			RETURN
			DIVIDE(_qty,_days)*30
		lineageTag: 1a930027-eafe-4d95-98e0-2cc072ccf1ff

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Avg LY Full' =
			
			Var _date = CALCULATE(MAX(Sub_DimDates[Date]),FILTER(ALL(Sub_DimDates),Sub_DimDates[IsHistory]=1))
			Var _days = CALCULATE(SUM(Sub_DimDates[IsHistory]),FILTER(ALL(Sub_DimDates),YEAR(Sub_DimDates[Date])=YEAR(_date)-1))
			Var _qty = CALCULATE([Quantity Dynamic Table Switch LY No -],FILTER(ALL(Sub_DimDates),YEAR(Sub_DimDates[Date])=YEAR(_date)-1))
			
			RETURN
			DIVIDE(_qty,_days)*30
		formatString: #,0
		lineageTag: 22800a9e-8abb-47e0-99b4-7b987d2d6fd0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Quantity Dynamic Table Switch Current Month' =
			
			VAR _date = CALCULATE(MAX(dimDates[Date]),FILTER(ALL(dimDates),dimDates[IsHistory]=1))
			VAR _maxdate = EOMONTH(_date,0)
			VAR _mindate = EOMONTH(_date,-1)
			VAR _Measure = CALCULATE([Total Quantity],USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]),FILTER(ALL(Sub_DimDates),Sub_DimDates[Date]<=_maxdate && Sub_DimDates[Date]>=_mindate))
			
			 RETURN
			 IF(ISBLANK(_measure),"-",_measure)
		displayFolder: Dynamic Table
		lineageTag: b4dfe68a-19a7-4868-b0d0-7d99c4f3fb0a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch Next Month' =
			
			VAR _date = CALCULATE(MAX(dimDates[Date]),FILTER(ALL(dimDates),dimDates[IsHistory]=1))
			VAR _maxdate = EOMONTH(_date,1)
			VAR _mindate = EOMONTH(_date,0)
			VAR _Measure = CALCULATE([Total Quantity],USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]),FILTER(ALL(Sub_DimDates),Sub_DimDates[Date]<=_maxdate && Sub_DimDates[Date]>=_mindate))
			
			 RETURN
			 IF(ISBLANK(_measure),"-",_measure)
		displayFolder: Dynamic Table
		lineageTag: dd6e2fa3-80eb-4f35-aa21-120bc838d07e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch Previous Month' =
			
			VAR _date = CALCULATE(MAX(dimDates[Date]),FILTER(ALL(dimDates),dimDates[IsHistory]=1))
			VAR _maxdate = EOMONTH(_date,-1)
			VAR _mindate = EOMONTH(_date,-2)
			VAR _Measure = CALCULATE([Total Quantity],USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]),FILTER(ALL(Sub_DimDates),Sub_DimDates[Date]<=_maxdate && Sub_DimDates[Date]>=_mindate))
			
			 RETURN
			 IF(ISBLANK(_measure),"-",_measure)
		displayFolder: Dynamic Table
		lineageTag: ae6033c3-d6b0-4546-8a44-aa62c7241354

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch Next 2 Months' =
			
			VAR _date = CALCULATE(MAX(dimDates[Date]),FILTER(ALL(dimDates),dimDates[IsHistory]=1))
			VAR _maxdate = EOMONTH(_date,2)
			VAR _mindate = EOMONTH(_date,1)
			VAR _Measure = CALCULATE([Total Quantity],USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]),FILTER(ALL(Sub_DimDates),Sub_DimDates[Date]<=_maxdate && Sub_DimDates[Date]>=_mindate))
			
			 RETURN
			 IF(ISBLANK(_measure),"-",_measure)
		displayFolder: Dynamic Table
		lineageTag: 2298c62f-0f1c-4185-aab5-84e47c856518

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch Diff % LY' =
			
			Switch(TRUE(),
			HASONEVALUE(Sub_DimDates[MonthInCalendarName]),Blank(),
			Divide([Quantity Dynamic Table Switch] - [Quantity Dynamic Table Switch LY],[Quantity Dynamic Table Switch LY])
			)
		formatString: 0.0%;(0.0%);0.0%
		displayFolder: Dynamic Table\Column
		lineageTag: d85cdd73-f6f6-4385-8f46-109dafc0b337

		changedProperty = IsHidden

	measure 'Quantity Dynamic Table Switch Diff % 2Y' =
			
			Switch(TRUE(),
			HASONEVALUE(Sub_DimDates[MonthInCalendarName]),Blank(),
			Divide([Quantity Dynamic Table Switch] - [Quantity Dynamic Table Switch 2LY FYvsYTD], [Quantity Dynamic Table Switch 2LY FYvsYTD])
			--[Quantity Dynamic Table Switch 2Y],[Quantity Dynamic Table Switch 2Y])
			)
		formatString: 0.0%;(0.0%);0.0%
		displayFolder: Dynamic Table\Column
		lineageTag: 30e7aeeb-a342-4ad6-886b-755a44b6cf96

		changedProperty = IsHidden

	measure 'Quantity Dynamic Table Switch Diff % 2Y YTD' =
			
			Switch(TRUE(),
			HASONEVALUE(Sub_DimDates[MonthInCalendarName]),Blank(),
			Divide([Quantity Dynamic Table Switch] - [Quantity Dynamic Table Switch 2Y YTD],[Quantity Dynamic Table Switch 2Y YTD])
			)
		formatString: 0.0%;(0.0%);0.0%
		displayFolder: Dynamic Table\Column
		lineageTag: 57000ee5-4e1e-42ba-8c97-91f3700ef94e

		changedProperty = IsHidden

	measure 'Quantity Dynamic Table Switch Previous 2 Months' =
			
			VAR _date = CALCULATE(MAX(dimDates[Date]),FILTER(ALL(dimDates),dimDates[IsHistory]=1))
			VAR _maxdate = EOMONTH(_date,-2)
			VAR _mindate = EOMONTH(_date,-3)
			VAR _Measure = CALCULATE([Total Quantity],USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]),FILTER(ALL(Sub_DimDates),Sub_DimDates[Date]<=_maxdate && Sub_DimDates[Date]>=_mindate))
			
			 RETURN
			 IF(ISBLANK(_measure),"-",_measure)
		displayFolder: Dynamic Table
		lineageTag: bb431db3-b0ec-4075-b5c6-deb4e6e48566

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch Next 3 Months' =
			
			VAR _date = CALCULATE(MAX(dimDates[Date]),FILTER(ALL(dimDates),dimDates[IsHistory]=1))
			VAR _maxdate = EOMONTH(_date,3)
			VAR _mindate = EOMONTH(_date,2)
			VAR _Measure = CALCULATE([Total Quantity],USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה]),FILTER(ALL(Sub_DimDates),Sub_DimDates[Date]<=_maxdate && Sub_DimDates[Date]>=_mindate))
			
			 RETURN
			 IF(ISBLANK(_measure),"-",_measure)
		displayFolder: Dynamic Table
		lineageTag: b40ffa4b-0346-4e7a-bb69-4d6a95eec284

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Open Price Supply Date Switch' =
			
			SWITCH(MIN(PriceType[ID]),
			1,CALCULATE([Avg Unit Price By Supply Date],factOrders[סטטוס] = 1 || factOrders[סטטוס] = 2),
			2,CALCULATE([Avg CF Price By Supply Date],factOrders[סטטוס] = 1 || factOrders[סטטוס] = 2),
			3,CALCULATE([Avg FOT Price By Supply Date],factOrders[סטטוס] = 1 || factOrders[סטטוס] = 2),
			CALCULATE([Avg Unit Price By Supply Date],factOrders[סטטוס] = 1 || factOrders[סטטוס] = 2)
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ce1d4061-fb83-4b45-9af7-ab99a743cd51

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Open Orders Quantity By Supply Date -' =
			
			VAR _MinO = CALCULATE(MIN(factOrders[תאריך אספקה]),ALL(dimDates),ALL(Sub_DimDates),factOrders[סטטוס]=1 || factOrders[סטטוס]=2)
			VAR _MaxO = CALCULATE(MAX(factOrders[תאריך אספקה]),ALL(dimDates),ALL(Sub_DimDates),factOrders[סטטוס]=1 || factOrders[סטטוס]=2)
			VAR _MinP = CALCULATE(MIN(factPurchaseOrder[Supply Date]),ALL(dimDates),ALL(Sub_DimDates),factPurchaseOrder[IsOpen]="1")
			VAR _MaxP = CALCULATE(MAX(factPurchaseOrder[Supply Date]),ALL(dimDates),ALL(Sub_DimDates),factPurchaseOrder[IsOpen]="1")
			VAR _Min = IF(_MinO<=_MinP,_MinO,_MinP)
			VAR _Max = IF(_MaxO>=_MaxP,_MaxO,_MaxP)
			
			RETURN
			SWITCH(TRUE(),
			MAX(DimDates[Date]) <_Min,BLANK(),
			MIN(DimDates[Date]) > _Max,BLANK(),
			ISBLANK([Open Orders Quantity By Supply Date]),"-",
			[Open Orders Quantity By Supply Date]
			)
		lineageTag: fc80bce9-a36e-44e8-8ecc-f83847056f92

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Open Orders Quantity Flat' = CALCULATE([Total Quantity Flat],factOrders[סטטוס]=1) +  [Total Quantity Left]
		lineageTag: 4225b422-d212-4c62-bc5a-f5425af95436

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Quantity Flat' = SUM('factOrders'[FlatQTY])
		displayFolder: כמויות
		lineageTag: 7a33bf7c-899c-4dfe-9b8e-5650d1004b44

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Quantity Basis' = SUM('factOrders'[BasisQTY])
		displayFolder: כמויות
		lineageTag: 2ddccb1a-64ab-46be-a72c-7e3ddeba4590

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Open Orders Quantity Basis' = CALCULATE([Total Quantity Basis],factOrders[סטטוס]=1)
		lineageTag: 286fab93-b8e9-407b-950a-34136111f8a7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Open Orders Quantity Basis By Supply Date' =
			
			
			CALCULATE([Open Orders Quantity Basis]
			,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			)
		lineageTag: ad50f908-1e3a-4b21-96c5-aee661a31fa8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Open Orders Quantity Flat By Supply Date' =
			
			
			CALCULATE([Open Orders Quantity Flat]
			,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			)
		lineageTag: 77c13d8e-e05c-419a-9590-cce966163cf8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales - Risk Plan Basis' = ```
			
			VAR _MaxDate = CALCULATE(MAX(factOrders[תאריך אספקה]),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה]))
			VAR MinDate = MIN(dimDates[Date])
			VAR _ALLMinDate = CALCULATE(MIN(dimDates[Date]),ALL(dimDates))
			var allOpenChosenMonth = 
			CALCULATE(
			    [Open Orders Quantity Basis By Supply Date]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate && dimDates[Date]>=MinDate)
			)
			VAR _OLDOpenOrders = 
			CALCULATE(
			    [Open Orders Quantity Basis By Supply Date]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate && dimDates[Date]>=_ALLMinDate)
			)
			return 
			IF(MAX(dimDates[Show Months])="This Month",_OLDOpenOrders,allOpenChosenMonth)
			```
		lineageTag: 024d3b9d-0aa0-4e81-aca9-a67b16cf2778

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales - Risk Plan Flat' = ```
			
			VAR _MaxDate = CALCULATE(MAX(factOrders[תאריך אספקה]),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה]))
			VAR MinDate = MIN(dimDates[Date])
			VAR _ALLMinDate = CALCULATE(MIN(dimDates[Date]),ALL(dimDates))
			var allOpenChosenMonth = 
			CALCULATE(
			    [Open Orders Quantity Flat By Supply Date]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate && dimDates[Date]>=MinDate)
			)
			VAR _OLDOpenOrders = 
			CALCULATE(
			    [Open Orders Quantity Flat By Supply Date]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate && dimDates[Date]>=_ALLMinDate)
			)
			return 
			IF(MAX(dimDates[Show Months])="This Month",_OLDOpenOrders,allOpenChosenMonth)
			```
		lineageTag: 90fe3e41-6513-4028-be02-20ab5187f6d1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch Measures Show - Basis' =
			
			IF(HASONEVALUE(dimItemsSimple[Article_Description]),
			    SWITCH(MAX(SwitchMeasure[ID]),
			    1,[Stock - Risk Plan Basis],
			    2,[Purchase - Risk Plan Basis],
			    3,[Sales - Risk Plan Basis],
			    4,[Remain - Risk Plan Basis],
			    BLANK())
			,
			    SWITCH(MAX(SwitchMeasure[ID]),
			    1,CALCULATE([Stock - Risk Plan Basis],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    2,CALCULATE([Purchase - Risk Plan Basis],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    3,CALCULATE([Sales - Risk Plan Basis],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    4,CALCULATE([Remain - Risk Plan Basis],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    BLANK()))
		formatString: #,0
		lineageTag: 1d8f43c2-5e88-416e-b2d6-1b2503f521c3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Switch Measures Show - Flat' =
			
			IF(HASONEVALUE(dimItemsSimple[Article_Description]),
			    SWITCH(MAX(SwitchMeasure[ID]),
			    1,[Stock - Risk Plan Flat],
			    2,[Purchase - Risk Plan Flat],
			    3,[Sales - Risk Plan Flat],
			    4,[Remain - Risk Plan Flat],
			    BLANK())
			,
			    SWITCH(MAX(SwitchMeasure[ID]),
			    1,CALCULATE([Stock - Risk Plan Flat],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    2,CALCULATE([Purchase - Risk Plan Flat],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    3,CALCULATE([Sales - Risk Plan Flat],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    4,CALCULATE([Remain - Risk Plan Flat],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    BLANK()))
		formatString: #,0
		lineageTag: 7f6210cd-4770-4363-9d0b-026d33751344

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Stock - Risk Plan Basis' =
			
			IF(MAX(dimDates[Show Months])="This Month",0,
			
			            CALCULATE([Remain - Risk Plan Basis],DATEADD(dimDates[Date],-1,MONTH))
			    )
		displayFolder: Risk Plan
		lineageTag: efc4d5c0-3cdb-4338-94bb-eb450869bfe0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Stock - Risk Plan Flat' =
			
			[Stock - Risk Plan] - [Stock - Risk Plan Basis]
		displayFolder: Risk Plan
		lineageTag: 52fc16e3-d77a-4396-9393-f2f94bd7e125

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Remain - Risk Plan Basis' = ```
			
			VAR LastUpdated=CALCULATE(MAX(factInventory[Date]),ALL(factInventory))
			return 
			0 + [All Open Purchase Basis By Supply Date - Risk Plan] - [All Open Orders Basis By Supply Date - Risk Plan]
			
			```
		displayFolder: Risk Plan
		lineageTag: b43abf5b-c5df-45cb-8590-27727425808e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'All Open Orders Basis By Supply Date - Risk Plan' =
			
			VAR _MaxDate = MAX(dimDates[Date])
			VAR MinDate = MIN(dimDates[Date])
			VAR _ALLMinDate = CALCULATE(MIN(dimDates[Date]),ALL(dimDates))
			return
			CALCULATE(
			    [Open Orders Quantity Basis By Supply Date]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			)
		displayFolder: Risk Plan
		lineageTag: 9224f496-3797-4d94-b2e9-ec0617b375a4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Remain - Risk Plan Flat' = ```
			
			VAR LastUpdated=CALCULATE(MAX(factInventory[Date]),ALL(factInventory))
			var StockCurrentMonth = CALCULATE(CALCULATE(SUM(factInventory[Quantity]),factInventory[Date]=LastUpdated),ALL(dimDates))
			
			return 
			StockCurrentMonth + [All Open Purchase Flat By Supply Date - Risk Plan] - [All Open Orders Flat By Supply Date - Risk Plan]
			
			```
		displayFolder: Risk Plan
		lineageTag: 76c2e0fb-9e79-40e1-aef5-61680425a210

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'All Open Orders Flat By Supply Date - Risk Plan' = ```
			
			VAR _MaxDate = MAX(dimDates[Date])
			VAR MinDate = MIN(dimDates[Date])
			VAR _ALLMinDate = CALCULATE(MIN(dimDates[Date]),ALL(dimDates))
			return
			CALCULATE(
			    [Open Orders Quantity Flat By Supply Date]
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			)
			
			```
		displayFolder: Risk Plan
		lineageTag: 32c53d7a-d5a3-48fa-bf25-d5c393ed0640

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Avg 2Y FY' =
			
			Var _date = CALCULATE(MAX(Sub_DimDates[Date]),FILTER(ALL(Sub_DimDates),Sub_DimDates[IsHistory]=1))
			Var _days = CALCULATE(SUM(Sub_DimDates[IsHistory]),FILTER(ALL(Sub_DimDates),YEAR(Sub_DimDates[Date])=YEAR(_date)-1))
			Var _qty = CALCULATE([Quantity Dynamic Table Switch 2Y])--, FILTER(ALL(Sub_DimDates),YEAR(Sub_DimDates[Date])=YEAR(_date)-1))
			
			RETURN
			DIVIDE(_qty,_days)*30
		lineageTag: 6792db2f-9af9-46f8-8d00-d4911a78b524

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Avg 2Y YTD' =
			
			Var _date = CALCULATE(MAX(Sub_DimDates[Date]),FILTER(ALL(Sub_DimDates),Sub_DimDates[IsHistory]=1))
			Var _days = CALCULATE(SUM(Sub_DimDates[IsHistory]),FILTER(ALL(Sub_DimDates),YEAR(Sub_DimDates[Date])=YEAR(_date)-1))
			Var _qty = CALCULATE([Quantity Dynamic Table Switch 2Y YTD])--,FILTER(ALL(Sub_DimDates),YEAR(Sub_DimDates[Date])=YEAR(_date)-1))
			
			RETURN
			DIVIDE(_qty,_days)*30
		lineageTag: 067d1f23-14ba-475e-9d5b-7c78204d1a47

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Sales Price Flat' =
			
			DIVIDE([Total Sales Flat Switch] , [Total Quantity Flat])
			--DIVIDE([Total Sales Flat] , [Total Quantity Flat])--[Open Orders Quantity Flat])
		lineageTag: ab95a85e-8a50-436d-8a4b-8e22ea0a6dd9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Sales Price Flat By Supply Date' =
			
			
			CALCULATE([AVG Sales Price Flat]
			,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			)
		lineageTag: 6ff3ef0b-7bf2-486e-8bea-6c1e6906ec8a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Sales Price Basis Flat Value' =
			
			--DIVIDE([Total Sales Flat Value] , [Open Orders Quantity Basis])
			DIVIDE([Total Sales Flat Value Switch] , [Open Orders Quantity Basis])
		lineageTag: c80f349f-9ce1-47a2-b75c-03d928bbba23

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Sales Price Basis Flat Value By Supply Date' =
			
			
			CALCULATE([Avg Sales Price Basis Flat Value]
			,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			)
		lineageTag: 112aa844-f660-456b-8147-981f4223898c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch Measures Price - Flat' =
			
			//SWITCH(TRUE(),
			//ISINSCOPE(dimDates[MonthInCalendarName]),
			//,
			IF(HASONEVALUE(dimItemsSimple[Article_Description]),
			    SWITCH(MAX(SwitchMeasure[ID]),
			    1,[Stock Price - Risk Plan Flat],
			    2,[Avg Cost Price Supply Date - Risk Plan Flat],
			    3,[AVG Sales Price Flat - FirstMonth],--[AVG Price FlatValue Supply Date Switch],--[AVG Price - Risk Plan Flat],
			    4,[Remain Price - Risk Plan Flat],
			    BLANK()
			    )
			,
			    SWITCH(MAX(SwitchMeasure[ID]),
			    1,CALCULATE([Stock Price - Risk Plan],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    2,CALCULATE([Avg Cost Price Supply Date - Risk Plan Flat],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    3,CALCULATE([AVG Sales Price Flat - FirstMonth],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    4,CALCULATE([Remain Price - Risk Plan Flat],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    BLANK()))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ec31c41b-a880-41ba-a441-658edd89d474

		changedProperty = IsHidden

	measure 'Switch Measures Price - Flat Value' =
			
			//SWITCH(TRUE(),
			//ISINSCOPE(dimDates[MonthInCalendarName]),
			//,
			IF(HASONEVALUE(dimItemsSimple[Article_Description]),
			    SWITCH(MAX(SwitchMeasure[ID]),
			    1,[Stock Price - Risk Plan Basis],
			    2,[Avg Cost Price Supply Date - Risk Plan Flat Value],
			    3,[AVG Price - Risk Plan Basis Flat Value],
			    4,[Remain Price - Risk Plan Basis],
			    BLANK()
			    )
			,
			    SWITCH(MAX(SwitchMeasure[ID]),
			    1,CALCULATE([Stock Price - Risk Plan],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    2,CALCULATE([Avg Cost Price Supply Date - Risk Plan Flat Value],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    3,CALCULATE([AVG Price - Risk Plan Basis Flat Value],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    4,CALCULATE([Remain Price - Risk Plan Basis],FILTER(dimItemsSimple,dimItemsSimple[Article_Description]="Corn")),
			    BLANK()))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ced6099a-bbbe-4145-9841-d1dccb72df02

		changedProperty = IsHidden

	measure 'Remain Price - Risk Plan Flat' =
			
			VAR LastUpdated=CALCULATE(MAX(factInventory[Date]),ALL(factInventory))
			var StockCostCurrentMonth = CALCULATE(CALCULATE([Inventory Value Switch],factInventory[Date]=LastUpdated),ALL(dimDates))
			var StockQtyCurrentMonth = CALCULATE(CALCULATE([Inventory Balance - Quantity],factInventory[Date]=LastUpdated),ALL(dimDates))
			VAR _MaxDate = MAX(dimDates[Date])
			var _Quantity = CALCULATE(
			    CALCULATE(SUM(factPurchaseOrder[FlatQTY]),factPurchaseOrder[IsOpen]="1",USERELATIONSHIP(dimDates[Date],factPurchaseOrder[Supply Date]))
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate),USERELATIONSHIP(dimDates[Date],factPurchaseOrder[Supply Date]))
			VAR _Positive = DIVIDE( StockCostCurrentMonth+[All Open Purchase Cost By Supply Date - Risk Plan Flat],StockQtyCurrentMonth+_Quantity,BLANK())
			
			return
			IF([Remain - Risk Plan Flat] >=0 ,_Positive,[AVG Sales Price Flat - FirstMonth]
			)
		displayFolder: Risk Plan
		lineageTag: f76ec66d-eb85-460a-95a0-6408c41d7a9f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Price - Risk Plan Basis Flat Value' =
			
			ROUND(
			    SWITCH(TRUE(),
			    ISBLANK([Sales - Risk Plan Basis]) && [Purchase - Risk Plan Basis] <> BLANK(),
			        [Avg Cost Price Basis Flat Value Supply Date],
			    ISBLANK([Sales - Risk Plan Basis]) && ISBLANK([Purchase - Risk Plan Basis]),
			        BLANK(),
			        [Avg Sales Balance Price Basis Flat Value By Supply Date] --[Avg Sales Price Basis Flat Value By Supply Date]
			    )
			,0)
		displayFolder: Risk Plan
		lineageTag: 427fe8e8-a92d-42b6-9108-30a249822574

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Supply DynamicTable LY YTD' = ```
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-1
			RETURN
			CALCULATE(
			    CALCULATE(
			        [Total Quantity Supply TO DATE],
			        Sub_DimDates[Year]=_YEAR,
			        DATEADD(Sub_DimDates[Date],-1,YEAR),
			        DATEADD(DimDates[Date],-1,YEAR)
			        
			    )
			,dimDates[IsHistory]=1
			)
			
			```
		displayFolder: Dynamic Table
		lineageTag: 1204eeb2-56e1-4b69-9acb-12bd058b0850

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Supply DynamicTable 2Y YTD' =
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-2
			RETURN
			CALCULATE(
			    CALCULATE(
			        [Total Quantity Supply TO DATE],
			        Sub_DimDates[Year]=_YEAR,
			        DATEADD(Sub_DimDates[Date],-2,YEAR),
			        DATEADD(DimDates[Date],-2,YEAR)
			    )
			,dimDates[IsHistory]=1
			)
		displayFolder: Dynamic Table
		lineageTag: 04a44f4e-94b0-4300-830c-5dc78f1dd8fb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales USD CF FlatValue' =
			
			SUM('factOrders'[LineTotalFlatValueCFFUSD])
		displayFolder: CF
		lineageTag: d73c211e-00d6-4448-b7e0-b5fcd8998f78

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales CF FlatValue' = ```
			
			    SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        --1,[Total Sales NIS CF],
			        2,[Total Sales USD CF FlatValue],
			   [Total Sales USD CF FlatValue])
			```
		displayFolder: CF
		lineageTag: ba31b045-7bd1-40ec-a2c1-d223403a6ed6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg CF Price FlatValue By Supply Date' =
			
			CALCULATE(DIVIDE([Total Sales CF FlatValue],[Total Quantity]),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה]))
		displayFolder: CF
		lineageTag: c47c37bb-1b4e-4ad3-bc70-00838bafbe2e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales USD FOT FlatValue' =
			
			SUM('factOrders'[LineTotalFlatValueFOTUSD])
		displayFolder: FOT
		lineageTag: b35230aa-e7dc-4680-a241-0fa30d894d66

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales FOT FlatValue' = ```
			
			    SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			       --1,[Total Sales NIS FOT],
			        2,[Total Sales USD FOT FlatValue],
			   [Total Sales USD FOT FlatValue])
			```
		displayFolder: FOT
		lineageTag: a3d60cc1-b63e-433a-813d-bf1e3f8020a5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg FOT Price FlatValue By Supply Date' =
			
			CALCULATE(DIVIDE([Total Sales FOT FlatValue],[Total Quantity]),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה]))
		displayFolder: FOT
		lineageTag: b48c39b9-e313-403d-9c30-1fcd718bd1fe

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales Flat Value Switch' =
			
			SWITCH(MIN(PriceType[ID]),
			1,SUM(factOrders[LineTotalFlatValueBalanceUSD]),
			2,SUM(factOrders[LineTotalFlatValueBalanceCFFUSD]),
			3,SUM(factOrders[LineTotalFlatValueBalanceFOTUSD]),
			SUM(factOrders[LineTotalFlatValueBalanceUSD]))
			   --SUM(factOrders[LineTotalFlatBalanceUSD])))
		lineageTag: 50216ff7-cf89-42c2-803f-647d6ed483f9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales Flat Switch' =
			
			SWITCH(MIN(PriceType[ID]),
			1,SUM(factOrders[LineTotalFlatUSD]),--SUM(factOrders[LineTotalFlatBalanceUSD]),
			2,SUM(factOrders[LineTotalCF_USD]),
			3,SUM(factOrders[LineTotalFOT_USD]),
			SUM(factOrders[LineTotalFlatUSD]))
		lineageTag: 901ae0ed-52e7-4f0e-996f-122679a27d28

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales Flat + FlatValue Switch' =
			
			SWITCH(MIN(PriceType[ID]),
			1,SUM(factOrders[LineTotalFlatValueUSD]),
			2,SUM(factOrders[LineTotalFlatValueCFFUSD]),
			3,SUM(factOrders[LineTotalFlatValueFOTUSD]),
			SUM(factOrders[LineTotalFlatValueUSD]))
		lineageTag: 91484611-25ac-42f0-a9d7-74c082d312fa

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Remain Price - Risk Plan Basis' =
			
			--VAR LastUpdated=CALCULATE(MAX(factInventory[Date]),ALL(factInventory))
			--var StockCostCurrentMonth = CALCULATE(CALCULATE([Inventory Value Switch],factInventory[Date]=LastUpdated),ALL(dimDates))
			--var StockQtyCurrentMonth = CALCULATE(CALCULATE([Inventory Balance - Quantity],factInventory[Date]=LastUpdated),ALL(dimDates))
			VAR _MaxDate = MAX(dimDates[Date])
			var _Quantity = --[All Open Purchase Basis By Supply Date - Risk Plan] - [All Open Orders Basis By Supply Date - Risk Plan]
			CALCULATE(
			    CALCULATE(SUM(factPurchaseOrder[BasisQTY]),factPurchaseOrder[IsOpen]="1",USERELATIONSHIP(dimDates[Date],factPurchaseOrder[Supply Date]))
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate),USERELATIONSHIP(dimDates[Date],factPurchaseOrder[Supply Date]))
			VAR _Positive = DIVIDE( [All Open Purchase Cost By Supply Date - Risk Plan Flat Value],_Quantity,BLANK())
			
			return
			IF([Remain - Risk Plan Basis] >=0 ,_Positive,[AVG Price - Risk Plan Basis Flat Value]--[Avg Sales Price Basis Flat Value By Supply Date]
			)
		displayFolder: Risk Plan
		lineageTag: dcc2d6fc-054b-4e68-8bb0-f9046f1f6f10

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Stock Price - Risk Plan Basis' =
			
			IF(MAX(dimDates[Show Months])="This Month",0,
			CALCULATE([Remain Price - Risk Plan Basis],
			            DATEADD(dimDates[Date],-1,MONTH
			            )
			
			))
		displayFolder: Risk Plan
		lineageTag: 1145a348-c8b0-4bf1-9e32-1d60f5acf586

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Stock Price - Risk Plan Flat' = ```
			
			IF(MAX(dimDates[Show Months])="This Month",
			    [Inventory Avg Value Switch],
			    --[Stock Price calculated Flat]
			    CALCULATE([Remain Price - Risk Plan Flat],DATEADD(dimDates[Date],-1,MONTH))
			)
			
			```
		displayFolder: Risk Plan
		lineageTag: 90981de0-94ca-488b-ba01-35fa52bc3922

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Sales Price Flat+FlatValue' =
			
			DIVIDE([Total Sales Flat + FlatValue Switch] , [Total Quantity])
		lineageTag: 64cd5726-b898-47a7-a592-48449ddc6aeb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales Flat + FlatValue Balance Switch' =
			
			SWITCH(MIN(PriceType[ID]),
			1,SUM(factOrders[LineTotalFlatValueBalanceUSD]),
			2,SUM(factOrders[LineTotalFlatValueBalanceCFFUSD]),
			3,SUM(factOrders[LineTotalFlatValueBalanceFOTUSD]),
			SUM(factOrders[LineTotalFlatValueBalanceUSD]))
		lineageTag: 121c51fb-0896-4fd1-93c8-663c6e98c137

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Table Switch LY FYvsYTD' =
			
			SWITCH(MIN(SwitchTable_LYvsLYYTD[ID]),
			1,[Quantity Dynamic Table Switch LY],
			2,[Quantity Dynamic Table Switch LY YTD Visual]
			)
		formatString: #,0
		displayFolder: Dynamic Table
		lineageTag: a4d1e17f-5739-4e36-a139-91a31a02c0ff

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Quantity Dynamic Table Switch 2LY FYvsYTD' =
			
			SWITCH(MIN(SwitchTable_LYvsLYYTD[ID]),
			1,[Quantity Dynamic Table Switch 2Y],
			2,[Quantity Dynamic Table Switch 2Y YTD]
			)
		formatString: #,0
		displayFolder: Dynamic Table
		lineageTag: 4e72b4dc-5a4e-43eb-a441-0287ba69ce7e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Quantity Supply Date_v1' =
			CALCULATE([Total Quantity]
			                  ,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			                  ,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			                )
		lineageTag: 4c88655a-dcff-4f6f-b33d-ccc8ad6d267c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Good Customer - Supply Date - 6 Out 12' = ```
			
			VAR _Date = CALCULATE(MAX(dimDates[Date]),ALL(dimDates),dimDates[IsHistory]=1)
			VAR _EOdate = EOMONTH(_Date,0)
			VAR _L12M = CALCULATE(
			            CALCULATE(MAX(dimDates[FirstDayOfMonth])  
			                        ,DATEADD(dimDates[Date],-12,MONTH)
			                     )
			                    ,dimDates[IsHistory]=1
			                    )
			--EDATE(_EOdate, -6)
			VAR _Months =
			    CALCULATETABLE(
			        VALUES(dimDates[FirstDayOfMonth]),
			        dimDates[FirstDayOfMonth] >= _L12M,
			        dimDates[FirstDayOfMonth] <= _EOdate,
			        dimDates[IsHistory] = 1
			    )
			VAR _ActiveMonthCount =
			    SUMX(
			        _Months,
			        // For each month from the _Months table, use the column name [FirstDayOfMonth] as the current month.
			        VAR CurrentMonth = [FirstDayOfMonth]
			        VAR _StartOfMonth = CurrentMonth
			        VAR _EndOfMonth = EOMONTH(CurrentMonth, 0)
			        VAR Qty =
			            CALCULATE(
			                [Total Quantity Supply Date_v1],
			                ALL(dimDates),
			                dimDates[Date] >= _StartOfMonth,
			                dimDates[Date] <= _EndOfMonth
			            )
			        RETURN IF(NOT(ISBLANK(Qty)) && Qty <> 0, 1, 0)
			    )
			RETURN
			        IF(_ActiveMonthCount >=6, 1, 0)
			```
		formatString: 0
		lineageTag: d20b4b1d-4e51-4676-8b69-b34ab430c1d3

		changedProperty = IsHidden

	measure 'Good Customer - Avg Quantity Last 12 Months' =
			
			VAR _Date =
			    CALCULATE(
			        MAX(dimDates[Date]),
			        ALL(dimDates),
			        dimDates[IsHistory] = 1
			    )
			VAR SumQty12 =
			    CALCULATE(
			        [Total Quantity Supply Date_v1],
			        -- Use DATESINPERIOD to restrict to the last 12 months,
			        -- anchored by the current max date in your context.
			        DATESINPERIOD(
			            dimDates[Date],
			            _Date,
			            -12,
			            MONTH
			        )
			    )
			VAR ActiveMonthCount12 =
			    CALCULATE(
			        DISTINCTCOUNT(dimDates[FirstDayOfMonth]),
			        -- Same 12-month window
			        DATESINPERIOD(
			            dimDates[Date],
			            _Date,
			            -12,
			            MONTH
			        ),
			        -- Keep only months where quantity is > 0
			        -- (or you can use [Total Quantity Supply Date_v1] <> BLANK)
			        KEEPFILTERS(
			            FILTER(
			                ALL(dimDates),
			                [Total Quantity Supply Date_v1] > 0
			            )
			        )
			    )
			RETURN
			    DIVIDE(SumQty12, ActiveMonthCount12)
		formatString: #,0
		lineageTag: 5ddaf5ce-0f01-4ad5-a743-10ad73cf898a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Good Customer - Supply Date' =
			
			Var _4out9 = [Good Customer - Supply Date - 6 Out 12]
			Var _3Out6 = [Good Customer - Supply Date - 3 Out 6]
			Var _date = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			Var _OpenOrder = [Open Orders Quantity By Supply Date]
			Var _MonthlyAVG = [Good Customer - Avg Quantity Last 12 Months]
			
			RETURN
			SWITCH(TRUE(),
			ISBLANK(_OpenOrder),
			    _3Out6+_4out9,
			_OpenOrder<=_MonthlyAVG*1.5,
			        _3Out6 + _4out9,
			BLANK()
			)
		formatString: 0
		lineageTag: 0cdeeb6d-88a1-4f8b-9fe7-d6a2f78a7e09

		changedProperty = IsHidden

	measure 'Good Customer - 3Months Forecast' =
			
			VAR _Date =
			    CALCULATE(
			        MAX(dimDates[Date]),
			        ALL(dimDates),
			        dimDates[IsHistory] = 1
			    )
			VAR _CurrMonth =
			    DATE( YEAR(_Date), MONTH(_Date), 1 )
			
			// Your 12‑month average, cleared of Sub_dimDates filters
			VAR _Avg12 =
			    CALCULATE(
			        [Good Customer - Avg Quantity Last 12 Months],
			        ALL(Sub_dimDates)
			    )
			
			// The month of the current cell in the matrix
			VAR _CellMonth =
			    MAX( Sub_dimDates[FirstDayOfMonth] )
			
			// Quantity in that cell’s month
			VAR _CellQty =
			    CALCULATE(
			        [Total Quantity Supply Date_v1],
			        ALL(dimDates),
			        dimDates[Date] >= _CellMonth,
			        dimDates[Date] <= EOMONTH(_CellMonth, 0)
			    )
			
			// Offset in months between the real current month and the cell’s month
			VAR _Offset =
			    DATEDIFF( _CurrMonth, _CellMonth, MONTH )
			
			RETURN
			SWITCH(
			    TRUE(),
			    // Three months before current: actual quantity (even if zero)
			    _Offset = -3,  _CellQty,
			    _Offset = -2,  _CellQty,
			    _Offset = -1,  _CellQty,
			
			    // Current month: actual if >0, otherwise average
			    _Offset = 0 && _CellQty > 0,  _CellQty,
			    _Offset = 0,                   _Avg12,
			
			    // Next month or the month after: average
			    _Offset = 1 || _Offset = 2,   _Avg12,
			
			    // All other months: blank
			    BLANK()
			)
		formatString: 0
		lineageTag: 504bc8a4-a72e-4a8b-a57e-6e6effb51e0d

		changedProperty = IsHidden

	measure 'Good Customer - Quantity Supply Table' =
			
			VAR _Date =
			    CALCULATE(
			        MAX(dimDates[Date]),
			        ALL(dimDates),
			        dimDates[IsHistory] = 1
			    )
			VAR _CurrMonth =
			    DATE( YEAR(_Date), MONTH(_Date), 1 )
			
			// Your 12‑month average, cleared of Sub_dimDates filters
			VAR _Avg12 =
			    CALCULATE(
			        [Good Customer - Avg Quantity Last 12 Months],
			        ALL(Sub_dimDates)
			    )
			
			// The month of the current cell in the matrix
			VAR _CellMonth =
			    MAX( Sub_dimDates[FirstDayOfMonth] )
			
			// Quantity in that cell’s month
			VAR _CellQty =
			    CALCULATE(
			        [Total Quantity Supply Date_v1],
			        ALL(dimDates),
			        ALL(Sub_DimDates),
			        dimDates[Date] >= _CellMonth,
			        dimDates[Date] <= EOMONTH(_CellMonth, 0)
			    )
			
			// Offset in months between the real current month and the cell’s month
			VAR _Offset =
			    DATEDIFF( _CurrMonth, _CellMonth, MONTH )
			
			RETURN
			IF(
			    // Check if we are in the context of a specific month; if so, run our SWITCH logic
			    ISINSCOPE(Sub_DimDates[MonthInCalendarName]),
			    SWITCH(
			        TRUE(),
			        _Offset = -2, _CellQty,
			        _Offset = -1, _CellQty,
			        _Offset =  0, _CellQty,
			        _Offset =  1, _CellQty,
			        _Offset =  2, _CellQty,
			        BLANK()  // For any other cases, return BLANK
			    ),
			    // Otherwise (total column), return the average for the past 12 months
			    _Avg12
			)
		lineageTag: e2ce185b-325d-4f73-84bd-238d079b1388

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Recomended Supply Date' =
			
			VAR _maxDate = MAX(factOrders[תאריך אספקה])
			VAR _RecomendedMonth = DATE(YEAR(_maxDate),MONTH(_maxDate)+1,1)
			VAR _currentMonth = DATE(YEAR(TODAY()), MONTH(TODAY()), 1)
			VAR _dateToShow = IF(_maxDate < _currentMonth, _currentMonth, _RecomendedMonth)
			RETURN
			    FORMAT(_dateToShow, "MMM yy")
		lineageTag: 79ab5330-ca0b-4e92-a796-0c7f4642b857

		changedProperty = IsHidden

	measure 'InactiveCustomer - Orders Supply Date Flag YTD vs LY YTD' =
			
			VAR LastPeriod = [Quantity Supply Date DynamicTable]
			VAR PrevPeriod = [Quantity Supply DynamicTable LY YTD]
			// % decrease from prev to last
			VAR DecreasePct =
			    DIVIDE( PrevPeriod - LastPeriod, PrevPeriod )
			
			// detect the “no data” scenario
			VAR HasData =
			    NOT( ISBLANK( LastPeriod ) || ISBLANK( PrevPeriod ) )
			
			RETURN
			    IF(
			        NOT HasData,
			        BLANK(),                     // no data → blank
			        IF(
			            PrevPeriod > 0
			            && DecreasePct > 0.30,   // drop > 30%
			            1,
			            0
			        )
			    )
			    --IF(TotalSalesThisYear = 0 && TotalSalesParallelPeriod > 0, 1, 0)
			    --DIVIDE(TotalSalesLast90-TotalSalesPrev90,TotalSalesPrev90)
			    --TotalSalesLast90-TotalSalesPrev90
			    --TotalSalesLast90
			    --TotalSalesPrev90
		formatString: 0
		lineageTag: 914f2fdc-3777-4bc2-990e-35e9be4e67d2

		changedProperty = IsHidden

	measure 'InactiveCustomer - Orders Supply Date Flag YTD vs LY YTD ---- diff' =
			
			VAR TotalSalesThisYear = [Quantity Supply Date DynamicTable]
			VAR TotalSalesParallelPeriod = [Quantity Supply DynamicTable LY YTD]
			
			RETURN
			    --IF(TotalSalesThisYear = 0 && TotalSalesParallelPeriod > 0, 1, 0)
			    --DIVIDE(TotalSalesLast90-TotalSalesPrev90,TotalSalesPrev90)
			    TotalSalesThisYear-TotalSalesParallelPeriod
			    --TotalSalesLast90
			    --TotalSalesPrev90
		formatString: #,0
		lineageTag: 3ed5b38c-aede-42a8-b552-f5a17dee7b6f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'InactiveCustomer - Orders Supply Date Flag YTD vs LY YTD ---- closePeriod' = ```
			
			VAR TotalSalesThisYear = [Quantity Supply Date DynamicTable]
			VAR TotalSalesParallelPeriod = [Quantity Supply DynamicTable LY YTD]
			
			RETURN
			    TotalSalesThisYear
			
			```
		formatString: #,0
		lineageTag: b243f350-52f3-4674-89a1-73f822568d09

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'InactiveCustomer - Orders Supply Date Flag YTD vs LY YTD ---- ParallelPeriod' =
			
			VAR TotalSalesThisYear = [Quantity Supply Date DynamicTable]
			VAR TotalSalesParallelPeriod = [Quantity Supply DynamicTable LY YTD]
			
			RETURN
			    --IF(TotalSalesThisYear = 0 && TotalSalesParallelPeriod > 0, 1, 0)
			    --DIVIDE(TotalSalesLast90-TotalSalesPrev90,TotalSalesPrev90)
			    --TotalSalesThisYear-TotalSalesParallelPeriod
			    --TotalSalesThisYear
			    TotalSalesParallelPeriod
		formatString: 0
		lineageTag: 496505c2-1ed4-4053-af85-85c276015a00

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'InactiveCustomer Measure Switch' =
			
			
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,[Total Quantity],
			2,[Total Quantity Supply Date],
			3,[Total Quantity (Sales) By Delivery Date],
			[Total Quantity]
			)
		lineageTag: e08b37df-cf74-46b7-bd62-3464474fade4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'InactiveCustomer - Switch Flag 90 days vs 90 days' =
			
			VAR ReferenceDate = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			-- Calculate the total sales over the last 90 days (from the most recent date going back 90 days)
			VAR LastPreiod =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],--[Total Quantity],
			        DATESINPERIOD(dimDates[Date], ReferenceDate, -90, DAY)
			    )
			-- Calculate the total sales for the 90 days preceding the last 90 days (from ReferenceDate-90 to ReferenceDate-180)
			VAR PrevPreiod =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate - 90, -90, DAY)
			    )
			VAR DecreasePct =
			    DIVIDE( PrevPreiod - LastPreiod, PrevPreiod )
			VAR HasData =
			    NOT( ISBLANK( LastPreiod ) || ISBLANK( PrevPreiod ) )
			
			RETURN
			    IF(NOT HasData,BLANK(),          // no data → blank
			        IF(
			            PrevPreiod > 0
			            && DecreasePct > 0.30,   // drop > 30%
			            1,
			            0
			        )
			    )
			    --IF(TotalSalesLast90 = 0 && TotalSalesPrev90 > 0, 1, 0)
			    --DIVIDE(TotalSalesLast90-TotalSalesPrev90,TotalSalesPrev90)
			    --TotalSalesLast90-TotalSalesPrev90
			    --TotalSalesLast90
			    --TotalSalesPrev90
		formatString: 0
		lineageTag: fcabbbd1-eff8-4148-b4e9-156d7f18a93a

		changedProperty = IsHidden

	measure 'InactiveCustomer - Switch Flag 90 days vs 90 days ---- diff' =
			
			VAR ReferenceDate = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			-- Calculate the total sales over the last 90 days (from the most recent date going back 90 days)
			VAR TotalSalesLast90 =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],--[Total Quantity],
			        DATESINPERIOD(dimDates[Date], ReferenceDate, -90, DAY)
			    )
			-- Calculate the total sales for the 90 days preceding the last 90 days (from ReferenceDate-90 to ReferenceDate-180)
			VAR TotalSalesPrev90 =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate - 90, -90, DAY)
			    )
			RETURN
			    --IF(TotalSalesLast90 = 0 && TotalSalesPrev90 > 0, 1, 0)
			    --DIVIDE(TotalSalesLast90-TotalSalesPrev90,TotalSalesPrev90)
			    TotalSalesLast90-TotalSalesPrev90
			    --TotalSalesLast90
			    --TotalSalesPrev90
		formatString: #,0
		lineageTag: 93c98d51-64e5-4c25-a47f-a2b0194a0514

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'InactiveCustomer - Switch Flag 90 days vs 90 days ---- close' =
			
			VAR ReferenceDate = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			-- Calculate the total sales over the last 90 days (from the most recent date going back 90 days)
			VAR TotalSalesLast90 =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],--[Total Quantity],
			        DATESINPERIOD(dimDates[Date], ReferenceDate, -90, DAY)
			    )
			-- Calculate the total sales for the 90 days preceding the last 90 days (from ReferenceDate-90 to ReferenceDate-180)
			VAR TotalSalesPrev90 =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate - 90, -90, DAY)
			    )
			RETURN
			    --IF(TotalSalesLast90 = 0 && TotalSalesPrev90 > 0, 1, 0)
			    --DIVIDE(TotalSalesLast90-TotalSalesPrev90,TotalSalesPrev90)
			    --TotalSalesLast90-TotalSalesPrev90
			    TotalSalesLast90
			    --TotalSalesPrev90
		formatString: #,0
		lineageTag: dd39979e-3b36-464d-9085-e3600c759780

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'InactiveCustomer - Switch Flag 90 days vs 90 days ---- parallel' =
			
			VAR ReferenceDate = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			-- Calculate the total sales over the last 90 days (from the most recent date going back 90 days)
			VAR TotalSalesLast90 =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],--[Total Quantity],
			        DATESINPERIOD(dimDates[Date], ReferenceDate, -90, DAY)
			    )
			-- Calculate the total sales for the 90 days preceding the last 90 days (from ReferenceDate-90 to ReferenceDate-180)
			VAR TotalSalesPrev90 =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate - 90, -90, DAY)
			    )
			RETURN
			    --IF(TotalSalesLast90 = 0 && TotalSalesPrev90 > 0, 1, 0)
			    --DIVIDE(TotalSalesLast90-TotalSalesPrev90,TotalSalesPrev90)
			    --TotalSalesLast90-TotalSalesPrev90
			    --TotalSalesLast90
			    TotalSalesPrev90
		formatString: #,0
		lineageTag: 89f124c1-811f-4342-b7ca-faa02c28b0f2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'InactiveCustomer - Switch Flag 180 days vs 180 days --- diff' =
			
			VAR ReferenceDate = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			
			VAR TotalSalesLastPeriod =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate, -180, DAY)
			    )
			
			VAR TotalSalesPrevParallelPreiod =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate - 180, -180, DAY)
			    )
			RETURN
			    --IF(TotalSalesLastPeriod  = 0 && TotalSalesPrevParallelPreiod > 0, 1, 0)
			    --DIVIDE(TotalSalesLastPeriod-TotalSalesPrevParallelPreiod,TotalSalesPrevParallelPreiod)
			    TotalSalesLastPeriod-TotalSalesPrevParallelPreiod
			    --TotalSalesLastPeriod
			    --TotalSalesPrevParallelPreiod
		formatString: 0
		lineageTag: 3ddbc7ac-8180-486f-8ba1-2b9c7119be83

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'InactiveCustomer - Switch Flag 180 days vs 180 days --- close' =
			
			VAR ReferenceDate = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			
			VAR TotalSalesLastPeriod =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate, -180, DAY)
			    )
			
			VAR TotalSalesPrevParallelPreiod =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate - 180, -180, DAY)
			    )
			RETURN
			    --IF(TotalSalesLastPeriod  = 0 && TotalSalesPrevParallelPreiod > 0, 1, 0)
			    --DIVIDE(TotalSalesLastPeriod-TotalSalesPrevParallelPreiod,TotalSalesPrevParallelPreiod)
			    --TotalSalesLastPeriod-TotalSalesPrevParallelPreiod
			    TotalSalesLastPeriod
			    --TotalSalesPrevParallelPreiod
		formatString: #,0
		lineageTag: c1ccd3a9-1595-4bc5-8dd1-2a0bef918f89

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'InactiveCustomer - Switch Flag 180 days vs 180 days --- parallel' =
			
			VAR ReferenceDate = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			
			VAR TotalSalesLastPeriod =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate, -180, DAY)
			    )
			
			VAR TotalSalesPrevParallelPreiod =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate - 180, -180, DAY)
			    )
			RETURN
			    --IF(TotalSalesLastPeriod  = 0 && TotalSalesPrevParallelPreiod > 0, 1, 0)
			    --DIVIDE(TotalSalesLastPeriod-TotalSalesPrevParallelPreiod,TotalSalesPrevParallelPreiod)
			    --TotalSalesLastPeriod-TotalSalesPrevParallelPreiod
			    --TotalSalesLastPeriod
			    TotalSalesPrevParallelPreiod
		formatString: 0
		lineageTag: d442186a-5cc7-48bf-aaec-1b461ac3626b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'InactiveCustomer - Switch Flag 180 days vs 180 days' =
			
			VAR ReferenceDate = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			
			VAR TotalSalesLastPeriod =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate, -180, DAY)
			    )
			
			VAR TotalSalesPrevParallelPreiod =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate - 180, -180, DAY)
			    )
			
			VAR DecreasePct =
			    DIVIDE( TotalSalesPrevParallelPreiod - TotalSalesLastPeriod, TotalSalesPrevParallelPreiod )
			VAR HasData =
			    NOT( ISBLANK( TotalSalesLastPeriod ) || ISBLANK( TotalSalesPrevParallelPreiod ) )
			
			RETURN
			    IF(NOT HasData,BLANK(),                     // no data → blank
			        IF(
			            TotalSalesPrevParallelPreiod > 0
			            && DecreasePct > 0.30,   // drop > 30%
			            1,
			            0
			        )
			    )
			    --IF(TotalSalesLastPeriod  = 0 && TotalSalesPrevParallelPreiod > 0, 1, 0)
			    --DIVIDE(TotalSalesLastPeriod-TotalSalesPrevParallelPreiod,TotalSalesPrevParallelPreiod)
			    --TotalSalesLastPeriod-TotalSalesPrevParallelPreiod
			    --TotalSalesLastPeriod
			    --TotalSalesPrevParallelPreiod
		lineageTag: 5cba239e-ed4e-40a0-9c72-04d5bd64b3ff

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'InactiveCustomer - Switch Flag 90 days vs 90 days ---- %Change' =
			
			VAR ReferenceDate = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			-- Calculate the total sales over the last 90 days (from the most recent date going back 90 days)
			VAR TotalSalesLast90 =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],--[Total Quantity],
			        DATESINPERIOD(dimDates[Date], ReferenceDate, -90, DAY)
			    )
			-- Calculate the total sales for the 90 days preceding the last 90 days (from ReferenceDate-90 to ReferenceDate-180)
			VAR TotalSalesPrev90 =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate - 90, -90, DAY)
			    )
			RETURN
			    --IF(TotalSalesLast90 = 0 && TotalSalesPrev90 > 0, 1, 0)
			    DIVIDE(TotalSalesLast90-TotalSalesPrev90,TotalSalesPrev90)
			    --TotalSalesLast90-TotalSalesPrev90
			    --TotalSalesLast90
			    --TotalSalesPrev90
		formatString: 0%;-0%;0%
		lineageTag: 3a9386cb-9a35-49ff-a4aa-025a1d0fa6d4

		changedProperty = IsHidden

	measure 'InactiveCustomer - Orders Supply Date Flag YTD vs LY YTD ---- %change' =
			
			VAR TotalSalesThisYear = [Quantity Supply Date DynamicTable]
			VAR TotalSalesParallelPeriod = [Quantity Supply DynamicTable LY YTD]
			
			RETURN
			    --IF(TotalSalesThisYear = 0 && TotalSalesParallelPeriod > 0, 1, 0)
			    DIVIDE(TotalSalesThisYear-TotalSalesParallelPeriod,TotalSalesParallelPeriod)
			    --TotalSalesThisYear-TotalSalesParallelPeriod
			    --TotalSalesLast90
			    --TotalSalesPrev90
		formatString: 0%;-0%;0%
		lineageTag: 9e01c4b8-d521-4ca7-bda0-5f2cc2241039

		changedProperty = IsHidden

	measure 'InactiveCustomer - Orders Supply Date Gauge MAX' =
			
			[InactiveCustomer - Orders Supply Date Flag YTD vs LY YTD ---- ParallelPeriod]*2
		formatString: 0
		lineageTag: 3a79a62e-c923-4c78-9a14-0598952e4093

		changedProperty = IsHidden

	measure 'InactiveCustomer - Orders Supply Date Gauge MIN' = [InactiveCustomer - Orders Supply Date Flag YTD vs LY YTD ---- ParallelPeriod]*0.7
		formatString: 0
		lineageTag: f08b89c3-bcbc-4e60-99f6-199fc4989e41

		changedProperty = IsHidden

	measure 'InactiveCustomer - Switch Gauge 90 MAX' =
			
			[InactiveCustomer - Switch Flag 90 days vs 90 days ---- parallel]*2
		lineageTag: 9d33de07-dd63-4e5a-adba-b92b3be7af67

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'InactiveCustomer - Switch Gauge 180 MAX' =
			
			[InactiveCustomer - Switch Flag 180 days vs 180 days --- parallel]*2
		lineageTag: 31a45593-f095-4ac4-b0ee-b113b82cd6e3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'InactiveCustomer - Switch Gauge 90 MIN' =
			
			[InactiveCustomer - Switch Flag 90 days vs 90 days ---- parallel]*0.7
		lineageTag: 8d63b5e7-37f4-453b-af82-8d01ed881ecc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'InactiveCustomer - Switch Gauge 180 MIN' =
			
			[InactiveCustomer - Switch Flag 180 days vs 180 days --- parallel]*0.7
		lineageTag: 8789cbdd-a6eb-48cb-8381-bc9cefef4978

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'InactiveCustomer - Switch Flag 180 days vs 180 days --- %change' =
			
			VAR ReferenceDate = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			
			VAR TotalSalesLastPeriod =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate, -180, DAY)
			    )
			
			VAR TotalSalesPrevParallelPreiod =
			    CALCULATE(
			        [InactiveCustomer Measure Switch],
			        DATESINPERIOD(dimDates[Date], ReferenceDate - 180, -180, DAY)
			    )
			RETURN
			    --IF(TotalSalesLastPeriod  = 0 && TotalSalesPrevParallelPreiod > 0, 1, 0)
			    DIVIDE(TotalSalesLastPeriod-TotalSalesPrevParallelPreiod,TotalSalesPrevParallelPreiod)
			    --TotalSalesLastPeriod-TotalSalesPrevParallelPreiod
			    --TotalSalesLastPeriod
			    --TotalSalesPrevParallelPreiod
		formatString: #,0%;-#,0%;#,0%
		lineageTag: fe0f81e3-7226-4df3-b4ac-76104083cf1d

		changedProperty = IsHidden

	measure 'InactiveCustomer – Yellow Flag' =
			
			VAR F_Supply_YTD =
			    [InactiveCustomer - Orders Supply Date Flag YTD vs LY YTD]
			
			VAR F_180_Qty =
			    CALCULATE(
			        [InactiveCustomer - Switch Flag 180 days vs 180 days],
			        'OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order] = 1
			    )
			
			VAR F_180_Del =
			    CALCULATE(
			        [InactiveCustomer - Switch Flag 180 days vs 180 days],
			        'OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order] = 3
			    )
			
			VAR F_90_Qty =
			    CALCULATE(
			        [InactiveCustomer - Switch Flag 90 days vs 90 days],
			        'OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order] = 1
			    )
			
			VAR F_90_Del =
			    CALCULATE(
			        [InactiveCustomer - Switch Flag 90 days vs 90 days],
			        'OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order] = 3
			    )
			
			// check if any of the four secondary flags = 1
			VAR OtherFlagsCount =
			    IF( F_180_Qty = 1, 1, 0 )
			  + IF( F_180_Del = 1, 1, 0 )
			  + IF( F_90_Qty  = 1, 1, 0 )
			  + IF( F_90_Del  = 1, 1, 0 )
			  + IF( F_Supply_YTD = 1, 1, 0 )
			
			RETURN
			    IF(
			        OtherFlagsCount=0,
			        --ISBLANK(F_Supply_YTD),
			        BLANK(),                       // no YTD data → blank
			        IF(
			            //F_Supply_YTD = 1 && OtherFlagsCount >=1, // YTD = 1 AND at least one other = 1
			            OtherFlagsCount >=2,
			            1,
			            0
			        )
			    )
		formatString: 0
		lineageTag: 55c05b9b-9286-4b4c-80e2-56af5802f997

		changedProperty = IsHidden

	measure 'InactiveCustomer – Red Flag' =
			
			VAR F_Supply_YTD =
			    [InactiveCustomer - Orders Supply Date Flag YTD vs LY YTD]
			
			VAR F_180_Qty =
			    CALCULATE(
			        [InactiveCustomer - Switch Flag 180 days vs 180 days],
			        'OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order] = 1
			    )
			
			VAR F_180_Del =
			    CALCULATE(
			        [InactiveCustomer - Switch Flag 180 days vs 180 days],
			        'OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order] = 3
			    )
			
			VAR F_90_Qty =
			    CALCULATE(
			        [InactiveCustomer - Switch Flag 90 days vs 90 days],
			        'OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order] = 1
			    )
			
			VAR F_90_Del =
			    CALCULATE(
			        [InactiveCustomer - Switch Flag 90 days vs 90 days],
			        'OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order] = 3
			    )
			
			// check if any of the four secondary flags = 1
			VAR OtherFlagsCount =
			    IF( F_180_Qty = 1, 1, 0 )
			    + IF( F_180_Del = 1, 1, 0 )
			    + IF( F_90_Qty  = 1, 1, 0 )
			    + IF( F_90_Del  = 1, 1, 0 )
			    + IF( F_Supply_YTD = 1, 1, 0 )
			
			RETURN
			    IF(OtherFlagsCount<3,BLANK(),1)
			    /*IF(
			        OtherFlagsCount =0,
			        --ISBLANK(F_Supply_YTD),
			        BLANK(),                       // no YTD data → blank
			        IF(
			            F_Supply_YTD = 1 && OtherFlagsCount >=2, // YTD = 1 AND at least one other = 2
			            1,
			            0
			        )
			    )*/
		formatString: 0
		lineageTag: 138aa2b2-4c72-4514-b849-56f4fa75d18e

		changedProperty = IsHidden

	measure _blank2 = BLANK()
		formatString: 0
		lineageTag: c5142ac3-6204-4a8f-b8e3-8a67de9c6591

		changedProperty = IsHidden

	measure 'InactiveCustomer – Flag Scoure Count' =
			
			VAR F_Supply_YTD =
			    [InactiveCustomer - Orders Supply Date Flag YTD vs LY YTD]
			
			VAR F_180_Qty =
			    CALCULATE(
			        [InactiveCustomer - Switch Flag 180 days vs 180 days],
			        'OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order] = 1
			    )
			
			VAR F_180_Del =
			    CALCULATE(
			        [InactiveCustomer - Switch Flag 180 days vs 180 days],
			        'OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order] = 3
			    )
			
			VAR F_90_Qty =
			    CALCULATE(
			        [InactiveCustomer - Switch Flag 90 days vs 90 days],
			        'OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order] = 1
			    )
			
			VAR F_90_Del =
			    CALCULATE(
			        [InactiveCustomer - Switch Flag 90 days vs 90 days],
			        'OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order] = 3
			    )
			
			// check if any of the four secondary flags = 1
			VAR OtherFlagsCount =
			    IF( F_180_Qty = 1, 1, 0 )
			  + IF( F_180_Del = 1, 1, 0 )
			  + IF( F_90_Qty  = 1, 1, 0 )
			  + IF( F_90_Del  = 1, 1, 0 )
			  + IF( F_Supply_YTD = 1, 1, 0 )
			
			RETURN
			    IF(
			        OtherFlagsCount=0,
			        BLANK(),                       // no YTD data → blank
			    OtherFlagsCount
			    )
		formatString: 0
		lineageTag: d2292254-0fdb-4d10-be8d-ed9630b19fd0

		changedProperty = IsHidden

	measure 'AVG Sales Balance Price Flat+FlatValue' = ```
			
			VAR _MaxDate = CALCULATE(MAX(factOrders[תאריך אספקה]),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה]))
			VAR MinDate = MIN(dimDates[Date])
			VAR openSales = 
			CALCULATE([Total Sales Flat + FlatValue Balance Switch Supply Date],dimOrderStatus[Status_Group]="Open",FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate))
			--CALCULATE([Total Sales Flat + FlatValue Switch Supply Date],dimOrderStatus[Status_Group]="Open",FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate))
			VAR OpenSalesQuantity = CALCULATE([Open Orders Quantity Flat By Supply Date]+[Open Orders Quantity Basis By Supply Date],FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate))
			var allOpenChosenMonth = [Avg Unit Price By Supply Date]
			var firstMonth =
			CALCULATE(
			    DIVIDE(openSales ,OpenSalesQuantity)
			    --openSales
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate)-- && dimDates[Date]>=MinDate)
			)
			
			return 
			IF(MAX(dimDates[Show Months])="This Month",firstMonth,allOpenChosenMonth)
			--openSales
			--OpenSalesQuantity
			```
		lineageTag: ffe3e5c7-2f9c-43af-abc1-044113983dac

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales Flat + FlatValue Balance Switch Supply Date' =
			
			CALCULATE([Total Sales Flat + FlatValue Balance Switch]
			                  ,ALLSELECTED(factOrders[תאריך אספקה],factOrders[Date])
			                  ,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			                  ,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			                )
		lineageTag: 9fa3d1ef-f341-409c-b2e6-1a6b9cbf599d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Sales Price Flat - FirstMonth' = ```
			
			VAR _MaxDate = CALCULATE(MAX(factOrders[תאריך אספקה]),USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה]))
			VAR MinDate = MIN(dimDates[Date])
			VAR openSales = 
			CALCULATE([Total Sales Flat Balance Switch Supply Date],dimOrderStatus[Status_Group]="Open",FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate))
			--CALCULATE([Total Sales Flat + FlatValue Switch Supply Date],dimOrderStatus[Status_Group]="Open",FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate))
			VAR OpenSalesQuantity = CALCULATE([Open Orders Quantity Flat By Supply Date],FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate))
			var allOpenChosenMonth = [AVG Sales Price Flat By Supply Date]
			var firstMonth =
			CALCULATE(
			    DIVIDE(openSales ,OpenSalesQuantity)
			    --openSales
			    ,FILTER(ALL(dimDates),dimDates[Date]<=_MaxDate)-- && dimDates[Date]>=MinDate)
			)
			
			return 
			IF(MAX(dimDates[Show Months])="This Month",firstMonth,allOpenChosenMonth)
			```
		lineageTag: a9ae7730-c3b4-489d-8464-8ff98d85fdfa

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales Flat Balance Switch' =
			
			SWITCH(MIN(PriceType[ID]),
			1,SUM(factOrders[LineTotalFlatBalanceUSD]),
			2,SUM(factOrders[LineTotalFlatBalanceCFFUSD]),
			3,SUM(factOrders[LineTotalFlatBalanceFOTUSD]),
			SUM(factOrders[LineTotalFlatBalanceUSD]))
		lineageTag: 1ff16ea8-7e1c-41cf-8d7d-484f18fdad56

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales Flat Balance Switch Supply Date' =
			
			CALCULATE([Total Sales Flat Balance Switch]
			                  ,ALLSELECTED(factOrders[תאריך אספקה],factOrders[Date])
			                  ,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			                  ,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			                )
		lineageTag: 7a0723fc-89be-49fd-86d7-8972bb2242f5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity LY YTD-ToDate' =
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-1
			RETURN
			CALCULATE(CALCULATE([Total Quantity],FILTER(ALL(Sub_DimDates),Sub_DimDates[Year]=_YEAR),dimDates[Is History to Today]=1,Sub_DimDates[Is History To Today]=1))
		displayFolder: כמויות
		lineageTag: 52f0c8a2-47b9-4e01-bbb8-f6f9eafb100b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Change Quantity LY YTD-Todate' = DIVIDE([Quantity YTD]-[Quantity LY YTD-ToDate],[Quantity LY YTD-ToDate])
		formatString: 0%;-0%;0%
		displayFolder: כמויות
		lineageTag: ac25fea3-9337-4aa8-afca-6a39681cd683

		changedProperty = IsHidden

	measure 'Avg Sales Balance Price Basis Flat Value' =
			
			--DIVIDE([Total Sales Flat Value] , [Open Orders Quantity Basis])
			DIVIDE([Total Sales Flat Value Switch]-[Total Sales Flat Balance Switch] , [Open Orders Quantity Basis])
			--DIVIDE([Total Sales Flat Value Switch] , [Open Orders Quantity Basis])
		lineageTag: 4a38f794-7aa7-4607-90d7-8d0950ce06a1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Sales Balance Price Basis Flat Value By Supply Date' =
			
			
			CALCULATE([Avg Sales Balance Price Basis Flat Value]
			,USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			)
		lineageTag: b51513db-f58d-41f1-a211-b4e559c0d6d1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Dynamic Switch LY FYvsYTD' =
			
			SWITCH(MIN(SwitchTable_LYvsLYYTD[ID]),
			1,CALCULATE([Total Quantity Supply DATE],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR),dimDates[IsHistory]=1), --FY
			2,CALCULATE(CALCULATE([Total Quantity Supply to DATE],DATEADD(Sub_DimDates[Date],-1,YEAR),DATEADD(DimDates[Date],-1,YEAR)),dimDates[IsHistory]=1) --YTD
			)
		lineageTag: b2a3a308-4820-4a10-b630-9869695ad303

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Unit Price (Weekly)' =
			
			// IF(
			//     ISFILTERED(dimDates[MonthInCalendarName]),
			    CALCULATE(
			     [Avg Unit Price],
			    USERELATIONSHIP(dimDates[Date],factOrders[תאריך אספקה])
			    --REMOVEFILTERS(dimDates[MonthInCalendarName])
			)
			// ,[Avg Unit Price]
			// )
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 62a96600-9246-4d1a-81b1-57e2ac7918a9

		changedProperty = IsHidden

	measure 'QQuantity Sales USD NIS 3Y Switch' = ```
			
			 SWITCH(MAX(OrderVSExecutionVSSupply[ID]),
			    1,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE([Total Sales NIS],DATEADD(Sub_DimDates[Date],-3,YEAR),DATEADD(DimDates[Date],-3,YEAR)),
			        2, CALCULATE([Total Sales USD],DATEADD(Sub_DimDates[Date],-3,YEAR),DATEADD(DimDates[Date],-3,YEAR)),
			        3, CALCULATE([Total Quantity],DATEADD(Sub_DimDates[Date],-3,YEAR),DATEADD(DimDates[Date],-3,YEAR)))
			    ,2,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE(CALCULATE([Total Sales NIS Supply TO DATE],DATEADD(Sub_DimDates[Date],-3,YEAR),DATEADD(DimDates[Date],-3,YEAR)),dimDates[IsHistory]=1),
			        2, CALCULATE(CALCULATE([Total Sales USD Supply TO DATE],DATEADD(Sub_DimDates[Date],-3,YEAR),DATEADD(DimDates[Date],-3,YEAR)),dimDates[IsHistory]=1),
			        3, [Quantity Supply DynamicTable 3Y])
			    ,3,SWITCH(MAX(VAT_MeasureSelctionTable[ID ANALYSIS]),
			        1, CALCULATE([Total Sales NIS (Sales)],DATEADD(Sub_DimDates[Date],-3,YEAR),DATEADD(DimDates[Date],-3,YEAR)),
			        2, CALCULATE([Total Sales USD (Sales)],DATEADD(Sub_DimDates[Date],-3,YEAR),DATEADD(DimDates[Date],-3,YEAR)),
			        3, CALCULATE([Total Quantity (Sales)],DATEADD(Sub_DimDates[Date],-3,YEAR),DATEADD(DimDates[Date],-3,YEAR)))
			 )+0
			```
		displayFolder: Dynamic Switch Graph Measures
		lineageTag: c5257b90-8fd5-4b5e-9f0d-4ff35da10b6c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Supply DynamicTable 3Y' =
			
			VAR _YEAR = CALCULATE(YEAR(MAX(dimDates[date])),dimDates[IsHistory]=1)-3
			RETURN
			CALCULATE([Total Quantity Supply Date],
			            Sub_DimDates[Year]=_YEAR,
			            DATEADD(Sub_DimDates[Date],-3,YEAR),
			            DATEADD(DimDates[Date],-3,YEAR)
			        )
		displayFolder: Dynamic Table
		lineageTag: 82e37e9c-ab83-430a-b1f7-dbaa3d46f383

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity weekly Switch' = ```
			
			 SWITCH(MAX(OrderVSExecutionVSSupply[ID]),
			    1,[Quantity Orders DynamicTable],
			    2,[Quantity Supply Date DynamicTable],
			    3,[Quantity Execution DynamicTable],
			    [Quantity Orders DynamicTable]
			    )
			//  SWITCH(MAX(OrderVSExecutionVSSupply[ID]),
			//     1,[Total Quantity],
			//     2,[Total Quantity Supply TO DATE],
			//     3,[Total Quantity (Sales)])
			```
		displayFolder: Dynamic Switch Graph Measures
		lineageTag: da2d8f1d-7f11-4b41-8ba9-bdfe4279d2d8

		formatStringDefinition =
				VAR V = [Quantity weekly Switch]
				RETURN
				SWITCH(
				    TRUE(),
				    /* ==== CURRENCY (USD) ==== */
				    ABS(V) >= 1000000,
				        "#,0,,.0#M",
				
				    ABS(V) >= 1000,
				        "#,0,.0#K",
				
				    "#,0"
				)

	measure 'Avg CF (Items)' =
			
			IF( HASONEVALUE(dimItemsSimple[Article_Description]),
			    [Avg CF Price],
			    BLANK()
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CF
		lineageTag: 0369fc31-6e0a-49df-b2a5-8c27c2e3c5e3

	measure 'My Flag Measure' = ```
			
			VAR A = [Quantity Dynamic Table Switch]
			VAR B = [Quantity Dynamic Table Switch LY FYvsYTD]
			VAR C = [Quantity Dynamic Table Switch 2LY FYvsYTD]
			RETURN
			IF (
			    (ISBLANK(A) || A = 0) &&
			    (ISBLANK(B) || B = 0) &&
			    (ISBLANK(C) || C = 0),
			    1,
			    0
			)
			
			```
		formatString: 0
		lineageTag: df518223-140b-4659-a1a2-6bdea5416847

	measure 'InactiveCustomer - Switch Flag YTD' =
			
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,[Quantity Orders DynamicTable],
			2,[Quantity Supply Date DynamicTable],
			3,[Quantity Execution DynamicTable],
			[Quantity Orders DynamicTable]
			)
		lineageTag: 0d8b3baa-7718-4579-9388-3cda7d3d51d6

		formatStringDefinition =
				VAR V = [InactiveCustomer - Switch Flag YTD]
				RETURN
				SWITCH(
				    TRUE(),
				    ABS(V) >= 1000000,
				        "#,0,,.0#M",
				    ABS(V) >= 1000,
				        "#,0,.0#K",
				    "#,0" --Number
				)

	measure 'InactiveCustomer - Switch Gauge YTD MIN' =
			
			[InactiveCustomer - Switch Flag YTD --parallel] * 0.7
		lineageTag: 099fcb4e-22d9-4d2b-bde0-ed7d3e15ed66

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'InactiveCustomer - Switch Gauge YTD MAX' = ```
			
			[InactiveCustomer - Switch Flag YTD --parallel] * 2 
			```
		lineageTag: ff1cfaa6-1310-40ad-9cc9-d2bff5410f10

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'InactiveCustomer - Switch Flag YTD --parallel' =
			
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,[Quantity Orders DynamicTable LY YTD],
			2,[Quantity Supply DynamicTable LY YTD],
			3,[Quantity Execution DynamicTable LY YTD],
			[Quantity Orders DynamicTable LY YTD]
			)
		lineageTag: 93b35f2b-8fa4-4ff1-b620-5d0d48b8ae00

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'InactiveCustomer - Switch Flag YTD --- %change' = ```
			
			VAR TotalSalesLastPeriod =
			    [InactiveCustomer - Switch Flag YTD] 
			VAR TotalSalesPrevParallelPreiod =
			    [InactiveCustomer - Switch Flag YTD --parallel] 
			RETURN
			    DIVIDE(TotalSalesLastPeriod-TotalSalesPrevParallelPreiod,TotalSalesPrevParallelPreiod)
			```
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 238018b5-0f60-451d-a777-e48d18a574d3

	measure 'Switch Titles YTD' =
			
			CONCATENATE(SELECTEDVALUE('OrderSupplyExecution Parameter'[Value4])," YTD")
		lineageTag: 2c621a9e-d97d-4282-b44f-2f2e3ad1fa19

	measure 'Switch Titles 180' =
			
			CONCATENATE(SELECTEDVALUE('OrderSupplyExecution Parameter'[Value4])," 180")
		lineageTag: 3525da0b-43b1-4474-bb7f-b7a3a0b0e993

	measure 'Switch Titles 90' =
			
			CONCATENATE(SELECTEDVALUE('OrderSupplyExecution Parameter'[Value4])," 90")
		lineageTag: bb03962e-1b14-4f46-b52b-895914fcb1a9

	measure 'Quantity Months Table Switch (Sales Analyzer)' = ```
			
			VAR _MinDate= MIN(Sub_DimDates[Date])
			VAR _CheckBlank = CALCULATE([Total Quantity Supply TO DATE],ALL(dimItemsSimple),Filter(ALL(Sub_DimDates),Sub_DimDates[Date]>=_MinDate))
			// VAR _todate = CALCULATE(MAX(dimDates[Date]),FILTER(ALL(dimDates),dimDates[IsHistory]=1))
			VAR _Maxdate = CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			VAR _SubMaxdate = MAX(Sub_DimDates[Date])
			VAR _date = IF(_Maxdate<=_SubMaxdate,_Maxdate,_SubMaxdate)
			VAR _Orders = CALCULATE([Quantity Orders DynamicTable],FILTER(dimDates,dimDates[Date]<=_date))
			
			
			Var _Supply =
			CALCULATE(CALCULATE([Total Quantity]
			                  ,FILTER(dimDates,dimDates[Date]<=_date)
			                  ,USERELATIONSHIP(Sub_DimDates[Date],factOrders[תאריך אספקה])
			                  )
			        ,dimDates[IsHistory]=1)
			VAR _Execute = CALCULATE([Quantity Execution DynamicTable],FILTER(dimDates,dimDates[Date]<=_date)) --[Quantity Execution DynamicTable]
			VAR _Measure = 
			SWITCH(MIN('OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order]),
			1,IF(ISBLANK(_Orders),"-",_Orders),
			2,IF(ISBLANK(_Supply),"-",_Supply),
			3,IF(ISBLANK(_Execute),"-",_Execute),
			IF(ISBLANK(_Orders),"-",_Orders)
			)
			
			
			Return
			IF(ISBLANK(_CheckBlank),BLANK(),_Measure)
			```
		displayFolder: Dynamic Table
		lineageTag: d5bd4196-9978-4154-b57d-021af4562f6f

		formatStringDefinition = "#,##0;-#,##0;-"

	measure 'Sort Measure' =
			VAR sortfield = SELECTEDVALUE ( SortOptions[Sort By], "Open Orders" )
			RETURN
			SWITCH (
			    TRUE (),
			
			    sortfield = "Open Orders",
			    RANKX ( ALL ( dimCustomers[שם לקוח אב] ), [Quantity Dynamic Table Switch Open Orders], , DESC, DENSE ),
			
			    sortfield = "Size",
			    RANKX (
			        ALL ( dimCustomers[שם לקוח אב] ),
			        CALCULATE ( [Qty Num], dimDates[ShowLast2Years] = 1 ),
			        , DESC, DENSE
			    ),
			
			    sortfield = "Order Date",
			    RANKX ( ALL ( dimCustomers[שם לקוח אב] ), [Last Order Date], , DESC, DENSE )
			)
		formatString: 0
		lineageTag: 749622c4-af13-4d4f-8a9a-6748f14a376f

	measure 'Last Order Date' = ```
			
			CALCULATE(
			    MAX(factOrders[Date]),
			    ALLEXCEPT(dimCustomers, dimCustomers[שם לקוח אב])
			)
			
			```
		formatString: General Date
		lineageTag: b42ed131-5d65-4ca0-bf1a-c7103c1a61e3

	measure 'Total Months' =
			
			VAR StartD = DATE ( 2025, 1, 1 )
			VAR EndD = EOMONTH ( TODAY (), 0 )
			RETURN
			    CALCULATE (
			        DISTINCTCOUNT ( 'Sub_DimDates'[YearMonthNumber] ),
			        'Sub_DimDates'[Date] >= StartD,
			        'Sub_DimDates'[Date] <= EndD,
			        REMOVEFILTERS ( 'Sub_DimDates' )
			    )
		formatString: 0
		displayFolder: Sales Qty Target
		lineageTag: 12bcaf32-e2e9-42bc-af04-993a63b8754c

	measure 'Months With Purchases' =
			
			VAR StartD = DATE ( 2025, 1, 1 )
			VAR EndD = EOMONTH ( TODAY (), 0 )
			RETURN
			    CALCULATE (
			        COUNTROWS (
			            FILTER (
			                ADDCOLUMNS (
			                    VALUES ( 'Sub_DimDates'[MonthInCalendarShortName] ),
			                    "@q", CALCULATE ( [Qty Num] )
			                ),
			                [@q] > 0
			            )
			        ),
			        'Sub_DimDates'[Date] >= StartD,
			        'Sub_DimDates'[Date] <= EndD,
			        REMOVEFILTERS ( 'Sub_DimDates' )
			    )
		formatString: 0
		displayFolder: Sales Qty Target
		lineageTag: 048827ef-2329-45e6-9b09-420efd784495

	measure 'TopN Avg' =
			
			VAR N = [Top Months Value]
			VAR StartD = DATE ( 2025, 1, 1 )
			VAR EndD = EOMONTH ( TODAY (), 0 )
			VAR MonthlyQty =
			    CALCULATETABLE (
			        ADDCOLUMNS (
			            VALUES ( 'Sub_DimDates'[MonthInCalendarShortName] ),
			            "@q", CALCULATE ( [Qty Num] )
			        ),
			        'Sub_DimDates'[Date] >= StartD,
			        'Sub_DimDates'[Date] <= EndD,
			        REMOVEFILTERS ( 'Sub_DimDates' )
			    )
			VAR TopMonths =
			    TOPN ( N, MonthlyQty, [@q], DESC, 'Sub_DimDates'[MonthInCalendarShortName], ASC )
			RETURN
			    DIVIDE ( SUMX ( TopMonths, [@q] ), N )
		displayFolder: Sales Qty Target
		lineageTag: 85c6d78b-3d12-4085-9166-7f09b5059d69

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Next Month Qty' =
			
			VAR NextStart = EOMONTH ( TODAY (), 0 ) + 1
			VAR NextEnd = EOMONTH ( TODAY (), 1 )
			RETURN
			    CALCULATE (
			        [Qty Num],
			        'Sub_DimDates'[Date] >= NextStart,
			        'Sub_DimDates'[Date] <= NextEnd,
			        REMOVEFILTERS ( 'Sub_DimDates' )
			    )
		displayFolder: Sales Qty Target
		lineageTag: 9018d972-4cb4-4a91-a71e-17fff549b565

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Norm Avg' =
			
			DIVIDE ( [TopN Avg] * [Months With Purchases], [Total Months] )
		displayFolder: Sales Qty Target
		lineageTag: ab2a3e2e-f0ab-4d7b-bf65-209fe45a6b52

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gap Next Month vs Norm' = ```
			[Norm Avg] - COALESCE ( [Next Month Qty], 0 ) 
			```
		displayFolder: Sales Qty Target
		lineageTag: dd754fcf-e6e4-4283-80a7-672eafa8e3eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gap Next Month - No Booking' =
			
			VAR nq = [Next Month Qty]
			RETURN
			    IF ( ISBLANK ( nq ) || nq = 0,  [Norm Avg] - 0 , "-" )
		displayFolder: Sales Qty Target
		lineageTag: 0c7a8f89-e98b-4d1d-9e82-04dc83ca10c1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qty Num' =
			
			// VAR raw = [Quantity Months Table Switch (Sales Analyzer)]
			// RETURN
			//     IF ( ISBLANK ( raw ), 0, IFERROR ( raw + 0, 0 ) )
			VAR _Orders = [Quantity Orders DynamicTable]
			VAR _Supply =
			    CALCULATE (
			        [Total Quantity],
			        USERELATIONSHIP ( Sub_DimDates[Date], factOrders[תאריך אספקה] )
			    )
			VAR _Execute = [Quantity Execution DynamicTable]
			VAR _Sel = MIN ( 'OrderSupplyExecution Parameter'[OrderSupplyExecution Parameter Order] )
			VAR _Val =
			    SWITCH ( _Sel,
			        1, _Orders,
			        2, _Supply,
			        3, _Execute,
			        _Orders
			    )
			RETURN
			    IF ( ISBLANK ( _Val ), 0, _Val )
		displayFolder: Sales Qty Target
		lineageTag: 47cf039b-27c6-4756-a440-5549492d5949

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EntityID
		dataType: string
		lineageTag: d8980b69-fa29-41ac-86c7-df878cd50f78
		summarizeBy: none
		sourceColumn: EntityID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderID
		dataType: string
		lineageTag: 0c39fa40-0255-48c6-93e3-8260f385e3ac
		summarizeBy: none
		sourceColumn: OrderID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 5806b3e2-9ca9-485a-bf99-29dfb83f6ef1
		summarizeBy: sum
		sourceColumn: OrderLineNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DocName
		dataType: string
		lineageTag: f9866a84-6b90-47d7-9381-289f895ecf9e
		summarizeBy: none
		sourceColumn: DocName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AccountKey
		dataType: string
		lineageTag: b7b1fd15-efc1-4c56-a2e5-e6c6145b8629
		summarizeBy: none
		sourceColumn: AccountKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Time
		dataType: int64
		formatString: 0
		lineageTag: cc4030f4-58fa-4dbf-b9dc-1f4ce2ce5758
		summarizeBy: sum
		sourceColumn: Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AgentKey
		dataType: string
		lineageTag: 34e19320-aeb1-4640-979e-d503dd9ea3b1
		summarizeBy: none
		sourceColumn: AgentKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ItemKey
		dataType: string
		lineageTag: f6e8c3da-83ae-479a-bd39-db6b32ffed4a
		summarizeBy: none
		sourceColumn: ItemKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 30e59ab2-6b91-4e2f-8aa9-66f50982b231
		summarizeBy: count
		sourceColumn: EmployeeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'חבר מועדון'
		dataType: int64
		formatString: 0
		lineageTag: 80abc19a-082c-41fe-824f-9952c2be4a75
		summarizeBy: sum
		sourceColumn: חבר מועדון

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DiscountPercent
		dataType: int64
		formatString: 0
		lineageTag: 49c722f7-fee4-45f9-8209-46797ec6119f
		summarizeBy: sum
		sourceColumn: DiscountPercent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LineTotalDiscount
		dataType: int64
		formatString: 0
		lineageTag: ca0cea97-18e6-4644-a107-166ea42e7294
		summarizeBy: sum
		sourceColumn: LineTotalDiscount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UnitGrossPrice
		dataType: int64
		formatString: 0
		lineageTag: 215511a0-b1ce-4804-9ca2-ace76e2adee2
		summarizeBy: sum
		sourceColumn: UnitGrossPrice

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UnitNetPriceUSD
		dataType: double
		lineageTag: b5f38c56-ea64-48e1-9265-9763023679bd
		summarizeBy: sum
		sourceColumn: UnitNetPriceUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: double
		formatString: #,#.##;(#,#.##)
		lineageTag: 2b3c3a3f-798a-40b9-a948-3367ba6bcffe
		summarizeBy: sum
		sourceColumn: Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column LineTotalCost
		dataType: int64
		formatString: " #,#.##;(#,#.##)"
		lineageTag: 98062215-0cd8-46f9-8132-d9ecaecc4fee
		summarizeBy: sum
		sourceColumn: LineTotalCost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LineTotalNetUSD
		dataType: double
		formatString: " #,#.##;(#,#.##)"
		lineageTag: d352bafd-cf99-40eb-95c1-f45d35995250
		summarizeBy: sum
		sourceColumn: LineTotalNetUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitNetPriceNIS
		dataType: double
		formatString: " #,#.##;(#,#.##)"
		lineageTag: afcf83a8-9d7d-46e5-a979-cb99f970ddca
		summarizeBy: sum
		sourceColumn: UnitNetPriceNIS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalNetNIS
		dataType: double
		formatString: " #,#.##;(#,#.##)"
		lineageTag: 4ca7e7c9-ae6f-4510-af03-60b0357395a9
		summarizeBy: sum
		sourceColumn: LineTotalNetNIS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YearMonth
		dataType: int64
		formatString: 0
		lineageTag: a12b3f88-9dc4-477c-acb0-7cc4a0f34a5e
		summarizeBy: sum
		sourceColumn: YearMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column סטטוס
		dataType: int64
		formatString: 0
		lineageTag: ce8fec9a-7266-4435-a89a-5b3afc9d5476
		summarizeBy: none
		sourceColumn: סטטוס

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ChargeFlag
		dataType: int64
		formatString: 0
		lineageTag: 05fc656a-b35c-450a-93b7-579d060ca3e7
		summarizeBy: sum
		sourceColumn: ChargeFlag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'סטטוס ליקוט כותרת'
		dataType: int64
		formatString: 0
		lineageTag: 4b429666-47ce-420f-b6d1-711d94e055d3
		summarizeBy: sum
		sourceColumn: סטטוס ליקוט כותרת

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'סטטוס ליקוט שורה'
		dataType: int64
		formatString: 0
		lineageTag: fe2cd045-c853-48f2-a7a8-2d612e609c59
		summarizeBy: sum
		sourceColumn: סטטוס ליקוט שורה

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'דגל סטורנו'
		dataType: int64
		formatString: 0
		lineageTag: 57f4b6cd-4171-4c2a-bcdf-726233ba2673
		summarizeBy: sum
		sourceColumn: דגל סטורנו

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RowInsertDatetime
		dataType: dateTime
		formatString: General Date
		lineageTag: 99b34733-6b10-434c-aa10-b357ef4bf134
		summarizeBy: none
		sourceColumn: RowInsertDatetime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 10bc8f1c-b057-4987-b1f2-37ebeb2fad7a
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'תאריך אספקה'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 2fffbb1b-3aa5-48c2-92b0-977702f0a2e6
		summarizeBy: none
		sourceColumn: תאריך אספקה

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column QuantitySupply
		dataType: double
		formatString: " #,#.##;(#,#.##)"
		lineageTag: 13e38d24-88bf-4586-b3aa-f3b912da3480
		summarizeBy: sum
		sourceColumn: QuantitySupply

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column QuantityLeft
		dataType: double
		formatString: " #,#.##;(#,#.##)"
		lineageTag: cddd058d-be23-4c07-a28a-3884fd256c33
		summarizeBy: sum
		sourceColumn: QuantityLeft

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column SpotFlag
		dataType: int64
		formatString: 0
		lineageTag: 72bca220-3fc0-4823-8430-ea7ff9173758
		summarizeBy: none
		sourceColumn: SpotFlag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OldFlag
		dataType: int64
		formatString: 0
		lineageTag: 7a545bf2-32dc-4041-9a8e-3c16861c7daa
		summarizeBy: sum
		sourceColumn: OldFlag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SupplierWarehouse
		dataType: int64
		formatString: 0
		lineageTag: 0e95d19e-c309-44ea-b6ad-f7fc058e2f4c
		summarizeBy: none
		sourceColumn: SupplierWarehouse

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UnitPriceCF
		dataType: double
		lineageTag: d69e4693-6951-4769-b6ce-0a474f51fb00
		summarizeBy: sum
		sourceColumn: UnitPriceCF

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalCF_USD
		dataType: double
		formatString: " #,#.##;(#,#.##)"
		lineageTag: 7c79450b-46ab-45c2-895f-7fa91622e27d
		summarizeBy: sum
		sourceColumn: LineTotalCF_USD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalCF_NIS
		dataType: double
		formatString: " #,#.##;(#,#.##)"
		lineageTag: 7b83a6fc-3291-4b13-ae0b-4786e3642c82
		summarizeBy: sum
		sourceColumn: LineTotalCF_NIS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPriceFOT
		dataType: double
		lineageTag: 965fb737-ce9b-466e-99c7-f83568621581
		summarizeBy: sum
		sourceColumn: UnitPriceFOT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalFOT_USD
		dataType: double
		formatString: " #,#.##;(#,#.##)"
		lineageTag: e6c6c4e1-c1d0-40c2-b194-3a543dead736
		summarizeBy: sum
		sourceColumn: LineTotalFOT_USD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalFOT_NIS
		dataType: double
		formatString: " #,#.##;(#,#.##)"
		lineageTag: ebb4effc-cd12-4934-aae2-8be3bb3f6d41
		summarizeBy: sum
		sourceColumn: LineTotalFOT_NIS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PremiumFlag
		dataType: int64
		formatString: 0
		lineageTag: 1fe7dcd6-e0f1-41f7-914f-ec6575d22502
		summarizeBy: sum
		sourceColumn: PremiumFlag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TransactionType
		dataType: int64
		formatString: 0
		lineageTag: 1b4de5cb-9a87-47f9-835e-1006767c7f06
		summarizeBy: none
		sourceColumn: TransactionType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Family
		dataType: int64
		formatString: 0
		lineageTag: 74322259-4a8c-448c-95b0-8639bd9509ec
		summarizeBy: sum
		sourceColumn: Family

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BasisQTY
		dataType: double
		lineageTag: 6f2d8ac8-50e6-4723-9565-79cc96b25d05
		summarizeBy: sum
		sourceColumn: BasisQTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FlatQTY
		dataType: double
		lineageTag: fb22e6b0-0c9d-4de8-a2d3-5d02e8d62bfc
		summarizeBy: sum
		sourceColumn: FlatQTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POL_StockExchangeDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 98676bda-773b-43a4-b45a-03f3a336c534
		summarizeBy: none
		sourceColumn: POL_StockExchangeDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PF_GeneralFactor
		dataType: double
		lineageTag: 19887cfb-f38a-461b-9859-48097072389f
		summarizeBy: sum
		sourceColumn: PF_GeneralFactor

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POL_PremiumPrice
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: fb158ce0-4945-4e02-9218-b50bba2938f1
		summarizeBy: none
		sourceColumn: POL_PremiumPrice

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column POL_StockMarketPrice
		dataType: double
		lineageTag: cbdcd08c-3c6f-49ba-83cd-b3457a03462d
		summarizeBy: sum
		sourceColumn: POL_StockMarketPrice

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SMP_Symbol
		dataType: string
		lineageTag: d3138946-a85d-4ab9-8e9d-2ae97c592830
		summarizeBy: none
		sourceColumn: SMP_Symbol

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SMPE_TempPrice
		dataType: double
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		lineageTag: 151ac7f7-d7a3-42f0-87a8-e82b554e2c3c
		summarizeBy: none
		sourceColumn: SMPE_TempPrice

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column LineTotalFlatValueBalanceUSD
		dataType: double
		lineageTag: fa552d32-e162-4c6f-924b-311d7c3609b5
		summarizeBy: sum
		sourceColumn: LineTotalFlatValueBalanceUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalFlatBalanceUSD
		dataType: double
		lineageTag: 3fd15853-7e1f-4106-b82a-7f1a86b31cf1
		summarizeBy: sum
		sourceColumn: LineTotalFlatBalanceUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderType
		dataType: string
		lineageTag: c205802b-77be-4307-a2b4-651a09c5c197
		summarizeBy: none
		sourceColumn: OrderType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MarketTempPrice
		dataType: double
		lineageTag: c859fe81-5b3b-452c-b5d8-0d4f1d2db436
		summarizeBy: sum
		sourceColumn: MarketTempPrice

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FinalPriceClosedContract
		dataType: double
		lineageTag: 31363edd-20c4-4d7c-a494-cbae1f8d1e7c
		summarizeBy: sum
		sourceColumn: FinalPriceClosedContract

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalFlatValueUSD
		dataType: double
		lineageTag: 4c215d0e-ab5a-471f-85fd-61416198ba80
		summarizeBy: sum
		sourceColumn: LineTotalFlatValueUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CFFlat
		dataType: double
		lineageTag: 4c7c837a-face-40f4-be4a-1f1bb77049c6
		summarizeBy: sum
		sourceColumn: CFFlat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CFFLAT_CC
		dataType: double
		lineageTag: c71aac5f-7bda-4abf-92b2-7b50f1fdb718
		summarizeBy: sum
		sourceColumn: CFFLAT_CC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CFFLAT_NCC
		dataType: double
		lineageTag: b8f46bb7-7cd9-4b5a-9cb2-f0034c9c45da
		summarizeBy: sum
		sourceColumn: CFFLAT_NCC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FotPrice
		dataType: double
		lineageTag: 95f63737-c120-4fb3-80bd-9e40ec331991
		summarizeBy: sum
		sourceColumn: FotPrice

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FOT_CC
		dataType: double
		lineageTag: 6353a7bf-5320-4bb6-97ab-42404e67e1d8
		summarizeBy: sum
		sourceColumn: FOT_CC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FOT_NCC
		dataType: double
		lineageTag: e7eed021-355d-4c3c-bffe-842e8716ff61
		summarizeBy: sum
		sourceColumn: FOT_NCC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OriginalQty
		dataType: double
		lineageTag: 2b818e79-0963-4f7b-a55d-2e56126a7bb6
		summarizeBy: sum
		sourceColumn: OriginalQty

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DollarRate
		dataType: double
		lineageTag: e39a293f-03a4-48b1-beeb-fee8937d0c00
		summarizeBy: sum
		sourceColumn: DollarRate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POL_StockMarketTempPriceForNoneClosed
		dataType: double
		lineageTag: ea2d24ba-8935-4f40-9b99-887d6676d3e7
		summarizeBy: sum
		sourceColumn: POL_StockMarketTempPriceForNoneClosed

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MarketTempPriceCFF_USD
		dataType: double
		lineageTag: da0def22-3ac1-446e-8900-0ab14929d63a
		summarizeBy: sum
		sourceColumn: MarketTempPriceCFF_USD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalFlatValueBalanceCFFUSD
		dataType: double
		lineageTag: 5f9ab5fc-b573-4d36-97fc-364c422cf2bf
		summarizeBy: sum
		sourceColumn: LineTotalFlatValueBalanceCFFUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MarketTempPriceFOT_USD
		dataType: double
		lineageTag: ffa7f481-46b6-40d8-a11e-a4db9b42ecab
		summarizeBy: sum
		sourceColumn: MarketTempPriceFOT_USD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalFlatValueBalanceFOTUSD
		dataType: double
		lineageTag: c5ace394-b5f4-4080-9711-19a7bc06791e
		summarizeBy: sum
		sourceColumn: LineTotalFlatValueBalanceFOTUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalFlatValueCFFUSD
		dataType: double
		lineageTag: cc41c66b-1031-4bef-bc13-a34c999df0f8
		summarizeBy: sum
		sourceColumn: LineTotalFlatValueCFFUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalFlatValueFOTUSD
		dataType: double
		lineageTag: 23675d86-1a4d-4587-80de-00e188377ca6
		summarizeBy: sum
		sourceColumn: LineTotalFlatValueFOTUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalBalanceUSD
		dataType: double
		lineageTag: e20a544f-c3e8-4875-bdb2-8d667249abc7
		summarizeBy: sum
		sourceColumn: LineTotalBalanceUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalFlatUSD
		dataType: double
		lineageTag: 96d06a68-a676-4eac-9215-2410f209df3b
		summarizeBy: sum
		sourceColumn: LineTotalFlatUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalFlatBalanceCFFUSD
		dataType: double
		lineageTag: 45f4e4e7-6e41-49d1-aa8f-212ccb357130
		summarizeBy: sum
		sourceColumn: LineTotalFlatBalanceCFFUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotalFlatBalanceFOTUSD
		dataType: double
		lineageTag: ced22c81-60f1-46a8-9ae2-072e0cf5327e
		summarizeBy: sum
		sourceColumn: LineTotalFlatBalanceFOTUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Open_Slicer
		dataType: string
		lineageTag: e0c3d883-6b50-42ba-86d6-d21baabb32ee
		summarizeBy: none
		sourceColumn: Open_Slicer

		annotation SummarizationSetBy = Automatic

	partition factOrders = m
		mode: import
		queryGroup: 'fact Tables'
		source =
				let
				    Source = Sql.Database(#"SQL Address", "MT", [Query="------ active in prod 21-1-25#(lf)-------------- מחירון יומי להשוואה-----------------#(lf)With LastCreation as (#(lf)Select OrderId,MAX(CreateDate) AS LastCreation#(lf)From tblOrderPriceS#(lf)Group By OrderID#(lf))#(lf)#(lf),LastVersion as (#(lf)Select o.OrderId,Max(DayVersion) as LastVersion#(lf)From tblOrderPriceS o#(lf)Inner Join LastCreation LC#(lf)#(tab)ON o.OrderID=LC.OrderID AND o.CreateDate=LC.LastCreation#(lf)Group By o.OrderID#(lf))#(lf)#(lf),OrderPrices as (#(lf)Select O.*#(lf)from tblOrderPriceS o#(lf)Inner Join LastCreation LC#(lf)#(tab)ON o.OrderID=LC.OrderID And o.CreateDate=LC.LastCreation#(lf)Inner Join LastVersion LV#(lf)#(tab)ON o.OrderID=LV.OrderID AND o.DayVersion = LV.LastVersion#(lf)Where 1=1#(lf)),#(lf)#(lf)BasisContract as (#(lf)Select a.POSO_SOID as ID,#(lf)ISNULL(SUM(b.TotalSuccessfullyClosed),0) as TotalContracts#(lf)FRom [dbo].[SaleOrder2PurchaseOrderLines] a#(lf)LEFT JOIN [dbo].[viewStockExchangeOrders] b#(lf)#(tab)ON a.POSO_POID = b.SEO_PurchaseOrderID AND a.POSO_POLID = b.SEO_PurchaseOrderLine#(lf)Where 1=1#(lf)and POSO_isActive = 1#(lf)and LEFT(POSO_POID,1) = 9#(lf)Group BY a.POSO_SOID#(lf))#(lf)#(lf),SMPE_1 as (#(lf)select * #(lf),ROW_NUMBER() OVER (PARTITION BY SMPE_ProductID,SMPE_Year,SMPE_Month ORDER BY SMPE_CreateDate DESC,SMPE_DueDate DESC) as rownum#(lf)from [dbo].[StockMarketProductEOM]#(lf))#(lf)#(lf),SMPE as (#(lf)select * from SMPE_1 where  rownum = 1#(lf))#(lf)#(lf),SalesOrder2Purchase as (#(lf)select * from [dbo].[SaleOrder2PurchaseOrderLines]#(lf)where POSO_IsActive = '1'#(lf)--and POSO_SOID = 128444 --131989#(lf)and POSO_HasRolloverBeenMade = 0#(lf)and LEFT(POSO_POID,2) = 90   ---- Temp Order Only#(lf))#(lf)#(lf)#(lf)#(lf)--------------------הזמנות------------------#(lf),Orders as (#(lf)SELECT #(lf)#(lf)'1' as 'EntityID'#(lf)        ,CAST(HZ.MSPR_HZMNH AS VARCHAR) AS 'OrderID'#(lf)#(tab)#(tab),1 AS 'OrderLineNumber'#(lf)#(tab)#(tab),'Orders' AS 'DocName'#(lf)#(tab)#(tab),CAST(CONVERT(INT, CONVERT(VARCHAR,HZ.QOD_MQBL))as varchar) AS 'AccountKey' -- customer from invoices in case you need just invoices #(lf)#(tab)#(tab),SUBSTRING(HZ.T_ASPQH,1,4) + '-' + SUBSTRING(HZ.T_ASPQH,5,2) + '-' + SUBSTRING(HZ.T_ASPQH,7,2) as 'תאריך אספקה'#(lf)        ,SUBSTRING(HZ.T_HZMNH,1,4) + '-' + SUBSTRING(HZ.T_HZMNH,5,2) + '-' + SUBSTRING(HZ.T_HZMNH,7,2) as 'Date'#(lf)#(tab)#(tab),null AS 'Time'#(lf)#(tab)#(tab),cast(CONVERT(INT, CONVERT(VARCHAR,HZ.AISH_MCIROT)) as varchar) AS 'AgentKey' #(lf)#(tab)#(tab),cast(CONVERT(INT, CONVERT(VARCHAR,HZ.MOTSR_MOZMN)) as varchar)+ '-' + cast(CONVERT(INT, CONVERT(VARCHAR,HZ.MOTSR_MOZMN)) as varchar) AS 'ItemKey'#(lf)#(tab)#(tab)--,CAST('1' as varchar) + CAST(CONVERT(INT, CONVERT(VARCHAR, i.BRANCH)) as varchar) AS 'BranchKey'#(lf)#(tab)#(tab),null AS 'EmployeeKey'#(lf)#(tab)#(tab),null AS 'חבר מועדון'#(lf)#(tab)#(tab)--,(1 - (1 - ii.[T$PERCENT] / 100) * (1 - i.[T$PERCENT] / 100)) AS 'DiscountPercent' -- the DiscountPercent for the invoice and invoice line#(lf)#(tab)#(tab),null AS 'DiscountPercent'#(lf)#(tab)#(tab) --,(1 - (1 - ii.[T$PERCENT] / 100) * (1 - i.[T$PERCENT] / 100)) * ii.TQUANT / 1000 * ROUND(ii.PRICE, 2) * ii.IEXCHANGE AS 'LineTotalDiscount' -- the discount from gross price to the net#(lf)#(tab)#(tab),NULL AS 'LineTotalDiscount'#(lf)#(tab)#(tab)--,ROUND(ii.PRICE, 2) * ii.IEXCHANGE AS 'UnitGrossPrice'#(lf)#(tab)#(tab),NULL AS 'UnitGrossPrice'#(lf)#(tab)#(tab)--,ROUND(ii.PRICE * (1 - ii.[T$PERCENT] / 100) * (1 - i.[T$PERCENT] / 100), 2) * ii.IEXCHANGE AS 'UnitNetPrice'#(lf)#(tab)#(tab),CASE#(lf)#(tab)         WHEN HZ.MTBE = '$' THEN MCHIR_ICH#(lf)#(tab)#(tab)   --THEN CAST(HZ.MCHIR_ICH AS decimal (12,4))#(lf)#(tab)         ELSE CAST(HZ.MCHIR_ICH *(1/SM.NEW_SHER)  AS decimal (12,4))#(lf)         END AS 'UnitNetPriceUSD'#(lf)#(tab)#(tab),HZ.CMOT_MOZMNT AS 'Quantity'#(lf)#(tab)#(tab),HZ.CMOT_SHSOPQH AS 'QuantitySupply'#(lf)#(tab)#(tab),HZ.CMOT_MOZMNT - HZ.CMOT_SHSOPQH AS 'QuantityLeft'#(lf)#(tab)#(tab)--The cost can be tor.cost * Quant or just tor.cost#(lf)#(tab)#(tab)--Option 1#(lf)#(tab)#(tab)/*,CASE WHEN tor.COSTFLAG NOT IN ('C', '\0') #(lf)#(tab)#(tab)      THEN tor.COST * (CASE WHEN (tor.QUANT) < 0.0 THEN - 1 ELSE 1 END)#(lf)#(tab)#(tab)      ELSE p.COST * ((ii.QUANT / 1000) / p.COSTQUANT) * (CASE WHEN i.DEBIT = 'C' THEN - 1 ELSE 1 END) * (CASE WHEN ii.CREDITFLAG = 'Y' THEN 0 ELSE 1 END)#(lf)#(tab)#(tab)END AS 'LineTotalCost' --------Cost without Quant#(lf)#(tab)#(tab)*/#(lf)#(tab)#(tab),NULL AS 'LineTotalCost'#(lf)#(tab)#(tab)/*,(CASE WHEN ii.CURRENCY <> '-1'#(lf)#(tab)#(tab)#(tab)THEN round(ii.IVCOST, 2) * ii.IEXCHANGE#(lf)#(tab)#(tab)#(tab)ELSE round(ii.IVCOST, 2) END) * (CASE WHEN (i.DEBIT = 'C') #(tab)THEN - 1 ELSE 1 END) AS 'LineTotalNet'*/#(lf)#(tab)#(tab),CASE#(lf)#(tab)         WHEN HZ.MTBE = '$'#(lf)#(tab)#(tab)     THEN CAST((HZ.MCHIR_ICH)*CMOT_MOZMNT AS decimal (12,4))#(lf)#(tab)         ELSE CAST(HZ.MCHIR_ICH*HZ.CMOT_MOZMNT*(1/SM.NEW_SHER) AS decimal (12,4))#(lf)         END AS 'LineTotalNetUSD'#(lf)#(tab)#(tab),CASE#(lf)#(tab)         WHEN HZ.MTBE = '$'#(lf)#(tab)#(tab)     THEN CAST((HZ.MCHIR_ICH)*(HZ.CMOT_MOZMNT - HZ.CMOT_SHSOPQH) AS decimal (12,4))#(lf)#(tab)         ELSE CAST(HZ.MCHIR_ICH*(HZ.CMOT_MOZMNT - HZ.CMOT_SHSOPQH)*(1/SM.NEW_SHER) AS decimal (12,4))#(lf)         END AS 'LineTotalBalanceUSD'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab)--, (round(ii.IVCOST, 2)/ii.IEXCHANGE) *fnc.EXCHANGE2   *(CASE WHEN (i.DEBIT = 'C') THEN - 1 ELSE 1 END) AS 'LineTotalNet_USD'#(lf)#(tab)#(tab),CASE#(lf)#(tab)         WHEN HZ.MTBE = '$'#(lf)#(tab)#(tab)     THEN CAST(HZ.MCHIR_ICH*SM.NEW_SHER AS decimal (12,4))#(lf)#(tab)         ELSE CAST(HZ.MCHIR_ICH AS decimal (12,4))#(lf)         END AS 'UnitNetPriceNIS'#(lf)#(tab)    ,CASE#(lf)#(tab)         WHEN HZ.MTBE = '$'#(lf)#(tab)#(tab)     THEN CAST((HZ.MCHIR_ICH*SM.NEW_SHER)*CMOT_MOZMNT AS decimal (12,4))#(lf)#(tab)         ELSE CAST(HZ.MCHIR_ICH*HZ.CMOT_MOZMNT AS decimal (12,4))#(lf)         END AS 'LineTotalNetNIS'#(lf)#(lf)/*#(tab)#(tab) ,CASE#(lf)#(tab)#(tab)#(tab)WHEN ps.OrderID IS NOT NULL THEN OP.CFFLAT_CC#(lf)#(tab)#(tab)#(tab)ELSE OP.CFFlat END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) AS 'UnitPriceCF'#(lf)#(tab)#(tab) ,CASE#(lf)#(tab)#(tab)#(tab)WHEN ps.OrderID IS NOT NULL THEN OP.CFFLAT_CC*ps.FlatQTY#(lf)#(tab)#(tab)#(tab)ELSE Op.CFFlat*OP.OriginalQty END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) AS 'LineTotalCF_USD'#(lf)#(tab)#(tab) ,CASE#(lf)#(tab)#(tab)#(tab)WHEN ps.OrderID IS NOT NULL THEN OP.CFFLAT_CC*ps.FlatQTY*OP.DollarRate#(lf)#(tab)#(tab)#(tab)ELSE OP.CFFlat*OP.DollarRate*OP.OriginalQty END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) AS 'LineTotalCF_NIS'#(lf)#(tab)#(tab) ,CASE#(lf)#(tab)#(tab)#(tab)WHEN ps.OrderID IS NOT NULL THEN OP.FOT_CC#(lf)#(tab)#(tab)#(tab)ELSE OP.FotPrice END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) AS 'UnitPriceFOT'#(lf)#(tab)#(tab) ,CASE#(lf)#(tab)#(tab)#(tab)WHEN ps.OrderID IS NOT NULL THEN OP.FOT_CC*ps.FlatQTY#(lf)#(tab)#(tab)#(tab)ELSE Op.FotPrice*OP.OriginalQty END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) AS 'LineTotalFOT_USD'#(lf)#(tab)#(tab) ,CASE#(lf)#(tab)#(tab)#(tab)WHEN ps.OrderID IS NOT NULL THEN OP.FOT_CC*ps.FlatQTY*OP.DollarRate#(lf)#(tab)#(tab)#(tab)ELSE OP.FotPrice*OP.DollarRate*OP.OriginalQty END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) AS 'LineTotalFOT_NIS'#(lf)#(tab)#(tab) --,OP.CFPremium AS 'UnitPricePremium'#(lf)#(tab)#(tab) --,Op.CFPremium*OP.OriginalQty AS 'LineTotalPremium_USD'#(lf)#(tab)#(tab) --,OP.CFPremium*OP.DollarRate*OP.OriginalQty AS 'LineTotalPremium_NIS'#(lf)#(tab)#(tab) ,POL.POL_StockMarketTempPriceForNoneClosed*ps.BasisQTY#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) AS 'LineTotalFlatValueBalanceUSD'#(lf)#(tab)#(tab) ,CASE#(lf)#(tab)#(tab)#(tab)WHEN ps.OrderID IS NOT NULL THEN OP.CFFLAT_NCC#(lf)#(tab)#(tab)#(tab)ELSE NULL#(tab)END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) AS 'MarketTempPriceCFF_USD'#(lf)#(tab)#(tab) ,CASE#(lf)#(tab)#(tab)#(tab)WHEN ps.OrderID IS NOT NULL THEN OP.CFFLAT_NCC*ps.BasisQTY#(lf)#(tab)#(tab)#(tab)ELSE NULL END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) AS 'LineTotalFlatValueBalanceCFFUSD'#(lf)#(tab)#(tab) ,CASE#(lf)#(tab)#(tab)#(tab)WHEN ps.OrderID IS NOT NULL THEN OP.FOT_NCC#(lf)#(tab)#(tab)#(tab)ELSE NULL#(tab)END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) AS 'MarketTempPriceFOT_USD'#(lf)#(tab)#(tab) ,CASE#(lf)#(tab)#(tab)#(tab)WHEN ps.OrderID IS NOT NULL THEN OP.FOT_NCC*ps.BasisQTY#(lf)#(tab)#(tab)#(tab)ELSE NULL END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab) AS 'LineTotalFlatValueBalanceFOTUSD'#(lf)*/#(lf)#(tab)#(tab) ,Case#(lf)#(tab)#(tab)#(tab)WHEN OP.CFPremium >0#(lf)#(tab)#(tab)#(tab)#(tab)THEN 1#(lf)#(tab)#(tab)#(tab)ELSE 0#(lf)#(tab)#(tab)END AS 'PremiumFlag'#(lf)#(tab)#(tab),CONVERT(INT, CONVERT(VARCHAR,SUBSTRING(HZ.T_ASPQH,1,4) + SUBSTRING(HZ.T_ASPQH,5,2))) AS YearMonth#(lf)#(tab)#(tab)----#(lf)#(tab)#(tab),HZ.OrderStatus AS 'סטטוס'#(lf)#(tab)#(tab),NULL AS 'ChargeFlag'  #(lf)#(tab)#(tab),NULL AS 'סטטוס ליקוט כותרת'#(lf)#(tab)    ,NULL AS 'סטטוס ליקוט שורה'#(lf)#(tab)#(tab),NULL AS 'דגל סטורנו'#(lf)#(tab)#(tab)#(lf)#(tab)#(tab),CASE#(lf)#(tab)#(tab)#(tab)WHEN DATEDIFF(dd,#(lf)#(tab)#(tab)#(tab)CAST(SUBSTRING(HZ.T_HZMNH,1,4) + '-' + SUBSTRING(HZ.T_HZMNH,5,2) + '-' + SUBSTRING(HZ.T_HZMNH,7,2) as Date)#(lf)#(tab)#(tab)#(tab),CAST(SUBSTRING(HZ.T_ASPQH,1,4) + '-' + SUBSTRING(HZ.T_ASPQH,5,2) + '-' + SUBSTRING(HZ.T_ASPQH,7,2) AS Date)) > 60#(lf)#(tab)#(tab)#(tab)#(tab)THEN 1#(lf)#(tab)#(tab)#(tab)ELSE 2#(lf)#(tab)#(tab)END as 'SpotFlag'#(lf)#(tab)#(tab),CASE#(lf)#(tab)#(tab)#(tab)WHEN DATEDIFF(dd,#(lf)#(tab)#(tab)#(tab)CAST(SUBSTRING(HZ.T_ASPQH,1,4) + '-' + SUBSTRING(HZ.T_ASPQH,5,2) + '-' + SUBSTRING(HZ.T_ASPQH,7,2) AS Date)#(lf)#(tab)#(tab)#(tab),GETDATE()) > 80 AND HZ.OrderStatus in (1,2)#(lf)#(tab)#(tab)#(tab)#(tab)THEN 1#(lf)#(tab)#(tab)#(tab)ELSE 0#(lf)#(tab)#(tab)END as 'OldFlag'#(lf)#(tab)#(tab),QOD_SHOLCH as 'SupplierWarehouse'#(lf)#(tab)#(tab),OP.ActionType AS 'TransactionType'#(lf)#(tab)#(tab),t.PO_Family as 'Family'#(lf)#(tab)#(tab),CASE #(lf)#(tab)#(tab)#(tab)WHEN HZ.OrderStatus = 4 or HZ.OrderStatus = 5#(lf)#(tab)#(tab)#(tab)#(tab)THEN NULL#(lf)#(tab)#(tab)#(tab)WHEN t.PO_Family = 2#(lf)#(tab)#(tab)#(tab)#(tab)THEN CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN isNULL(ROUND(OP.OriginalQty/OP.QtyTonePerContract,0),0) > 0 #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)THEN ((ROUND(OP.OriginalQty/OP.QtyTonePerContract,0)-ISNULL(bc.Totalcontracts,0))/ROUND(OP.OriginalQty/OP.QtyTonePerContract,0))*HZ.CMOT_MOZMNT ---- כמות שלא תומחרה =כמות הזמנה כפול(סך הכל חוזים אפשריים - חוזים שנחתמו חלקי סך כל החוזים האפשריים#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE POB.Balance#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)WHEN t.PO_Family = 1#(lf)#(tab)#(tab)#(tab)#(tab)Then Null#(lf)#(tab)#(tab)#(tab)ELSE NULL#(lf)#(tab)#(tab)END AS BasisQTY#(lf)#(tab)#(tab),CASE #(lf)#(tab)#(tab)#(tab)WHEN POB.Balance IS NULL THEN HZ.CMOT_MOZMNT#(lf)#(tab)#(tab)#(tab)WHEN HZ.OrderStatus = 4 or HZ.OrderStatus = 5#(lf)#(tab)#(tab)#(tab)#(tab)Then POB.Balance#(lf)#(tab)#(tab)#(tab)WHEN t.PO_Family = 2#(lf)#(tab)#(tab)#(tab)#(tab)THEN CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN isNULL(ROUND(OP.OriginalQty/OP.QtyTonePerContract,0),0) > 0 #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)THEN (ISNULL(bc.Totalcontracts,0)/ROUND(OP.OriginalQty/OP.QtyTonePerContract,0))*HZ.CMOT_MOZMNT ---- כמות שתומחרה =כמות הזמנה כפול חוזים שנחתמו חלקי סך כל החוזים האפשריים#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE NULL#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)WHEN t.PO_Family = 1#(lf)#(tab)#(tab)#(tab)#(tab)Then POB.Balance#(lf)#(tab)#(tab)#(tab)ELSE  POB.Balance#(lf)#(tab)#(tab)END AS FlatQTY#(lf)#(tab)#(tab)--,bc.TotalContracts as ContractSigned#(lf)#(tab)#(tab),POL_StockExchangeDate#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab),sf.PF_GeneralFactor#(lf)#(tab)#(tab),POL_PremiumPrice#(lf)#(tab)#(tab),POL_StockMarketPrice#(lf)#(tab)#(tab),smp.SMP_Symbol#(lf)#(tab)#(tab),CAST (smpe.SMPE_TempPrice as float) as SMPE_TempPrice#(lf)#(tab)#(tab),ACT.TAOR_AOPTSIH as OrderType#(lf)#(tab)#(tab),POL.POL_StockMarketTempPriceForNoneClosed as MarketTempPrice#(lf)#(tab)#(tab),POL_FinalPriceForClosedContract#(tab)#(tab)#(tab)as FinalPriceClosedContract#(lf)#(lf)#(tab)#(tab),OP.CFFlat#(lf)#(tab)#(tab),OP.CFFLAT_CC#(lf)#(tab)#(tab),OP.CFFLAT_NCC#(lf)#(tab)#(tab),OP.FotPrice#(lf)#(tab)#(tab),OP.FOT_CC#(lf)#(tab)#(tab),OP.FOT_NCC#(lf)#(tab)#(tab),OP.OriginalQty#(lf)#(tab)#(tab),OP.DollarRate#(lf)#(tab)#(tab),POL.POL_StockMarketTempPriceForNoneClosed#(lf)#(tab)#(tab),GETDATE() AS RowInsertDatetime#(lf)FROM [HZMNOT] HZ#(lf)LEFT JOIN (#(lf)           SELECT *, #(lf)                    CASE#(lf)                    #(tab)WHEN sher = 0#(lf)                    #(tab)THEN FIRST_VALUE(sher) OVER (PARTITION BY value_partition ORDER BY Tarikh) #(lf)                    #(tab)ELSE sher#(lf)                    END AS new_sher#(lf)            FROM (#(lf)                     SELECT *#(lf)#(tab)#(tab)#(tab)#(tab)#(tab) ,SUM(CASE WHEN sher=0 THEN 0 ELSE 1 END) OVER (ORDER BY tarikh ) AS value_partition#(lf)                     FROM SHERI_MTBE) m#(lf)           #(lf)           ) SM #(lf)ON SM.TARIKH=HZ.T_HZMNH#(lf)Left Join OrderPrices OP#(lf)#(tab)ON op.OrderID = Hz.MSPR_HZMNH#(lf)LEFT JOIN PurchaseOrderTypes t#(lf)#(tab)ON t.PO_TypeID = OP.ActionType#(lf)Left Join BasisContract bc#(lf)#(tab)ON op.OrderID = bc.ID#(lf)----#(lf)left join SalesOrder2Purchase sol#(lf)#(tab)on HZ.MSPR_HZMNH = sol.POSO_SOID#(lf)left join PurchaseOrderLines POL#(lf)#(tab)on sol.POSO_POID = pol.POL_OrderID and sol.POSO_POLID = pol.POL_LineID#(lf)left join ProductStockMarketFactors sf#(lf)#(tab)on pol.POL_ProductID = sf.PF_ProductID and POL.POL_FactorCode = sf.PF_FactorID #(lf)left join StockMarketProduct smp#(lf)#(tab)on POL.POL_ProductID = smp.SMP_ProductID AND MONTH(POL.POL_StockExchangeDate) = smp.SMP_MonthID#(lf)left join SMPE as smpe --(select * from SMPE where  rownum = 1) smpe#(lf)#(tab)on POL.POL_ProductID = smpe.SMPE_ProductID AND YEAR(POL.POL_StockExchangeDate) = smpe.SMPE_Year AND MONTH(POL.POL_StockExchangeDate) = smpe.SMPE_Month#(lf)Left Join viewPurchaseOrderBalance POB#(lf)#(tab)ON POL.POL_OrderID = POB.POID AND POL.POL_LineID = POB.POLineID#(lf)LEFT JOIN TBLT_PEOLOT_HZMNH_T_MSHLOCH ACT#(lf)#(tab)ON HZ.actionType = ACT.MS_AOPTSIH#(lf)#(lf)WHERE Cast(SUBSTRING(T_HZMNH,1,4) as int) >=2018 and Cast(SUBSTRING(T_HZMNH,1,4) as int) <= Year(Getdate())#(lf)AND HZ.OrderStatus<>3#(lf)AND HZ.ActionType IN (1,11,12,14)--NOT IN (2,6,7,10/*,11*/)#(lf)#(lf)--AND HZ.MSPR_HZMNH IN ('139761')--,'136892','136030','136532','137242', '135805')--'135671'-- '136227' --'133900'#(lf)--AND SUBSTRING(HZ.T_ASPQH,1,4) = 2025 AND SUBSTRING(HZ.T_ASPQH,5,2) = 01#(lf))#(lf)#(lf)SELECT#(tab)o.*#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab),CASE #(lf)#(tab)#(tab)#(tab)WHEN o.PremiumFlag = 1 THEN o.FlatQTY * FinalPriceClosedContract#(lf)#(tab)#(tab)#(tab)ELSE LineTotalBalanceUSD#(lf)#(tab)#(tab) END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AS LineTotalFlatBalanceUSD#(lf)#(tab)#(tab),CASE #(lf)#(tab)#(tab)#(tab)WHEN o.PremiumFlag = 1 THEN o.FlatQTY * FinalPriceClosedContract#(lf)#(tab)#(tab)#(tab)ELSE LineTotalNetUSD#(lf)#(tab)#(tab) END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AS LineTotalFlatUSD#(lf)#(tab)#(tab),CASE #(lf)#(tab)#(tab)#(tab)WHEN o.PremiumFlag = 1 THEN o.BasisQTY * MarketTempPrice#(lf)#(tab)#(tab)#(tab)ELSE 0#(lf)#(tab)#(tab) END#(lf)#(tab)#(tab) +#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN o.PremiumFlag = 1 THEN o.FlatQTY * FinalPriceClosedContract#(lf)#(tab)#(tab)#(tab)ELSE LineTotalNetUSD#(lf)#(tab)#(tab) END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AS LineTotalFlatValueUSD#(lf)#(lf)    ,CASE #(lf)        WHEN o.PremiumFlag = 1 THEN o.CFFLAT_CC #(lf)        ELSE o.CFFlat #(lf)    END AS UnitPriceCF,#(lf)    #(lf)    -- Calculate LineTotalCF_USD using PremiumFlag and FlatQTY (or OriginalQty)#(lf)    CASE #(lf)        WHEN o.PremiumFlag = 1 THEN o.CFFLAT_CC * o.FlatQTY #(lf)        ELSE o.CFFlat * o.OriginalQty #(lf)    END AS LineTotalCF_USD,#(lf)    #(lf)    -- Calculate LineTotalCF_NIS (apply DollarRate to the above)#(lf)    CASE #(lf)        WHEN o.PremiumFlag = 1 THEN o.CFFLAT_CC * o.FlatQTY * o.DollarRate #(lf)        ELSE o.CFFlat * o.DollarRate * o.OriginalQty #(lf)    END AS LineTotalCF_NIS,#(lf)    #(lf)    -- Calculate UnitPriceFOT based on the PremiumFlag#(lf)    CASE #(lf)        WHEN o.PremiumFlag = 1 THEN o.FOT_CC #(lf)        ELSE o.FotPrice #(lf)    END AS UnitPriceFOT,#(lf)    #(lf)    -- Calculate LineTotalFOT_USD using PremiumFlag and FlatQTY (or OriginalQty)#(lf)    CASE #(lf)        WHEN o.PremiumFlag = 1 THEN o.FOT_CC * o.FlatQTY #(lf)        ELSE o.FotPrice * o.OriginalQty #(lf)    END AS LineTotalFOT_USD,#(lf)    #(lf)    -- Calculate LineTotalFOT_NIS (apply DollarRate to the above)#(lf)    CASE #(lf)        WHEN o.PremiumFlag = 1 THEN o.FOT_CC * o.FlatQTY * o.DollarRate #(lf)        ELSE o.FotPrice * o.DollarRate * o.OriginalQty #(lf)    END AS LineTotalFOT_NIS,#(lf)    #(lf)    -- Use BasisQTY to compute the flat value balance in USD#(lf)    CASE#(lf)#(tab)#(tab)WHEN o.PremiumFlag = 1 THEN (o.POL_StockMarketTempPriceForNoneClosed * o.BasisQTY)+(o.FlatQTY * FinalPriceClosedContract) #(lf)#(tab)#(tab)ELSE LineTotalBalanceUSD#(lf)#(tab)#(tab)END AS LineTotalFlatValueBalanceUSD,#(lf)    #(lf)    -- Calculate MarketTempPriceCFF_USD and its related total using BasisQTY#(lf)    CASE #(lf)        WHEN o.PremiumFlag = 1 THEN o.CFFLAT_NCC #(lf)        ELSE NULL #(lf)    END AS MarketTempPriceCFF_USD,#(lf)    #(lf)    CASE #(lf)        WHEN o.PremiumFlag = 1 THEN (o.CFFLAT_NCC * o.BasisQTY) + (o.FlatQTY * o.CFFLAT_NCC)#(lf)        ELSE QuantityLeft*o.CFFlat #(lf)    END AS LineTotalFlatValueBalanceCFFUSD,#(lf)#(tab)CASE #(lf)        WHEN o.PremiumFlag = 1 THEN (o.FlatQTY * o.CFFLAT_NCC)#(lf)        ELSE QuantityLeft*o.CFFlat #(lf)    END AS LineTotalFlatBalanceCFFUSD,#(lf)    #(lf)    -- Calculate MarketTempPriceFOT_USD and its related total using BasisQTY#(lf)    CASE #(lf)        WHEN o.PremiumFlag = 1 THEN o.FOT_NCC #(lf)        ELSE NULL #(lf)    END AS MarketTempPriceFOT_USD,#(lf)    #(lf)    CASE #(lf)        WHEN o.PremiumFlag = 1 THEN  (o.FOT_NCC * o.BasisQTY) + (o.FlatQTY * o.FOT_NCC)--(o.FOT_NCC * o.BasisQTY)--#(lf)        ELSE QuantityLeft*o.FotPrice #(lf)    END AS LineTotalFlatValueBalanceFOTUSD,#(lf)    CASE #(lf)        WHEN o.PremiumFlag = 1 THEN (o.FOT_NCC * o.FlatQTY)#(lf)        ELSE QuantityLeft*o.FotPrice #(lf)    END AS LineTotalFlatBalanceFOTUSD,#(lf)#(lf)    CASE #(lf)        WHEN o.PremiumFlag = 1 #(lf)             THEN (o.CFFLAT_NCC * o.BasisQTY) + (o.CFFLAT_CC * o.FlatQTY)#(lf)        ELSE (o.CFFlat * o.OriginalQty)#(lf)    END AS LineTotalFlatValueCFFUSD,#(lf)    #(lf)    -- Combined calculation for FOT pricing#(lf)    CASE #(lf)        WHEN o.PremiumFlag = 1 #(lf)             THEN (o.FOT_NCC * o.BasisQTY) + (o.FOT_CC * o.FlatQTY)#(lf)        ELSE (o.FotPrice * o.OriginalQty)#(lf)    END AS LineTotalFlatValueFOTUSD,#(lf)#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN o.[סטטוס] = 1 then 'Open Order'#(lf)#(tab)#(tab)else null#(lf)#(tab)END AS 'Open_Slicer'#(lf)#(lf)/*#(tab)#(tab),CASE#(lf)#(tab)#(tab)#(tab)WHEN o.PremiumFlag = 1 THEN o.LineTotalFlatValueBalanceCFFUSD + LineTotalCF_USD#(lf)#(tab)#(tab)#(tab)ELSE LineTotalCF_USD END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AS LineTotalFlatValueCFFUSD#(lf)#(tab)#(tab),CASE#(lf)#(tab)#(tab)#(tab)WHEN o.PremiumFlag = 1 THEN o.LineTotalFlatValueBalanceFOTUSD + LineTotalCF_USD#(lf)#(tab)#(tab)#(tab)ELSE LineTotalCF_USD END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AS LineTotalFlatValueFOTUSD#(lf)*/#(lf)#(lf)FROM Orders o#(lf)where 1=1#(lf)--and OrderID = 140452#(lf)--and BasisQTY is not null#(lf)--and BasisQTY <>0#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Date", type date}, {"תאריך אספקה", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

