table Inventory_MeasureSelctionTable
	lineageTag: 5078141e-54f9-42db-a948-8bf442ca8598

	measure '1 Month QTY Avg' =
			
			CALCULATE([Total Quantity],ALL(DimDates),DATESBETWEEN(DimDates[Date],EDATE(CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			   ,-1)+1,CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)))
		formatString: #,0
		lineageTag: 00b71f04-9704-433c-ab8b-aceadedc6fd7

		changedProperty = IsHidden

	measure '3 Month QTY Avg' =
			
			CALCULATE([Total Quantity],ALL(DimDates),DATESBETWEEN(DimDates[Date],EDATE(CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			    ,-3),CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)))/3
		formatString: #,0
		lineageTag: 3a90ca18-4216-4242-8be3-6ff8387a1074

		changedProperty = IsHidden

	measure '6 Month QTY Avg' =
			
			CALCULATE([Total Quantity],ALL(DimDates),DATESBETWEEN(DimDates[Date],EDATE(CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			    ,-6),CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)))/6
		lineageTag: 34448963-e980-4600-8c21-f1fda47b7e3a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '12 Month QTY Avg' =
			
			CALCULATE([Total Quantity],ALL(DimDates),DATESBETWEEN(DimDates[Date],EDATE(CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			    ,-12),CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)))/12
		lineageTag: 6a765b0e-5865-4d22-9db9-5ee8e39c4bf5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Days Over 3 Month' =
			
			var todaydate=CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			return DATEDIFF(EDATE(todaydate,-3),todaydate,DAY)
		formatString: 0
		lineageTag: 00d860d1-808c-4e46-bfc4-746095504567

		changedProperty = IsHidden

	measure 'Days Over 1 Month' =
			
			var todaydate=CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			return DATEDIFF(EDATE(todaydate,-1),todaydate,DAY)
		formatString: 0
		lineageTag: 7aa35580-2290-439b-84ff-654c2b1d01be

		changedProperty = IsHidden

	measure 'Days Over 6 Month' =
			
			var todaydate=CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			return DATEDIFF(EDATE(todaydate,-6),todaydate,DAY)
		formatString: 0
		lineageTag: 938772ac-becb-4d93-a8bb-fbcfc00ebd5f

		changedProperty = IsHidden

	measure 'Days Over 12 Month' =
			
			var todaydate=CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			return DATEDIFF(EDATE(todaydate,-12),todaydate,DAY)
		formatString: 0
		lineageTag: bb055173-bf5c-43ba-8a2b-1400b350b483

		changedProperty = IsHidden

	measure 'Inventory Chosen Analysis' = ```
			
			IF(HASONEVALUE(Inventory_MeasureSelctionTable[ID]),
			SWITCH(MIN(Inventory_MeasureSelctionTable[ID]),
			    1,[1 Month QTY Avg],
			    2,[3 Month QTY Avg],
			    3,[6 Month QTY Avg],
			    4,[12 Month QTY Avg],
			    5,[3 Month LY QTY Avg])
			    ,[3 Month QTY Avg])
			    
			    
			```
		lineageTag: c8f9cbf8-58e4-46f7-b139-490f5d0a1fd0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Daily Inventory Chosen Analysis' =
			
			IF(HASONEVALUE(Inventory_MeasureSelctionTable[ID]),
			SWITCH(MIN(Inventory_MeasureSelctionTable[ID]),
			    1,DIVIDE([1 Month QTY Avg],[Days Over 1 Month]),
			    2,DIVIDE([3 Month QTY Avg],[Days Over 3 Month]),
			    3,DIVIDE([6 Month QTY Avg],[Days Over 6 Month]),
			    4,DIVIDE([12 Month QTY Avg],[Days Over 12 Month]),
			    5,DIVIDE([3 Month LY QTY Avg],[Days Over 3 Month LY])
			    ,DIVIDE([3 Month QTY Avg],[Days Over 3 Month])
			),DIVIDE([3 Month QTY Avg],[Days Over 3 Month]))
		formatString: 0.0
		lineageTag: 21f769c3-92b6-4d0c-85fd-70bdf7f5fa2d

		changedProperty = IsHidden

	measure 'מכר חודשי ממוצע  - ניתוח מלאי' = [Inventory Chosen Analysis]
		formatString: #,0
		lineageTag: 7d0ad719-13bc-4d38-82c9-af29108620d3

		changedProperty = IsHidden

	measure 'ממוצע יומי לתקופה שנבחרה' = [Daily Inventory Chosen Analysis]
		formatString: 0
		lineageTag: 14c928a5-3aff-416b-99bf-b66c20807200

		changedProperty = IsHidden

	measure 'Daily Sales - Inventory Recomendaiton' =
			
			var MaxDate=CALCULATE(MAX(dimDates[Date]),FILTER(ALL(dimDates),dimDates[IsHistory]=1))
			Var X=DATEDIFF(TODAY(),MAX(dimDates[Date]),DAY)
			return CALCULATE([Daily Inventory Chosen Analysis],FILTER(ALL(dimDates),dimDates[Date]=MaxDate))*X
		lineageTag: b6659800-8fea-469a-88e2-4df8c50bebc7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '3 Month LY QTY Avg' =
			
			CALCULATE([Total Quantity],ALL(DimDates),DATESBETWEEN(DimDates[Date],EDATE(CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			    ,-12),
			    EDATE(CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			    ,-9)
			    ))/3
		formatString: 0.0
		lineageTag: 11f75e76-e6a2-4b37-a97f-ab60041980dc

		changedProperty = IsHidden

	measure 'Days Over 3 Month LY' = ```
			
			 DATEDIFF(EDATE(CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			    ,-12),EDATE(CALCULATE(MAX(dimDates[Date]),dimDates[IsHistory]=1)
			    ,-9),DAY)
			
			
			
			```
		formatString: 0
		lineageTag: 5307d148-c1a3-4564-8645-eb103d553e0f

		changedProperty = IsHidden

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 33bdea8b-8719-4d1f-8a32-493fa4dcf26c
		summarizeBy: count
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ניתוח מלאי'
		dataType: string
		lineageTag: c9fbc3c4-9a57-4027-bf1c-a6661913daf7
		summarizeBy: none
		sourceColumn: ניתוח מלאי
		sortByColumn: 'Sort By'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sort By'
		dataType: int64
		formatString: 0
		lineageTag: a7e7932a-72bb-4aa9-b7bd-ad11086e091c
		summarizeBy: sum
		sourceColumn: Sort By

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Inventory_MeasureSelctionTable-488144cc-699d-4468-b3fd-d8d33b0d643f = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUbo+/frU65Ovr1S4PgHIXAHkzAeKGirF6kQrGQFZxgowFddnXp8LFDACSxkDWWboUsZgKROQfiN0OROwnCmGiSB7V15fdX359clAOVOl2FgA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [ID = _t, #"ניתוח מלאי" = _t, #"Sort By" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Sort By", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_Id = c30387d7-6419-446f-852d-0f83f1761b2a

	annotation LinkedQueryName = Inventory_MeasureSelctionTable

	annotation PBI_ResultType = Table

