table PriceType
	lineageTag: 71be67fc-882a-4478-b2de-4732a994114f

	column ID
		dataType: int64
		formatString: 0
		lineageTag: aea87ee0-ccfe-47ad-ad6d-528f1ffedfa5
		summarizeBy: count
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 961bebf8-cee4-4a96-a175-3e9f7dbb908a
		summarizeBy: none
		sourceColumn: Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition PriceType = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfIvSkktUorViVYyAvKcPd3AbGMg280/RCk2FgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Type = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Type", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

