table SwitchMeasure
	lineageTag: bb00cb26-9114-4073-a71d-1a565400473f

	column ID
		dataType: int64
		formatString: 0
		lineageTag: ebff8bd7-7ff3-4499-988e-ce2d39794b7d
		summarizeBy: count
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Measure
		dataType: string
		lineageTag: 327687af-3384-4d98-a4f1-52589c7f798a
		summarizeBy: none
		sourceColumn: Measure
		sortByColumn: ID

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition SwitchMeasure = m
		mode: import
		queryGroup: 'fact Tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQouyU/OVorViVYyAvICSouSMxKLU8ECxiDpxJzUYjDPBMgLSs1NzMxTio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Measure = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Measure", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

