table ValuePriceMeasure
	lineageTag: 9f667633-1037-4a9e-9590-6eeead7f90ce

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 0d155990-fa92-4bdd-bbd3-23b2a35c13dc
		summarizeBy: count
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Measure
		dataType: string
		lineageTag: b798b6ae-fbcf-4281-9f00-c3136b73c604
		summarizeBy: none
		sourceColumn: Measure

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition ValuePriceMeasure = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQpLzClNVYrViVYyAvICijKTgbxYAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Measure = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Measure", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

