table dimCIFQty
	lineageTag: 8c4b1e07-9a3d-4f62-b5d8-2e7a06c9f314

	/// מספר הזמנת רכש — מפתח הקשר אל factPurchaseExpenses[PurchaseOrderID]
	column PurchaseOrderID
		dataType: string
		lineageTag: 5d9e2a13-7c48-4b06-9f31-a8b4c02d6e57
		summarizeBy: none
		sourceColumn: PurchaseOrderID

		annotation SummarizationSetBy = Automatic

	/// כמות שנמכרה CIF לכל ההזמנה (ללא חיתוך תאריכים) — המחלק של עלות פריקה/דמורג'.
	/// קבוע ברמת ההזמנה: לצרוף עם MAX/SUMX על VALUES(PurchaseOrderID), לא SUM ישר.
	column CIF_Qty
		dataType: double
		lineageTag: 6a1f3b84-2d59-4e77-8c03-b1d5e94a7f26
		summarizeBy: none
		sourceColumn: CIF_Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dimCIFQty = m
		mode: import
		queryGroup: Dim
		source =
				let
				    Source = Sql.Database(#"SQL Address", "MT", [Query="-- =============================================================================#(lf)-- dimCIFQty - CIF quantity per purchase order (grain: one row per PurchaseOrderID)#(lf)--#(lf)-- מקור האמת היחיד למחלק של ""עלות לטון"" עבור פריקה (PNL 2270)#(lf)-- ודמורג' (PNL 1201). הכלל: מתחלקים ב-(OrderQuantity - CIF_Qty) ולא#(lf)-- ב-OrderQuantity, כי טונות שנמכרו CIF לא נפרקו ולכן אינן נושאות עלות פריקה.#(lf)--#(lf)-- למה זה קיים: FactGain.sql מחשב את המחלק בתוכו (CTE CIF_Qty) ומייצר את#(lf)-- DischargeCost_Base. ל-factPurchaseExpenses אין את ה-CTE sales/base_link ולכן לא#(lf)-- יכל לחשב אותו. במקום זה ה-DAX חישב מחדש דרך [CIF Qty (Sales)], שסינן על#(lf)-- [Price Term] = ""CIF"" (עמודת COALESCE) במקום על ActionType = 11, וגם הושפע ממסנני#(lf)-- תאריך - ומכאן הפער בין 14.68 ל-10.20.#(lf)--#(lf)-- ה-CTE כאן (CurrencyConvertion / sales / base_link / CIF_Qty) הועתקו מילה-במילה#(lf)-- מ-FactGain.sql. כל שינוי בהיגיון שם חייב להשתקף כאן.#(lf)--#(lf)-- שימוש במודל:#(lf)--   1. לייבא כטבלה נפרדת (Import).#(lf)--   2. לקשר dimCIFQty[PurchaseOrderID] -> factPurchaseExpenses[PurchaseOrderID] (1:N).#(lf)--   3. ב-DAX: NetTonnage = [Order Qty] - CIF_Qty. ה-CIF_Qty הוא קבוע לרמת ההזמנה,#(lf)--      לכן יש לצרוף אותו עם SUMX על VALUES(PurchaseOrderID) — לא SUM ישר על#(lf)--      שורות הוצאה, שיכפיל אותו במספר השורות.#(lf)--#(lf)-- הערות:#(lf)--   * CIF_Qty הוא כמות לכל חיי ההזמנה, בלי חיתוך תאריכים — בדיוק כמו ב-FactGain.#(lf)--     זה הכרחי: המחלק חייב להיות זהה לזה שיוצר את DischargeCost_Base.#(lf)--   * מוחזרות רק הזמנות שבאמת נמכרו CIF (CIF_Qty > 0); לשאר ה-DAX יקבל BLANK#(lf)--     ויתייחס אליו כ-0, כך שהטבלה נשארת קטנה.#(lf)-- =============================================================================#(lf)#(lf)DECLARE @CutoffDate DATE = '2024-01-01';#(lf)#(lf)with CurrencyConvertion as (#(lf)SELECT *, #(lf)         CASE#(lf)         #(tab)WHEN sher = 0#(lf)         #(tab)THEN FIRST_VALUE(sher) OVER (PARTITION BY value_partition ORDER BY Tarikh) #(lf)         #(tab)ELSE sher#(lf)         END AS new_sher#(lf)         ,CASE#(lf)         #(tab)WHEN SHER_EURO = 0#(lf)         #(tab)THEN FIRST_VALUE(SHER_EURO) OVER (PARTITION BY value_partitionEuro ORDER BY Tarikh) #(lf)         #(tab)ELSE  SHER_EURO#(lf)         END AS new_sherEuro#(lf) FROM (#(lf)          SELECT *#(lf) ,SUM(CASE WHEN sher=0 THEN 0 ELSE 1 END) OVER (ORDER BY tarikh ) AS value_partition#(lf) ,SUM(CASE WHEN SHER_EURO=0 THEN 0 ELSE 1 END) OVER (ORDER BY tarikh ) AS value_partitionEuro#(lf)          FROM SHERI_MTBE#(lf)) m#(lf))#(lf)#(lf),sales as (#(lf)  SELECT #(lf)#(tab)'Invoice' AS 'DocName'#(lf)#(tab)#(tab),Case#(lf)#(tab)#(tab)#(tab)WHEN CS.QOD_MOTSR = TM.QOD_MOTSR#(lf)#(tab)#(tab)#(tab)#(tab)THEN 'Item'#(lf)#(tab)#(tab)#(tab)ELSE 'Additional Expense'#(lf)#(tab)#(tab)END AS 'LineType'#(lf)#(tab)#(tab),CONVERT(VARCHAR,CS.QOD_LQOCH) 'AccountKey' -- customer from invoices in case you need just invoices #(lf)#(tab)#(tab),SUBSTRING(CS.T_CHSHBONIT,1,4) + '-' + SUBSTRING(CS.T_CHSHBONIT,5,2) + '-' + SUBSTRING(CS.T_CHSHBONIT,7,2) AS 'Date' -- Invoice date#(lf)#(tab)#(tab),CAST( CONVERT(VARCHAR,CS.QOD_MOTSR) as varchar) +'-' + CAST( CONVERT(VARCHAR,CS.QOD_MOTSR) as varchar) AS 'ItemKey'#(lf)#(tab)#(tab),CAST(CONVERT(VARCHAR,M.MasterProductInPurchase) as varchar) +'-' + CAST(CONVERT(VARCHAR,M.MasterProductInPurchase) as varchar) AS [מוצר על]#(lf)#(tab)#(tab),CAST(ROUND(CS.MCHIR_ICH_LLA_ME_M / NULLIF(CASE WHEN SHER_LCHISHOB <> 0 THEN SHER_LCHISHOB ELSE 1 END, 0), 2) AS FLOAT) AS 'UnitNetPriceUSD'#(lf)#(tab)#(tab),cast(ROUND(CS.MSHQL_NTO,2)AS FLOAT)  AS 'Quantity'#(lf)#(tab)#(tab),case#(lf)#(tab)#(tab)when TM.ActionType = 11 and CS.QOD_MOTSR = TM.QOD_MOTSR then TM.MSHQL_NTO#(lf)#(tab)#(tab)else 0 end#(lf)#(tab)as qty_cif#(lf)#(tab),case#(lf)#(tab)#(tab)when TM.ActionType = 1 and CS.QOD_MOTSR = TM.QOD_MOTSR then TM.MSHQL_NTO#(lf)#(tab)#(tab)else 0 end#(lf)#(tab)as qty_fot#(lf)#(tab),case#(lf)#(tab)#(tab)when TM.ActionType = 1 then 'FOT'#(lf)#(tab)#(tab)WHEN TM.ActionType = 11 then 'CIF'#(lf)#(tab)#(tab)WHEN TM.ActionType = 12 then 'FOT Premium'#(lf)#(tab)else null #(lf)#(tab)end as SalesType#(lf)#(tab)#(tab),CASE#(lf)#(tab)#(tab)#(tab)WHEN CS.QOD_MOTSR=TM.QOD_MOTSR#(lf)#(tab)#(tab)#(tab)#(tab)THEN 0#(lf)#(tab)#(tab)#(tab)ELSE Cs.CMOT#(lf)#(tab)#(tab)END as AdditionalQuantity#(lf)#(tab)#(tab),CAST(ROUND(#(lf)#(tab)#(tab)#(tab)CASE#(lf)#(tab)#(tab)#(tab)#(tab)WHEN CS.QOD_MOTSR <> 0#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)THEN (CS.MCHIR_ICH_LLA_ME_M * CS.MSHQL_NTO) / NULLIF(CASE WHEN SHER_LCHISHOB <> 0 THEN SHER_LCHISHOB ELSE CC.new_sher END, 0)#(lf)#(tab)#(tab)#(tab)#(tab)ELSE CS.MCHIR_ICH_LLA_ME_M / NULLIF(CASE WHEN SHER_LCHISHOB <> 0 THEN SHER_LCHISHOB ELSE CC.new_sher END, 0)#(lf)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)+#(lf)#(tab)#(tab)#(tab)CASE#(lf)#(tab)#(tab)#(tab)#(tab)WHEN CS.QOD_MOTSR = TM.QOD_MOTSR THEN 0#(lf)#(tab)#(tab)#(tab)#(tab)WHEN TM.QOD_MOTSR IS NULL         THEN 0#(lf)#(tab)#(tab)#(tab)#(tab)ELSE Cs.CMOT * (CS.MCHIR_ICH_LLA_ME_M / NULLIF(CASE WHEN SHER_LCHISHOB <> 0 THEN SHER_LCHISHOB ELSE CC.new_sher END, 0))#(lf)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab), 2) AS FLOAT) AS 'LineTotalNet_USD' --Invoices are always in NIS#(lf)#(tab)#(tab),CONVERT(INT, CONVERT(VARCHAR,SUBSTRING(CS.T_CHSHBONIT,1,4) + SUBSTRING(CS.T_CHSHBONIT,5,2))) AS YearMonth#(lf)#(tab)#(tab), TM.MS_TEODH as 'DeliveryNote'#(lf)#(tab)#(tab),CASE#(lf)#(tab)#(tab)#(tab)WHEN SUBSTRING(TM.TARIKH_MSHLOCH,1,4) = '0000'#(lf)#(tab)#(tab)#(tab)#(tab)THEN CAST(SUBSTRING(CS.T_CHSHBONIT,1,4) + '-' + SUBSTRING(CS.T_CHSHBONIT,5,2) + '-' + SUBSTRING(CS.T_CHSHBONIT,7,2) as date)#(lf)#(tab)#(tab)#(tab)ELSE CAST(ISNULL(SUBSTRING(TM.TARIKH_MSHLOCH,1,4) + '-' + SUBSTRING(TM.TARIKH_MSHLOCH,5,2) + '-' + SUBSTRING(TM.TARIKH_MSHLOCH,7,2),#(lf)#(tab)#(tab)ISNULL(SUBSTRING(FTM.FirstDeliveryDateTM,1,4) + '-' + SUBSTRING(FTM.FirstDeliveryDateTM,5,2) + '-' + SUBSTRING(FTM.FirstDeliveryDateTM,7,2),#(lf)#(tab)#(tab)SUBSTRING(CS.T_CHSHBONIT,1,4) + '-' + SUBSTRING(CS.T_CHSHBONIT,5,2) + '-' + SUBSTRING(CS.T_CHSHBONIT,7,2)))#(lf)#(tab)#(tab)AS date) #(lf)#(tab)#(tab)END as 'DeliveryDate'#(lf)#(tab)#(tab),HZ.MSPR_HZMNH as 'OrderID'#(lf)#(tab)#(tab),TM.QOD_SHOLCH as 'SupplierWarehouse'#(lf)#(tab)#(tab),TM.ActionType#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)as 'ActionType'#(lf)#(tab)#(tab),CASE #(lf)#(tab)#(tab)#(tab)WHEN TM.ActionType = 6 THEN G.AOPI_PEILOT#(lf)#(tab)#(tab)#(tab)ELSE act.ActionType#(lf)#(tab)#(tab)END#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)as 'ActionTypeDesc'#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab),'0'#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)as 'AdjustmentFlag'#(lf)#(tab)#(tab),'Sales'#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)as  'QuantityCategory'#(lf)FROM CHSHBONIOT_COTROT CH#(lf)Left Join GORMIM G#(lf)#(tab)on CH.QOD_LQOCH = G.QOD_GORM#(lf)Left Join TBLT_ANSHI_MCIROT AM #(lf)#(tab)on AM.SHM_AISH_MCIROT = G.AISH_MCIROT_MTPL#(lf)LEFT JOIN CHSHBONIOT_SHOROT CS #(lf)    ON CH.MS_CHSHBONIT = CS.MS_CHSHBONIT#(lf)--New line to add product family#(lf)LEFT JOIN MOTSRIM M#(lf)#(tab)ON CS.QOD_MOTSR = M.QOD_MOTSR#(lf)#(tab)--end here#(lf)LEFT JOIN TEODOT_MSHLOCH TM #(lf)#(tab)ON CS.MS_T_MSHLOCH = TM.MS_TEODH#(lf)LEFT JOIN (SELECT MS_CHSHBONIT , Min (TM.TARIKH_MSHLOCH) as 'FirstDeliveryDateTM',Min (CHS.TARIKH_MSHLOCH) as 'FirstDeliveryDateCHS'#(lf)#(tab)#(tab)#(tab)FROM CHSHBONIOT_SHOROT CHS#(lf)#(tab)#(tab)#(tab)Left Join TEODOT_MSHLOCH TM#(lf)#(tab)#(tab)#(tab)#(tab)ON TM.MS_TEODH = CHS.MS_T_MSHLOCH#(lf)#(tab)#(tab)#(tab)Where 1=1#(lf)#(tab)#(tab)#(tab)AND TM.TARIKH_MSHLOCH <>00000000#(lf)#(tab)#(tab)#(tab)AND CHS.TARIKH_MSHLOCH <>00000000#(lf)#(tab)#(tab)#(tab)Group By CHS.MS_CHSHBONIT) FTM#(lf)#(tab)ON FTM.MS_CHSHBONIT = CH.MS_CHSHBONIT#(lf)Left Join (SELECT MS_HZMNH,MS_T_MSHLOCH#(lf)#(tab)#(tab)#(tab)FROM QISHOR_T_MSHLOCH_HZMNOT#(lf)#(tab)#(tab)#(tab)) HZT#(lf)#(tab)on TM.MS_TEODH = HZT.MS_T_MSHLOCH#(lf)Left Join HZMNOT HZ#(lf)#(tab)on HZ.MSPR_HZMNH = HZT.MS_HZMNH#(lf)left join TBLT_PEOLOT_HZMNH_T_MSHLOCH act#(lf)#(tab)on TM.ActionType = act.MS_AOPTSIH#(lf)left join CurrencyConvertion CC #(lf)#(tab)ON cs.[TARIKH_MSHLOCH] = cc.Tarikh#(lf)WHERE 1=1#(lf)AND CAST(SUBSTRING(cs.T_CHSHBONIT,1,4) + '-' + SUBSTRING(cs.T_CHSHBONIT,5,2) + '-' + SUBSTRING(cs.T_CHSHBONIT,7,2) AS DATE) >= @CutoffDate#(lf)AND TM.QOD_SHOLCH <> TM.QOD_MQBL#(lf)AND CS.QOD_MOTSR <> 96#(lf)#(lf)-------OPEN Orders----------------------------------------------------------------------------------#(lf)UNION ALL#(lf)#(lf) SELECT #(lf)#(tab)'Delivery Note' as  'DocName'#(lf)#(tab),'Item' AS 'LineType'#(lf)#(tab),CONVERT(INT, CONVERT(VARCHAR, TM.QOD_MQBL)) AS 'AccountKey'#(lf)#(tab),SUBSTRING(TARIKH_MSHLOCH,1,4) + '-' + SUBSTRING(TARIKH_MSHLOCH,5,2) + '-' + SUBSTRING(TARIKH_MSHLOCH,7,2) as 'Date'#(lf)#(tab),CONVERT(VARCHAR, TM.QOD_MOTSR)+'-'+CONVERT(VARCHAR, TM.QOD_MOTSR) AS 'ItemKey'#(lf)#(tab),CAST(CONVERT(VARCHAR,M.MasterProductInPurchase) as varchar) +'-' + CAST(CONVERT(VARCHAR,M.MasterProductInPurchase) as varchar) AS [מוצר על]#(lf)#(tab),CAST(ROUND(CASE#(lf)#(tab)         WHEN TM.MTBE_SH = '$' THEN TM.MCHIR_ICH#(lf)#(tab)         ELSE TM.MCHIR_ICH * (1 / NULLIF(SM.NEW_SHER, 0))#(lf)         END, 2) AS FLOAT) AS 'UnitNetPriceUSD'#(lf)#(tab),cast(ROUND(TM.MSHQL_NTO,2)AS FLOAT) as 'Quantity'#(lf)#(tab),case#(lf)#(tab)#(tab)when TM.ActionType = 11 then TM.MSHQL_NTO#(lf)#(tab)#(tab)else 0 end#(lf)#(tab)as qty_cif#(lf)#(tab),case#(lf)#(tab)#(tab)when TM.ActionType = 1 then TM.MSHQL_NTO#(lf)#(tab)#(tab)else 0 end#(lf)#(tab)as qty_fot#(lf)#(tab),case#(lf)#(tab)#(tab)when TM.ActionType = 1 then 'FOT'#(lf)#(tab)#(tab)WHEN TM.ActionType = 11 then 'CIF'#(lf)#(tab)#(tab)WHEN TM.ActionType = 12 then 'FOT Premium'#(lf)#(tab)else null #(lf)#(tab)end as SalesType#(lf)#(tab),0 AS 'AdditionalQuantity'#(lf)#(tab),CAST(ROUND(CASE#(lf)#(tab)         WHEN TM.MTBE_SH = '$'#(lf)#(tab)#(tab)     THEN TM.MCHIR_ICH * TM.MSHQL_NTO /*TM.CMOT_SHSOPQH*/#(lf)#(tab)         ELSE TM.MCHIR_ICH * TM.MSHQL_NTO /*TM.CMOT_SHSOPQH*/ * (1 / NULLIF(SM.NEW_SHER, 0))#(lf)         END, 2) AS FLOAT) AS 'LineTotalNet_USD'#(lf)#(tab),CONVERT(INT, CONVERT(VARCHAR,SUBSTRING(T_ASPQH,1,4) + SUBSTRING(T_ASPQH,5,2))) AS YearMonth#(lf)#(tab),TM.MS_TEODH as 'DeliveryNote'#(lf)#(tab),CAST(SUBSTRING(TARIKH_MSHLOCH,1,4) + '-' + SUBSTRING(TARIKH_MSHLOCH,5,2) + '-' + SUBSTRING(TARIKH_MSHLOCH,7,2) as date) as 'DeliveryDate'#(lf)#(tab),HZ.MSPR_HZMNH as 'OrderID'#(lf)#(tab),TM.QOD_SHOLCH as 'SupplierWarehouse'#(lf)#(tab),TM.ActionType#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)as 'ActionType'#(lf)#(tab),CASE #(lf)#(tab)#(tab)WHEN TM.ActionType = 6 THEN G.AOPI_PEILOT#(lf)#(tab)#(tab)ELSE act.ActionType#(lf)#(tab)END as 'ActionTypeDesc'#(lf)#(tab),CASE#(lf)#(tab)WHEN TM.MCHIR_ICH = 0#(lf)#(tab)#(tab)THEN '1'#(lf)#(tab)ELSE '0'#(lf)#(tab)END AS 'AdjustmentFlag'#(lf)#(tab),CASE#(lf)#(tab)#(tab)WHEN TM.MCHIR_ICH <> 0 THEN 'Sales'#(lf)#(tab)#(tab)WHEN TM.MCHIR_ICH = 0 and G.AOPI_PEILOT = 'פחת' THEN 'Shortage'#(lf)#(tab)#(tab)WHEN TM.MCHIR_ICH = 0 and G.AOPI_PEILOT = 'אחסון' THEN 'Storage'#(lf)#(tab)#(tab)WHEN TM.MCHIR_ICH = 0 and G.AOPI_PEILOT NOT IN ('פחת','אחסון') then 'Swap'#(lf)#(tab)END AS 'QuantityCategory'#(lf)FROM TEODOT_MSHLOCH TM#(lf)Left Join (SELECT distinct MS_T_MSHLOCH#(lf)#(tab)#(tab)#(tab)FROM CHSHBONIOT_SHOROT#(lf)#(tab)#(tab)) CH#(lf)#(tab)on TM.MS_TEODH = CH.MS_T_MSHLOCH#(lf)LEFT JOIN MOTSRIM M#(lf)#(tab)ON TM.QOD_MOTSR = M.QOD_MOTSR#(lf)Left Join (SELECT MS_HZMNH,MS_T_MSHLOCH#(lf)#(tab)#(tab)#(tab)FROM QISHOR_T_MSHLOCH_HZMNOT#(lf)#(tab)#(tab)) HZT#(lf)#(tab)on TM.MS_TEODH = HZT.MS_T_MSHLOCH#(lf)Left Join HZMNOT HZ#(lf)#(tab)on HZ.MSPR_HZMNH = HZT.MS_HZMNH#(lf)LEFT JOIN CurrencyConvertion SM  -- reuse top-level CTE instead of repeating SHERI_MTBE inline#(lf)#(tab)ON SM.TARIKH = HZ.T_HZMNH#(lf)Left Join GORMIM G#(lf)#(tab)on TM.QOD_MQBL = G.QOD_GORM#(lf)Left Join (#(lf)#(tab)#(tab)#(tab)Select *#(lf)#(tab)#(tab)#(tab)From GORMIM#(lf)#(tab)#(tab)#(tab)Where EntityType Like N'%מקום אספקה%') W#(lf)#(tab)On W.QOD_GORM = TM.QOD_SHOLCH#(lf)left join TBLT_PEOLOT_HZMNH_T_MSHLOCH act#(lf)#(tab)on TM.ActionType = act.MS_AOPTSIH#(lf)WHERE#(lf)CH.MS_T_MSHLOCH is null#(lf)AND CAST(SUBSTRING(TARIKH_MSHLOCH,1,4) + '-' + SUBSTRING(TARIKH_MSHLOCH,5,2) + '-' + SUBSTRING(TARIKH_MSHLOCH,7,2) AS DATE) >= @CutoffDate#(lf)AND STTOS in (0,1)#(lf)AND TM.PurchaseOrderType = 0#(lf)AND TM.QOD_MOTSR <> 96 #(lf)AND TM.QOD_SHOLCH <> TM.QOD_MQBL   -- exclude internal docs (same source and destination)#(lf)  )#(lf),base_link as (#(lf)  SELECT distinct#(lf)        a.MS_TEODT_MCIRH AS DeliveryNote,#(lf)        b.MS_HZMNH AS PurchaseOrderID#(lf)    FROM QISHOR_RCSH_LMCIRH a#(lf)    LEFT JOIN QISHOR_T_MSHLOCH_HZMNOT b#(lf)        ON a.MS_TEODT_RCSH = b.MS_T_MSHLOCH#(lf)#(lf)#(tab)#(tab))#(lf)#(lf),CIF_Qty AS (#(lf)    -- זהה ל-CTE CIF_Qty ב-FactGain.sql: סכימת qty_cif (ActionType = 11) לכל הזמנה.#(lf)    SELECT#(lf)        bl.PurchaseOrderID,#(lf)        SUM(s.qty_cif) AS CIF_Qty#(lf)    FROM sales s#(lf)    INNER JOIN base_link bl#(lf)        ON bl.DeliveryNote = s.DeliveryNote#(lf)    GROUP BY bl.PurchaseOrderID#(lf))#(lf)#(lf)SELECT#(lf)    CAST(PurchaseOrderID AS VARCHAR(30)) AS PurchaseOrderID,#(lf)    CAST(CIF_Qty AS FLOAT)               AS CIF_Qty#(lf)FROM CIF_Qty#(lf)WHERE PurchaseOrderID IS NOT NULL#(lf)  AND CIF_Qty > 0#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"PurchaseOrderID", type text}, {"CIF_Qty", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

